// Bahasa Malaysia copy — same Copy shape as en.ts. Room type names stay in
// English: they are product names that match the booking portal and the photo
// library. Facts interpolate from config/site.ts; `{{name}}` slots are filled
// at runtime.
import type { Copy } from './en';
import { SITE, WEB_RATES, SHOW_PRICES, CLAIM_ONLY_HOTEL } from '../config/site';
import { neighbourhoodTitle, places } from '../data/neighbourhood';

const minRate = Math.min(...Object.values(WEB_RATES));

const nb: Copy['neighbourhood'] = {
  chipsLabel: 'Berdekatan, mengikut kategori',
  walkLabel: 'Masa berjalan kaki',
  gettingHere: 'Cara ke sini',
  airport: `Lapangan Terbang Sibu (SBW) ≈ ${SITE.distances.airportKm} km`,
  city: `Pusat bandar Sibu ≈ ${SITE.distances.cityCentreKm} km`,
  open: 'Buka',
  call: 'Hubungi',
  unverified: 'Belum disahkan',
  ring: '{{min}} minit · anggaran',
  placeOne: '1 tempat',
  placeMany: '{{n}} tempat',
  groups: { groceries: 'Barangan runcit', food: 'Makanan & kafe', health: 'Farmasi & klinik', services: 'Perkhidmatan harian' },
  title: '{{list}} — hanya beberapa langkah dari pintu anda.',
  titleMore: '{{list}} dan banyak lagi — hanya beberapa langkah dari pintu anda.',
  titleEmpty: 'Farley, betul-betul di luar pintu anda.',
  listComma: ', ',
  listAnd: ' dan ',
  phrases: {
    supermarket: 'pasar raya Farley',
    groceries: 'barangan runcit',
    cafeDownstairs: 'kafe di tingkat bawah',
    cafesBakeriesEat: 'kafe, bakeri dan tempat makan',
    bakeries: 'bakeri',
    cafesEat: 'kafe dan tempat makan',
    cafe: 'sebuah kafe',
    kopitiams: 'kopitiam',
    kopitiamsCafes: 'kopitiam dan kafe',
    kopitiamsBakery: 'kopitiam, kafe dan sebuah bakeri',
    kopitiamsBakeries: 'kopitiam, kafe dan bakeri',
    pharmaciesClinic: 'farmasi dan klinik',
    pharmaciesClinics: 'farmasi dan klinik',
    pharmacy: 'sebuah farmasi',
    services: 'perkhidmatan harian',
  },
  dailyHours: '{{times}} setiap hari',
  walkStated: 'kira-kira {{min}} minit berjalan kaki',
  walkApprox: 'anggaran {{min}} minit berjalan kaki',
  nextDoor: 'bersebelahan',
  kinds: {
    supermarket: 'Pasar raya: bangunan hijau di tengah-tengah kawasan Farley',
    cafeDownstairs: 'Kafe di tingkat bawah bangunan hotel',
    foodCourt: 'Medan selera: gerai kopitiam di bawah satu bumbung',
    foodCourtOld: 'Medan selera sebaris dengan pasar raya: gerai kopitiam',
    kopitiam: 'Kopitiam',
    cakes: 'Kek dan hidangan kafe',
    bakery: 'Bakeri',
    pharmacy: 'Farmasi',
    healthBeauty: 'Farmasi, kesihatan dan kecantikan',
    dental: 'Klinik pergigian',
    clinic: 'Klinik komuniti',
    gp: 'Klinik doktor (GP)',
    hardware: 'Kedai perkakasan',
    barber: 'Salun rambut dan kedai gunting rambut',
  },
  mustTry: {
    title: 'Wajib cuba di kopitiam',
    dishes: {
      kampua: { name: 'Mi kampua', note: 'Mi kering Foochow khas Sibu, digaul minyak bawang merah dan ditabur char siu (daging babi)' },
      kompia: { name: 'Kompia', note: 'Roti bijan Foochow yang dibakar dalam ketuhar tanah liat, kosong atau berinti daging babi' },
      redWineMeeSua: { name: 'Mi sua wain merah', note: 'Ayam yang direneh dalam wain beras merah Foochow, dihidang bersama mi sua halus' },
      dimSum: { name: 'Dim sum', note: 'Ladu dan pau kukus, paling enak pada waktu pagi' },
      redKoloMee: { name: 'Mi kolo merah', note: 'Mi telur kenyal dengan sos char siu merah' },
    },
  },
};

export const ms: Copy = {
  meta: {
    title: 'Salim Inn — Hotel di Farley Commercial Centre, Sibu',
    description: `Salim Inn ialah hotel di pusat Farley, Jalan Salim, Sibu: 29 bilik berhawa dingin, Wi-Fi percuma, kaunter penyambut tetamu 24 jam dan tempat letak kereta tetamu di depan pintu. Tempah terus${SHOW_PRICES ? ` dari RM${minRate} semalam` : ''}.`,
  },
  brand: {
    name: 'SALIM INN',
    place: 'Farley, Sibu',
    backToStart: 'Salim Inn — kembali ke permulaan',
    logoAlt: 'Salim Inn — Keselesaan yang Selesa, Bersih dan Berpatutan',
  },
  nav: {
    aria: 'Navigasi utama',
    label: 'Bab',
    play: 'Mainkan filem',
    pause: 'Jeda filem',
    replay: 'Main semula filem',
    book: 'Tempah terus',
    skipLink: 'Langkau filem dan tempah',
  },
  account: {
    signIn: 'Log masuk',
    myAccount: 'Akaun saya',
    adminConsole: 'Konsol pentadbir',
    bookAnotherStay: 'Tempah penginapan lain',
  },
  lang: { aria: 'Bahasa' },
  preloader: {
    loading: 'Memuatkan kejiranan',
    warming: 'Memanaskan lampu',
    almost: 'Hampir siap',
    ready: 'Skrol untuk bermula',
    tuning: 'Melaraskan paparan',
    steps: {
      'Sky and light': 'Langit dan cahaya',
      'Ground and rivers': 'Tanah dan sungai',
      Roads: 'Jalan raya',
      'Farley Commercial Centre': 'Farley Commercial Centre',
      'Car parks': 'Tempat letak kereta',
      Sibu: 'Sibu',
      Trees: 'Pokok',
    },
  },
  chapterNav: {
    labels: ['Farley', 'Kejiranan', 'Salim Inn', 'Ketibaan', 'Resepsionis', 'Bilik', 'Sekeliling', 'Tempah'],
    aria: 'Bab {{id}}: {{label}}',
  },
  chapters: [
    {
      id: 1,
      eyebrow: 'Farley · Sibu, Sarawak',
      title: 'Farley, Sibu.',
      body: 'Semua keperluan anda, hanya sejengkal jarak.',
    },
    {
      id: 2,
      eyebrow: 'Kejiranan',
      title: neighbourhoodTitle(places(), nb),
      body: 'Farley Commercial Centre mengelilingi blok ini, dengan pasar raya Farley di tengah-tengahnya.',
    },
    {
      id: 3,
      eyebrow: 'Lorong Salim 17',
      title: 'Salim Inn',
      body: CLAIM_ONLY_HOTEL ? 'Satu-satunya hotel di Farley.' : 'Di pusat Farley.',
    },
    {
      id: 4,
      eyebrow: 'Ketibaan',
      title: 'Tiba, parkir di depan pintu, daftar masuk.',
      body: 'Petak tetamu bertanda betul-betul di hadapan lobi, di bawah kanopi.',
    },
    {
      id: 5,
      eyebrow: 'Resepsionis',
      title: 'Kaunter kami tidak pernah tutup.',
      body: `Daftar masuk dari ${SITE.checkIn.label} · Daftar keluar sebelum ${SITE.checkOut.label} · Kaunter 24 jam`,
    },
    {
      id: 6,
      eyebrow: '29 bilik · 5 jenis bilik',
      title: 'Lima cara untuk menginap.',
      body: 'Setiap bilik mempunyai Wi-Fi berkelajuan tinggi percuma, penyaman udara, TV satelit dan bilik air en suite sendiri.',
    },
    {
      id: 7,
      eyebrow: 'Hanya sejengkal',
      title: 'Semuanya hanya sejengkal.',
      body: 'Masa berjalan kaki dari pintu hotel. Lingkaran ini hanya anggaran: jarak garis lurus, dengan mengambil kira jalan-jalan.',
    },
    {
      id: 8,
      eyebrow: 'Tempah terus',
      title: 'Tempah terus dengan Salim Inn.',
      body: SHOW_PRICES ? `Dari RM${minRate} semalam · kadar web` : 'Terbaik apabila anda menempah terus.',
    },
  ],
  bookingCard: {
    blurb: `Pilih tarikh dan bilik anda di portal tempahan Salim Inn. Daftar masuk dari ${SITE.checkIn.label}, daftar keluar sebelum ${SITE.checkOut.label}.`,
    book: 'Tempah terus',
    call: 'Hubungi {{phone}}',
  },
  welcome: {
    eyebrow: 'SELAMAT DATANG KE SALIM INN',
    title: 'Keselesaan moden.<br><em>Nilai jujur.</em>',
    intro:
      'Sejak 2012, Salim Inn mengalu-alukan pengembara yang mencari penginapan praktikal dan selesa di Sibu. Terletak di Farley Commercial Centre, kedai-kedai dan tempat makan betul-betul di luar—manakala pasukan kami sedia membantu sepanjang masa.',
  },
  trust: {
    aria: 'Ciri-ciri utama hotel',
    items: [
      { strong: '24 jam', span: 'Resepsionis dan CCTV' },
      { strong: '5 minit', span: 'Berjalan kaki ke Pasar Raya Farley' },
      { strong: 'Sejak 2012', span: 'Mengalu-alukan tetamu di Sibu' },
    ],
  },
  rooms: {
    eyebrow: 'BILIK & KADAR WEB',
    title: 'Bilik untuk setiap<br>jenis penginapan.',
    blurb: 'Dari bilik queen ringkas hingga suite keluarga, setiap penginapan merangkumi keperluan untuk malam yang selesa.',
    items: [
      { tag: '01 · SELESA UNTUK DUA', name: 'Standard Queen' },
      { tag: '02 · RUANG TAMBAHAN', name: 'Deluxe King' },
      { tag: '03 · DUA KATIL', name: 'Superior Twin' },
      { tag: '04 · MELANCONG BERSAMA', name: 'Family Room' },
      { tag: '05 · KING + QUEEN', name: 'Family Suite' },
    ],
    perNight: '/ malam',
    checkAvailability: 'Semak ketersediaan',
    rateNote:
      'Kadar web promosi dipaparkan oleh Salim Inn pada masa penerbitan. Ketersediaan dan harga muktamad disahkan semasa tempahan.',
  },
  gallery: {
    eyebrow: 'MELIHAT KE DALAM',
    title: 'Lihat tempat anda<br>akan berehat.',
    blurb: 'Gambar rasmi Salim Inn menunjukkan susun atur bilik sebenar, bilik air dan persekitaran Farley sebelum anda menempah.',
    items: [
      { alt: 'Bilik Deluxe King Salim Inn dengan katil dan perabot sisi katil', title: 'Deluxe King', caption: 'Katil lebih besar dan susun atur praktikal' },
      { alt: 'Bilik Superior Twin Salim Inn dengan dua katil berasingan', title: 'Superior Twin', caption: 'Katil berasingan untuk penginapan fleksibel' },
      { alt: 'Bilik keluarga Salim Inn dengan beberapa katil', title: 'Family Room', caption: 'Ruang untuk tinggal bersama' },
      { alt: 'Suite keluarga Salim Inn dengan katil queen dan meja kerja', title: 'Family Suite', caption: 'Ruang untuk berehat bersama' },
      { alt: 'Bilik tetamu Salim Inn dengan tingkap, televisyen, meja kerja dan penyaman udara', title: 'Dalam bilik anda', caption: 'TV, ruang kerja dan penyaman udara' },
      { alt: 'Bilik air Salim Inn dengan tuala bersih di rak krom di atas tandas', title: 'Bilik air peribadi', caption: 'Tuala bersih, sedia semasa ketibaan' },
      { alt: 'Bilik air Salim Inn dengan singki pedestal dan tingkap kabur', title: 'Bilik air en suite', caption: 'Cerah, bersih dan praktikal' },
      { alt: 'Bilik air Salim Inn dengan langsir mandian, singki pedestal dan bidet', title: 'Pancuran air panas', caption: 'Pancuran, WC dan bidet' },
      { alt: 'Bahagian luar Farley Commercial Centre berhampiran Salim Inn', title: 'Farley di depan pintu anda', caption: 'Kedai dan makanan berdekatan' },
      { alt: 'Fasad menghadap jalan Salim Inn dan cafe.cafe dengan kereta diparkir di luar', title: 'Wajah hadapan Salim Inn', caption: 'Mudah dikenali dari jalan' },
    ],
  },
  amenities: {
    eyebrow: 'KEPERLUAN SEBAGAI STANDARD',
    title: 'Semua yang anda perlukan.<br>Tiada yang tidak perlu.',
    blurb: 'Asas yang teliti memastikan penginapan anda terhubung, selesa dan selamat.',
    items: [
      { title: 'Wi-Fi berkelajuan tinggi percuma', body: 'Kekal berhubung di seluruh Salim Inn.' },
      { title: 'Bilik berhawa dingin', body: 'Ruang sejuk dan selesa anda sendiri.' },
      { title: 'Televisyen LCD dalam bilik', body: 'Berehat dengan saluran televisyen satelit.' },
      { title: 'Resepsionis 24 jam', body: 'Bantuan tersedia bila-bila anda perlukan.' },
      { title: 'CCTV 24 jam', body: 'Pengawasan di lokasi sepanjang masa.' },
      { title: 'Bilik mesra keluarga', body: 'Pilihan fleksibel untuk melancong bersama.' },
    ],
  },
  stay: {
    eyebrow: 'RANCANG KUNJUNGAN ANDA',
    title: 'Betul-betul di Farley.<br>Sedia bila anda tiba.',
    body: `Daftar masuk dari ${SITE.checkIn.label} dan daftar keluar sebelum ${SITE.checkOut.label}. Tempah dalam talian atau hubungi Salim Inn terus jika anda perlukan bantuan memilih bilik.`,
    cta: 'Semak ketersediaan',
    labels: { address: 'Alamat', call: 'Telefon', email: 'E-mel' },
    address: 'Lot 21–22, Lorong Salim 17<br>96000 Sibu, Sarawak, Malaysia',
  },
  faq: {
    eyebrow: 'PERKARA UNTUK DIKETAHUI',
    title: 'Soalan yang<br>kerap ditanya.',
    blurb: 'Jawapan ringkas untuk ketibaan yang lebih lancar. Hubungi pasukan resepsionis 24 jam jika anda perlukan apa-apa lagi.',
    items: [
      {
        q: 'Bila waktu daftar masuk dan daftar keluar?',
        a: `Daftar masuk bermula pada ${SITE.checkIn.label} dan daftar keluar sebelum ${SITE.checkOut.label}. Daftar keluar lewat tertakluk pada ketersediaan bilik dan caj tambahan; kadar sehari penuh mungkin dikenakan selepas 3:00 petang.`,
      },
      {
        q: 'Bagaimana tempahan saya disahkan?',
        a: 'Tempahan disahkan selepas bayaran penuh diterima. Kaedah pembayaran yang diterima termasuk kad kredit, PayPal dan pindahan bank.',
      },
      {
        q: 'Apakah polisi pembatalan?',
        a: 'Bayaran balik mungkin tersedia apabila notis pembatalan diberikan sekurang-kurangnya tiga hari sebelum ketibaan. Dengan notis lebih pendek—atau ketidakhadiran—malam pertama mungkin dicaj.',
      },
      {
        q: 'Adakah setiap bilik mempunyai Wi-Fi dan penyaman udara?',
        a: 'Ya. Wi-Fi percuma tersedia di seluruh Salim Inn, dan bilik tetamu termasuk penyaman udara dan televisyen.',
      },
      {
        q: 'Di manakah Salim Inn terletak?',
        a: 'Salim Inn terletak di Lot 21–22, Lorong Salim 17, Farley Commercial Centre, Sibu. Pasar Raya Farley kira-kira lima minit berjalan kaki.',
      },
      {
        q: 'Bolehkah saya berhubung dengan seseorang pada bila-bila masa?',
        a: `Ya. Resepsionis beroperasi 24 jam. Hubungi <a href="tel:${SITE.phoneE164}">${SITE.phoneDisplay}</a> atau e-mel <a href="mailto:${SITE.email}">${SITE.email}</a>.`,
      },
    ],
  },
  cta: {
    title: 'Jadikan Sibu<br>lebih terasa seperti rumah.',
    book: 'Tempah penginapan anda',
    call: 'Hubungi Salim Inn',
  },
  footer: {
    osm: 'Data peta © penyumbang OpenStreetMap',
    rights: `© ${new Date().getFullYear()} Salim Inn, Sibu`,
  },
  mobileCta: {
    rate: SHOW_PRICES ? 'dari <strong>RM{{min}}</strong> / malam' : 'Tempah terus',
  },
  frontDesk: {
    checkIn: `Daftar masuk dari ${SITE.checkIn.label}`,
    checkOut: `Daftar keluar sebelum ${SITE.checkOut.label}`,
    hours: 'Kaunter 24 jam',
  },
  neighbourhood: nb,
  configurator: {
    tabsAria: 'Jenis bilik',
    beds: 'Katil',
    size: 'Keluasan',
    sleeps: 'Muatan',
    extraBed: 'Katil tambahan',
    from: 'Dari',
    upTo: 'Sehingga {{n}} orang',
    extraBedYes: 'Tersedia · RM{{charge}}',
    extraBedNo: 'Tiada',
    rate: 'RM{{rate}} / malam · kadar web',
    bed: { single: ['{{n}} katil bujang', '{{n}} katil bujang'], queen: ['{{n}} katil queen', '{{n}} katil queen'], king: ['{{n}} katil king', '{{n}} katil king'] },
    bedSize: '{{bed}} ({{w}} × {{l}} cm)',
    bedJoin: ' + ',
    noWindow: 'Tiada tingkap: bilik dalaman, dengan langsir untuk rupa bilik bertingkap.',
    sizeFlag: 'Keluasan tiada dalam PMS — dimodelkan pada 28 m²',
    photoFlag: 'Tiada foto Standard Queen; dipaparkan dengan foto bilik tetamu umum.',
    seeReal: 'Lihat bilik sebenar',
    back3d: 'Kembali ke bilik 3D',
    photoAria: 'Foto bilik oleh pemilik',
    photo: 'Foto pemilik',
  },
  booking: {
    formLabel: 'Semak ketersediaan',
    checkIn: 'Daftar masuk',
    checkOut: 'Daftar keluar',
    adults: 'Dewasa',
    children: 'Kanak-kanak',
    room: 'Bilik',
    submit: 'Tempah terus',
    whatsapp: 'WhatsApp',
    call: 'Hubungi',
    payLine: 'Bayar dengan {{methods}}',
    webRate: 'Kadar web — terbaik apabila anda menempah terus.',
    summaryLabel: 'Butiran tempahan anda',
    copy: 'Salin butiran',
    copied: 'Disalin',
    selectToCopy: 'Telah dipilih — salin',
    continue: 'Teruskan ke tempahan',
    reopen: 'Buka semula portal tempahan',
    leadDesktop: 'Portal tempahan telah dibuka di tab baharu. Ia bermula pada langkah cariannya sendiri — gunakan butiran ini di sana:',
    leadMobile: 'Portal tempahan bermula pada langkah cariannya sendiri. Salin butiran anda, kemudian teruskan:',
    roomOption: '{{room}} · muat {{n}} orang',
    roomOptionRate: ' · dari RM{{rate}}',
    errors: {
      checkIn: 'Pilih tarikh daftar masuk anda.',
      checkInPast: 'Tarikh daftar masuk tidak boleh pada masa lalu.',
      checkOut: 'Pilih tarikh daftar keluar anda.',
      checkOutOrder: 'Tarikh daftar keluar mestilah selepas daftar masuk.',
      adults: 'Sekurang-kurangnya seorang dewasa perlu mendaftar masuk.',
      room: 'Pilih jenis bilik.',
    },
    tooMany: '{{room}} memuatkan {{base}} orang{{extra}}. Untuk {{guests}} orang, pilih {{bigger}}.',
    tooManyExtra: ' ({{n}} dengan katil tambahan)',
    tooManyAll: 'Sebuah bilik memuatkan sehingga {{max}} tetamu. Untuk {{guests}} orang, tempah dua bilik atau hubungi kami.',
    extraBedNote: '{{room}} memuatkan {{base}} orang; tambah katil tambahan (RM{{charge}}){{bigger}}.',
    extraBedBigger: ' atau pilih {{bigger}} untuk {{guests}} orang',
    adult: ['{{n}} dewasa', '{{n}} dewasa'],
    child: ['{{n}} kanak-kanak', '{{n}} kanak-kanak'],
    night: ['{{n}} malam', '{{n}} malam'],
    listSep: ', ',
    summaryStay: 'Daftar masuk {{in}} · Daftar keluar {{out}} ({{nights}})',
    summaryExtraBed: ' · katil tambahan',
    summaryRate: 'Dari RM{{rate}} semalam · kadar web',
    whatsappText: 'Helo {{hotel}}, saya ingin membuat tempahan:\n{{summary}}',
    cancellation: 'Pembatalan percuma dengan notis sekurang-kurangnya 3 hari. Pembatalan lewat atau tidak hadir dicaj untuk malam pertama.',
    paymentMethods: ['Tunai', 'Visa', 'Mastercard', 'Kad debit', 'Sarawak Pay', 'Pindahan bank', 'PayPal', 'Boost', 'MAE', 'QRPay'],
    dateLocale: 'ms-MY',
  },
  fallback: {
    note: 'Ini versi pegun filem Salim Inn. Pelayar anda tidak dapat memaparkannya dalam 3D, jadi setiap bab ialah satu bingkai.',
    alts: [
      'Sibu dari udara pada waktu senja, dengan sungai di sebalik bandar',
      'Farley Commercial Centre dari atas, dengan deretan kedainya mengelilingi pasar raya',
      'Blok sudut Salim Inn pada waktu senja, dengan papan tanda bumbungnya menyala',
      'Pintu masuk Salim Inn di bawah kanopi, dengan tempat letak kereta tetamu di hadapan',
      'Kaunter tempahan di lobi: granit hitam di hadapan mural yang berwarna-warni',
      'Sebuah bilik tetamu Deluxe King',
      'Hotel dan lingkaran Farley dari atas, dengan gelang masa berjalan kaki dari pintu',
      'Salim Inn dan lingkaran Farley pada waktu senja',
    ],
  },
};
