// 简体中文 copy — same Copy shape as en.ts. Facts interpolate from
// config/site.ts; `{{name}}` slots are filled at runtime.
// DRAFT — pending native-speaker review.
import type { Copy } from './en';
import { SITE, WEB_RATES, SHOW_PRICES, CLAIM_ONLY_HOTEL } from '../config/site';
import { neighbourhoodTitle, places } from '../data/neighbourhood';

const minRate = Math.min(...Object.values(WEB_RATES));

const nb: Copy['neighbourhood'] = {
  chipsLabel: '周边设施，按类别',
  walkLabel: '步行时间',
  gettingHere: '交通',
  airport: `诗巫机场（SBW）约 ${SITE.distances.airportKm} 公里`,
  city: `诗巫市中心约 ${SITE.distances.cityCentreKm} 公里`,
  open: '营业时间',
  call: '致电',
  unverified: '尚未核实',
  ring: '约{{min}}分钟',
  placeOne: '1处',
  placeMany: '{{n}}处',
  groups: { groceries: '超市与日用品', food: '餐饮与咖啡馆', health: '药房与诊所', services: '日常服务' },
  title: '{{list}}——出门即达。',
  titleEmpty: 'Farley，就在门外。',
  listComma: '、',
  listAnd: '和',
  phrases: {
    supermarket: 'Farley超市',
    groceries: '日用品商店',
    cafeDownstairs: '楼下的咖啡馆',
    cafesBakeriesEat: '咖啡馆、烘焙店与餐馆',
    bakeries: '烘焙店',
    cafesEat: '咖啡馆与餐馆',
    cafe: '咖啡馆',
    pharmaciesClinic: '药房与诊所',
    pharmacy: '药房',
    services: '日常服务',
  },
  walkStated: '步行约{{min}}分钟',
  walkApprox: '步行约{{min}}分钟（估算）',
  nextDoor: '就在隔壁',
};

export const zh: Copy = {
  meta: {
    title: 'Salim Inn——诗巫Farley商业中心酒店',
    description: `Salim Inn位于诗巫Jalan Salim的Farley中心地带：29间空调客房、免费Wi-Fi、24小时前台及门前宾客停车位${SHOW_PRICES ? `，直接预订每晚RM${minRate}起` : ''}。`,
  },
  brand: {
    name: 'SALIM INN',
    place: 'Farley · 诗巫',
    backToStart: 'Salim Inn——返回首页',
    logoAlt: 'Salim Inn——舒适洁净，实惠安心',
  },
  nav: {
    aria: '主导航',
    label: '章节',
    play: '播放影片',
    pause: '暂停影片',
    replay: '重新播放',
    book: '直接预订',
    skipLink: '跳过影片直接预订',
  },
  account: {
    signIn: '登录',
    myAccount: '我的账户',
    adminConsole: '管理后台',
    bookAnotherStay: '再次预订',
  },
  lang: { aria: '语言' },
  preloader: {
    loading: '正在加载街区',
    warming: '灯光预热中',
    almost: '即将完成',
    ready: '滚动开始',
    tuning: '正在调校画面',
    steps: {
      'Sky and light': '天空与光线',
      'Ground and rivers': '地面与河流',
      Roads: '道路',
      'Farley Commercial Centre': 'Farley商业中心',
      'Car parks': '停车场',
      Sibu: '诗巫',
      Trees: '树木',
    },
  },
  chapterNav: {
    labels: ['Farley', '街区', 'Salim Inn', '抵达', '前台', '客房', '举步即达', '预订'],
    aria: '第{{id}}章：{{label}}',
  },
  chapters: [
    {
      id: 1,
      eyebrow: 'Farley · 砂拉越诗巫',
      title: 'Farley · 诗巫',
      body: '一切所需，举步即达。',
    },
    {
      id: 2,
      eyebrow: '街区',
      title: neighbourhoodTitle(places(), nb),
      body: 'Farley商业中心环绕整个街区，Farley超市就在其中心。',
    },
    {
      id: 3,
      eyebrow: 'Lorong Salim 17',
      title: 'Salim Inn',
      body: CLAIM_ONLY_HOTEL ? 'Farley唯一的酒店。' : '位于Farley中心。',
    },
    {
      id: 4,
      eyebrow: '抵达',
      title: '抵达、门前停车、办理入住。',
      body: '标有宾客专用的停车位就在大堂门前、雨棚之下。',
    },
    {
      id: 5,
      eyebrow: '前台',
      title: '前台全天不打烊。',
      body: '下午2:00起入住 · 中午12:00前退房 · 前台24小时服务',
    },
    {
      id: 6,
      eyebrow: '29间客房 · 5种房型',
      title: '五种住宿方式。',
      body: '每间客房均配备免费高速Wi-Fi、空调、卫星电视及独立卫浴。',
    },
    {
      id: 7,
      eyebrow: '举步即达',
      title: '一切举步即达。',
      body: '从酒店门口出发的步行时间。圆环仅为估算：按直线距离计算，并已考虑街道绕行。',
    },
    {
      id: 8,
      eyebrow: '直接预订',
      title: '通过Salim Inn直接预订。',
      body: SHOW_PRICES ? `每晚RM${minRate}起 · 官网价` : '直接预订更优惠。',
    },
  ],
  bookingCard: {
    blurb: '请在Salim Inn预订门户选择日期与房型。下午2:00起入住，中午12:00前退房。',
    book: '直接预订',
    call: '致电 {{phone}}',
  },
  welcome: {
    eyebrow: '欢迎来到SALIM INN',
    title: '现代舒适。<br><em>实在价格。</em>',
    intro:
      '自2012年起，Salim Inn一直接待寻求诗巫实用舒适住宿的旅客。酒店坐落于Farley商业中心，购物与餐饮近在咫尺，贴心团队全天候为您服务。',
  },
  trust: {
    aria: '酒店亮点',
    items: [
      { strong: '24小时', span: '前台与闭路电视' },
      { strong: '5分钟', span: '步行至Farley超市' },
      { strong: '自2012年', span: '在诗巫迎接宾客' },
    ],
  },
  rooms: {
    eyebrow: '客房与官网价格',
    title: '每种住宿方式<br>都有合适客房。',
    blurb: '从简约大床房到家庭套房，每次入住均包含舒适一夜所需的一切。',
    items: [
      { tag: '01 · 舒适双人', name: '标准大床房' },
      { tag: '02 · 更宽敞', name: '豪华大床房' },
      { tag: '03 · 双床', name: '高级双床房' },
      { tag: '04 · 结伴同行', name: '家庭房' },
      { tag: '05 · 大床+大床', name: '家庭套房' },
    ],
    perNight: ' / 晚',
    checkAvailability: '查询空房',
    rateNote: '所示为Salim Inn发布时的促销官网价格。空房情况与最终价格将在预订时确认。',
  },
  gallery: {
    eyebrow: '一睹内部',
    title: '先看看您将<br>安顿的地方。',
    blurb: 'Salim Inn官方照片让您在预订前看到真实客房布局、卫浴与Farley周边环境。',
    items: [
      { alt: 'Salim Inn豪华大床房，配备大床与床头家具', title: '豪华大床房', caption: '更宽敞的床铺与实用的空间布局' },
      { alt: 'Salim Inn高级双床房，配有两张独立单人床', title: '高级双床房', caption: '独立双床，住宿更灵活' },
      { alt: 'Salim Inn家庭房，配有多张床', title: '家庭房', caption: '同住的宽敞空间' },
      { alt: 'Salim Inn家庭套房，配备大床与书桌', title: '家庭套房', caption: '与家人共享的宽裕空间' },
      { alt: 'Salim Inn客房，配有窗户、电视、书桌与空调', title: '客房内部', caption: '电视、工作区与空调' },
      { alt: 'Salim Inn浴室，马桶上方的镀铬毛巾架放着干净毛巾', title: '独立浴室', caption: '干净毛巾，到店即备' },
      { alt: 'Salim Inn浴室，配有立柱式洗手盆与磨砂窗', title: '套房卫浴', caption: '明亮、干净、实用' },
      { alt: 'Salim Inn浴室，配有浴帘、立柱洗手盆与洁身喷头', title: '热水淋浴', caption: '淋浴、马桶与洁身喷头' },
      { alt: 'Salim Inn附近的Farley商业中心外观', title: 'Farley就在门口', caption: '购物餐饮近在咫尺' },
      { alt: 'Salim Inn与cafe.cafe临街外观，门前有车辆停放', title: 'Salim Inn临街门脸', caption: '在路边一眼可辨' },
    ],
  },
  amenities: {
    eyebrow: '标准配备',
    title: '所需皆有。<br>冗余皆无。',
    blurb: '周到的基础配备让住宿保持互联、舒适与安全。',
    items: [
      { title: '免费高速Wi-Fi', body: 'Salim Inn全馆覆盖，时刻在线。' },
      { title: '空调客房', body: '属于您的凉爽舒适空间。' },
      { title: '房内液晶电视', body: '卫星电视频道伴您放松。' },
      { title: '24小时前台', body: '随时为您提供帮助。' },
      { title: '24小时监控', body: '全天候现场监控。' },
      { title: '家庭友好客房', body: '结伴出行的灵活之选。' },
    ],
  },
  stay: {
    eyebrow: '规划行程',
    title: '就在Farley。<br>随时恭候。',
    body: '下午2:00起入住，中午12:00前退房。可在线预订，如需帮助选择房型也可直接联系Salim Inn。',
    cta: '查询空房',
    labels: { address: '地址', call: '电话', email: '邮箱' },
    address: 'Lot 21–22, Lorong Salim 17<br>96000 Sibu, Sarawak, Malaysia',
  },
  faq: {
    eyebrow: '常见问题',
    title: '常见<br>问题',
    blurb: '简明解答助您顺利抵达。如需其他帮助，请联系24小时前台。',
    items: [
      {
        q: '入住和退房时间？',
        a: '下午2:00起办理入住，中午12:00前退房。延迟退房视房态而定并可能收取额外费用；下午3:00后可能按全天房价收费。',
      },
      {
        q: '预订如何确认？',
        a: '收到全额付款后预订即获确认。支持的付款方式包括信用卡、PayPal及银行转账。',
      },
      {
        q: '取消政策是什么？',
        a: '在抵达前至少三天通知取消可获得退款。不足三天通知或未到店入住，可能收取首晚房费。',
      },
      {
        q: '每间客房都有Wi-Fi和空调吗？',
        a: '是的。Salim Inn全馆覆盖免费Wi-Fi，客房均配备空调与电视。',
      },
      {
        q: 'Salim Inn在哪里？',
        a: 'Salim Inn位于诗巫Farley商业中心Lorong Salim 17号Lot 21–22。Farley超市步行约五分钟。',
      },
      {
        q: '可以随时联系到人吗？',
        a: `可以。前台24小时服务。致电<a href="tel:${SITE.phoneE164}">${SITE.phoneDisplay}</a>或发送邮件至<a href="mailto:${SITE.email}">${SITE.email}</a>。`,
      },
    ],
  },
  cta: {
    title: '让诗巫<br>更像家一点。',
    book: '预订住宿',
    call: '致电Salim Inn',
  },
  footer: {
    osm: '地图数据 © OpenStreetMap 贡献者',
    rights: `© ${new Date().getFullYear()} Salim Inn, Sibu`,
  },
  mobileCta: {
    rate: SHOW_PRICES ? '每晚 <strong>RM{{min}}</strong> 起' : '直接预订',
  },
  frontDesk: {
    checkIn: '下午2:00起入住',
    checkOut: '中午12:00前退房',
    hours: '前台24小时服务',
  },
  neighbourhood: nb,
  configurator: {
    tabsAria: '房型',
    beds: '床型',
    size: '面积',
    sleeps: '入住人数',
    extraBed: '加床',
    from: '价格',
    upTo: '最多{{n}}人',
    extraBedYes: '可加床 · RM{{charge}}',
    extraBedNo: '不可加床',
    rate: '每晚RM{{rate}}起 · 官网价',
    bed: { single: ['{{n}}张单人床', '{{n}}张单人床'], queen: ['{{n}}张大床', '{{n}}张大床'], king: ['{{n}}张特大床', '{{n}}张特大床'] },
    bedSize: '{{bed}}（{{w}} × {{l}} 厘米）',
    bedJoin: ' + ',
    noWindow: '无窗：内侧房间，以窗帘营造有窗的观感。',
    sizeFlag: 'PMS中无此面积数据——按28平方米建模',
    photoFlag: '暂无标准大床房照片；此处展示的是通用客房照片。',
    seeReal: '查看真实房间',
    back3d: '返回3D房间',
    photoAria: '业主拍摄的房间照片',
    photo: '业主照片',
  },
  booking: {
    formLabel: '查询空房',
    checkIn: '入住',
    checkOut: '退房',
    adults: '成人',
    children: '儿童',
    room: '房型',
    submit: '直接预订',
    whatsapp: 'WhatsApp',
    call: '致电',
    payLine: '支付方式：{{methods}}',
    webRate: '官网价——直接预订最优惠。',
    summaryLabel: '您的预订详情',
    copy: '复制详情',
    copied: '已复制',
    selectToCopy: '已选中——请复制',
    continue: '继续预订',
    reopen: '再次打开预订门户',
    leadDesktop: '预订门户已在新标签页中打开。它会从自己的搜索步骤开始——请在那里使用以下详情：',
    leadMobile: '预订门户会从自己的搜索步骤开始。请先复制您的详情，然后继续：',
    roomOption: '{{room}} · 可住{{n}}人',
    roomOptionRate: ' · RM{{rate}}起',
    errors: {
      checkIn: '请选择入住日期。',
      checkInPast: '入住日期不能早于今天。',
      checkOut: '请选择退房日期。',
      checkOutOrder: '退房日期必须晚于入住日期。',
      adults: '至少需有一位成人入住。',
      room: '请选择房型。',
    },
    tooMany: '{{room}}可住{{base}}人{{extra}}。{{guests}}人入住，请选择{{bigger}}。',
    tooManyExtra: '（加床后可住{{n}}人）',
    tooManyAll: '单间最多可住{{max}}位宾客。{{guests}}人入住，请预订两间客房或致电我们。',
    extraBedNote: '{{room}}可住{{base}}人；可加一张床（RM{{charge}}）{{bigger}}。',
    extraBedBigger: '，或选择{{bigger}}供{{guests}}人入住',
    adult: ['{{n}}位成人', '{{n}}位成人'],
    child: ['{{n}}名儿童', '{{n}}名儿童'],
    night: ['{{n}}晚', '{{n}}晚'],
    listSep: '，',
    summaryStay: '入住 {{in}} · 退房 {{out}}（{{nights}}）',
    summaryExtraBed: ' · 加床',
    summaryRate: '每晚RM{{rate}}起 · 官网价',
    whatsappText: '您好，{{hotel}}，我想预订：\n{{summary}}',
    cancellation: '入住前至少3天通知可免费取消。逾期取消或未入住将收取首晚房费。',
    paymentMethods: ['现金', 'Visa', 'Mastercard', '借记卡', 'Sarawak Pay', '银行转账', 'PayPal', 'Boost', 'MAE', 'QRPay'],
    dateLocale: 'zh-CN',
  },
  fallback: {
    note: '这是Salim Inn影片的静态版本。您的浏览器无法以3D显示，因此每一章都以单幅画面呈现。',
    alts: [
      '黄昏时分从空中俯瞰诗巫，城镇后方是河流',
      '从上方俯瞰Farley商业中心，商铺环绕着超市',
      '黄昏时的Salim Inn街角楼宇，屋顶招牌亮起',
      '雨棚下的Salim Inn入口，门前设有宾客停车位',
      '大堂里的接待柜台：黑色花岗岩台面，身后是一幅色彩缤纷的壁画',
      '一间豪华大床房',
      '从上方俯瞰酒店与Farley环形街区，以门口为中心标出步行时间圆环',
      '黄昏时分的Salim Inn与Farley环形街区',
    ],
  },
};
