/**
 * Page coverage manifest — the machine-readable inventory of every routed
 * page surface and the test files that cover it.
 *
 * `pageCoverage.test.ts` enforces it:
 *  - every routeRegistry id appears here,
 *  - every file under src/routes/ (except __root.tsx) appears here,
 *  - every listed component/test file exists on disk,
 *  - every `page` entry has at least one smoke test and one axe test file.
 *
 * When you add a route, add an entry here or the meta-test fails.
 */

export type PageKind = 'page' | 'redirect' | 'status';
export type PageVisibility = 'auth' | 'unauth' | 'public' | 'mixed';

export interface PageManifestEntry {
  /** Registry id when the page comes from routeRegistry, else a stable slug. */
  id: string;
  /** URL path(s) that render this page surface. */
  routePaths: string[];
  /** File(s) under src/routes/ that mount it. */
  routeFiles: string[];
  kind: PageKind;
  visibility: PageVisibility;
  /** Page component source relative to src/ (null for redirects). */
  component: string | null;
  /** Test file(s) asserting the page renders its meaningful state. */
  smokeTests: string[];
  /** Test file(s) running an axe scan (may equal smokeTests). */
  axeTests: string[];
  /** Test file(s) with deeper workflow assertions, where justified. */
  workflowTests?: string[];
  notes?: string;
}

/**
 * Routes that only redirect — no page surface to test. Asserted by the
 * meta-test so a future "temporary redirect" can't hide an untested page.
 */
export const REDIRECT_ROUTES: Array<{ routeFile: string; path: string; target: string }> = [
  { routeFile: 'guest-config.tsx', path: '/guest-config', target: '/guest-relations/guests' },
  { routeFile: 'promotions.tsx', path: '/promotions', target: '/campaigns' },
  { routeFile: 'reports.tsx', path: '/reports', target: '/insights' },
  { routeFile: 'portal/index.tsx', path: '/portal', target: '/guest-portal' },
  { routeFile: 'portal/book.tsx', path: '/portal/book', target: '/guest-portal?view=booking' },
];

/** Route files that never render a page of their own. */
export const NON_PAGE_ROUTE_FILES = ['__root.tsx'];

export const PAGE_MANIFEST: PageManifestEntry[] = [
  // ── public / mixed ────────────────────────────────────────────────────────
  {
    id: 'landing',
    routePaths: ['/'],
    routeFiles: ['index.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'components/layout/LandingPage.tsx',
    smokeTests: ['components/layout/LandingPage.test.tsx'],
    axeTests: ['components/layout/LandingPage.test.tsx'],
    notes: 'Index route also mounts the dashboard for signed-in staff.',
  },
  {
    id: 'dashboard',
    routePaths: ['/', '/admin-portal'],
    routeFiles: ['index.tsx', 'admin-portal.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/dashboard/components/DashboardRouter.tsx',
    smokeTests: ['features/dashboard/components/DashboardRouter.test.tsx'],
    // DashboardRouter.test.tsx stubs its children to test role dispatch; the
    // axe scan lives in a dedicated file that renders both real surfaces.
    axeTests: ['features/dashboard/components/DashboardSurfaces.axe.test.tsx'],
  },
  // ── auth flow ─────────────────────────────────────────────────────────────
  {
    id: 'login',
    routePaths: ['/login'],
    routeFiles: ['login.tsx'],
    kind: 'page',
    visibility: 'unauth',
    component: 'features/auth/components/LoginPage.tsx',
    smokeTests: ['features/auth/components/LoginPage.test.tsx'],
    axeTests: ['features/auth/components/LoginPage.test.tsx'],
    workflowTests: ['features/auth/components/LoginPage.test.tsx'],
  },
  {
    id: 'register',
    routePaths: ['/register'],
    routeFiles: ['register.tsx'],
    kind: 'page',
    visibility: 'unauth',
    component: 'features/auth/components/RegisterPage.tsx',
    smokeTests: ['features/auth/components/RegisterPage.test.tsx'],
    axeTests: ['features/auth/components/RegisterPage.test.tsx'],
    workflowTests: ['features/auth/components/RegisterPage.test.tsx'],
  },
  {
    id: 'verify-email',
    routePaths: ['/verify-email'],
    routeFiles: ['verify-email.tsx'],
    kind: 'page',
    visibility: 'unauth',
    component: 'features/auth/components/EmailVerificationPage.tsx',
    smokeTests: ['features/auth/components/EmailVerificationPage.test.tsx'],
    axeTests: ['features/auth/components/EmailVerificationPage.test.tsx'],
  },
  {
    id: 'complete-profile',
    routePaths: ['/complete-profile'],
    routeFiles: ['complete-profile.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/auth/components/CompleteProfilePage.tsx',
    smokeTests: ['features/auth/components/CompleteProfilePage.test.tsx'],
    axeTests: ['features/auth/components/CompleteProfilePage.test.tsx'],
  },
  {
    id: 'enroll-two-factor',
    routePaths: ['/enroll-two-factor'],
    routeFiles: ['enroll-two-factor.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/auth/components/EnrollTwoFactorPage.tsx',
    smokeTests: ['features/auth/components/EnrollTwoFactorPage.test.tsx'],
    axeTests: ['features/auth/components/EnrollTwoFactorPage.test.tsx'],
    workflowTests: ['features/auth/components/EnrollTwoFactorPage.test.tsx'],
  },
  // ── guest check-in (unauthenticated) ──────────────────────────────────────
  {
    id: 'guest-checkin',
    routePaths: ['/guest-checkin'],
    routeFiles: ['guest-checkin/index.tsx'],
    kind: 'page',
    visibility: 'unauth',
    component: 'features/bookings/components/GuestCheckInLanding.tsx',
    smokeTests: ['features/bookings/components/GuestCheckInLanding.test.tsx'],
    axeTests: ['features/bookings/components/GuestCheckInLanding.test.tsx'],
  },
  {
    id: 'guest-checkin-verify',
    routePaths: ['/guest-checkin/verify'],
    routeFiles: ['guest-checkin/verify.tsx'],
    kind: 'page',
    visibility: 'unauth',
    component: 'features/bookings/components/GuestCheckInVerify.tsx',
    smokeTests: ['features/bookings/components/GuestCheckInVerify.test.tsx'],
    axeTests: ['features/bookings/components/GuestCheckInVerify.test.tsx'],
  },
  {
    id: 'guest-checkin-form',
    routePaths: ['/guest-checkin/form'],
    routeFiles: ['guest-checkin/form.tsx'],
    kind: 'page',
    visibility: 'unauth',
    component: 'features/bookings/components/GuestCheckInForm.tsx',
    smokeTests: ['features/bookings/components/GuestCheckInForm.test.tsx'],
    axeTests: ['features/bookings/components/GuestCheckInForm.test.tsx'],
    workflowTests: ['features/bookings/components/GuestCheckInForm.test.tsx'],
  },
  {
    id: 'guest-checkin-confirm',
    routePaths: ['/guest-checkin/confirm'],
    routeFiles: ['guest-checkin/confirm.tsx'],
    kind: 'page',
    visibility: 'unauth',
    component: 'features/bookings/components/GuestCheckInConfirmation.tsx',
    smokeTests: ['features/bookings/components/GuestCheckInConfirmation.test.tsx'],
    axeTests: ['features/bookings/components/GuestCheckInConfirmation.test.tsx'],
  },
  // ── guest portal ──────────────────────────────────────────────────────────
  {
    id: 'portal-dashboard',
    routePaths: ['/guest-portal'],
    routeFiles: ['guest-portal.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/guestPortal/components/PortalDashboardPage.tsx',
    smokeTests: ['features/guestPortal/components/PortalDashboardPage.test.tsx'],
    axeTests: ['features/guestPortal/components/PortalDashboardPage.test.tsx'],
  },
  {
    id: 'portal-book',
    routePaths: ['/guest-portal?view=booking'],
    routeFiles: ['guest-portal.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/guestPortal/booking/PortalBookingPage.tsx',
    smokeTests: [
      'features/guestPortal/booking/PortalBookingPage.test.tsx',
      'features/guestPortal/booking/PortalBookingPageAnonymous.test.tsx',
    ],
    axeTests: [
      'features/guestPortal/booking/PortalBookingPage.test.tsx',
      'features/guestPortal/booking/PortalBookingPageAnonymous.test.tsx',
    ],
    workflowTests: [
      'features/guestPortal/booking/PortalBookingPage.test.tsx',
      'features/guestPortal/booking/PortalBookingPageAnonymous.test.tsx',
    ],
    notes: 'guest-portal.tsx picks this component when ?view=booking; also the anonymous-booking surface.',
  },
  {
    id: 'offers',
    routePaths: ['/offers'],
    routeFiles: ['offers.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/promotions/pages/OffersPage.tsx',
    smokeTests: ['features/promotions/pages/OffersPage.test.tsx'],
    axeTests: ['features/promotions/pages/OffersPage.test.tsx'],
  },
  // ── legal documents (public) ──────────────────────────────────────────────
  {
    id: 'legal-terms',
    routePaths: ['/legal/terms'],
    routeFiles: ['legal/terms.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/legal/pages/TermsPage.tsx',
    smokeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    axeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    notes: 'Thin wrapper over LegalDocumentPage(documentId="terms_of_service").',
  },
  {
    id: 'legal-privacy',
    routePaths: ['/legal/privacy'],
    routeFiles: ['legal/privacy.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/legal/pages/PrivacyPage.tsx',
    smokeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    axeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    notes: 'Thin wrapper over LegalDocumentPage(documentId="privacy_policy").',
  },
  {
    id: 'legal-payment-terms',
    routePaths: ['/legal/payment-terms'],
    routeFiles: ['legal/payment-terms.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/legal/pages/PaymentTermsPage.tsx',
    smokeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    axeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    notes: 'Thin wrapper over LegalDocumentPage(documentId="payment_terms").',
  },
  {
    id: 'legal-identity-verification',
    routePaths: ['/legal/identity-verification'],
    routeFiles: ['legal/identity-verification.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/legal/pages/IdentityVerificationPage.tsx',
    smokeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    axeTests: ['features/legal/components/LegalDocumentPage.test.tsx'],
    notes: 'Thin wrapper over LegalDocumentPage(documentId="identity_verification").',
  },
  // ── front office ──────────────────────────────────────────────────────────
  {
    id: 'bookings',
    routePaths: ['/bookings'],
    routeFiles: ['bookings.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/bookings/components/Bookings/BookingsPage.tsx',
    smokeTests: ['features/bookings/components/Bookings/BookingsPage.test.tsx'],
    axeTests: ['features/bookings/components/Bookings/BookingsPage.test.tsx'],
    workflowTests: ['features/bookings/components/Bookings/BookingsPage.test.tsx'],
  },
  {
    id: 'booking-detail',
    routePaths: ['/bookings/$bookingId'],
    routeFiles: ['bookings.$bookingId.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/bookings/pages/BookingDetailPage.tsx',
    smokeTests: ['features/bookings/pages/BookingDetailPage.test.tsx'],
    axeTests: ['features/bookings/pages/BookingDetailPage.test.tsx'],
    workflowTests: ['features/bookings/pages/BookingDetailPage.test.tsx'],
  },
  {
    id: 'timeline',
    routePaths: ['/timeline'],
    routeFiles: ['timeline.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/rooms/components/RoomReservationTimeline.tsx',
    smokeTests: ['features/rooms/components/RoomReservationTimeline.test.tsx'],
    axeTests: ['features/rooms/components/RoomReservationTimeline.test.tsx'],
  },
  {
    id: 'room-management',
    routePaths: ['/room-management'],
    routeFiles: ['room-management.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/rooms/components/RoomManagement/RoomManagementPage.tsx',
    smokeTests: ['features/rooms/components/RoomManagement/RoomManagementPage.test.tsx'],
    axeTests: ['features/rooms/components/RoomManagement/RoomManagementPage.test.tsx'],
    workflowTests: ['features/rooms/components/RoomManagement/RoomManagementPage.test.tsx'],
  },
  {
    id: 'housekeeping',
    routePaths: ['/housekeeping'],
    routeFiles: ['housekeeping.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/housekeeping/components/HousekeepingPage.tsx',
    smokeTests: ['features/housekeeping/components/HousekeepingPage.test.tsx'],
    axeTests: ['features/housekeeping/components/HousekeepingPage.test.tsx'],
    workflowTests: ['features/housekeeping/components/HousekeepingPage.test.tsx'],
  },
  // ── guests ────────────────────────────────────────────────────────────────
  {
    id: 'guest-relations',
    routePaths: ['/guest-relations'],
    routeFiles: ['guest-relations/index.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/guestRelations/pages/GuestRelationsOverviewPage.tsx',
    smokeTests: ['features/guestRelations/pages/GuestRelationsOverviewPage.test.tsx'],
    axeTests: ['features/guestRelations/pages/GuestRelationsOverviewPage.test.tsx'],
  },
  {
    id: 'guest-directory',
    routePaths: ['/guest-relations/guests'],
    routeFiles: ['guest-relations/guests/index.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/guestRelations/pages/GuestRelationsPage.tsx',
    smokeTests: ['features/guestRelations/pages/GuestRelationsPage.test.tsx'],
    axeTests: ['features/guestRelations/pages/GuestRelationsPage.test.tsx'],
    workflowTests: ['features/guestRelations/pages/GuestRelationsPage.test.tsx'],
  },
  {
    id: 'guest-relations-detail',
    routePaths: ['/guest-relations/guests/$guestId'],
    routeFiles: ['guest-relations/guests/$guestId.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/guestRelations/pages/GuestProfilePage.tsx',
    smokeTests: ['features/guestRelations/pages/GuestProfilePage.test.tsx'],
    axeTests: ['features/guestRelations/pages/GuestProfilePage.test.tsx'],
    workflowTests: ['features/guestRelations/pages/GuestProfilePage.test.tsx'],
  },
  {
    id: 'guest-relations-follow-ups',
    routePaths: ['/guest-relations/follow-ups'],
    routeFiles: ['guest-relations/follow-ups.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/guestRelations/pages/GuestRelationsFollowUpsPage.tsx',
    smokeTests: ['features/guestRelations/pages/GuestRelationsFollowUpsPage.test.tsx'],
    axeTests: ['features/guestRelations/pages/GuestRelationsFollowUpsPage.test.tsx'],
  },
  {
    id: 'support',
    routePaths: ['/support'],
    routeFiles: ['support.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/support/components/SupportManagementPage.tsx',
    smokeTests: ['features/support/components/SupportManagementPage.test.tsx'],
    axeTests: ['features/support/components/SupportManagementPage.test.tsx'],
    workflowTests: ['features/support/components/SupportManagementPage.test.tsx'],
  },
  {
    id: 'loyalty',
    routePaths: ['/loyalty'],
    routeFiles: ['loyalty.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/loyalty/components/LoyaltyPortal.tsx',
    smokeTests: ['features/loyalty/components/LoyaltyPortal.test.tsx'],
    axeTests: ['features/loyalty/components/LoyaltyPortal.test.tsx'],
    workflowTests: ['features/loyalty/components/LoyaltyPortal.test.tsx'],
  },
  {
    id: 'my-rewards',
    routePaths: ['/my-rewards'],
    routeFiles: ['my-rewards.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/loyalty/components/LoyaltyDashboard.tsx',
    smokeTests: [
      'features/loyalty/components/LoyaltyDashboard.admin.test.tsx',
      'features/loyalty/components/LoyaltyDashboard.member.test.tsx',
    ],
    axeTests: [
      'features/loyalty/components/LoyaltyDashboard.admin.test.tsx',
      'features/loyalty/components/LoyaltyDashboard.member.test.tsx',
    ],
    workflowTests: [
      'features/loyalty/components/LoyaltyDashboard.admin.test.tsx',
      'features/loyalty/components/LoyaltyDashboard.member.test.tsx',
    ],
  },
  // ── revenue & marketing ───────────────────────────────────────────────────
  {
    id: 'revenue',
    routePaths: ['/revenue'],
    routeFiles: ['revenue.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/revenue/pages/RevenueOverviewPage.tsx',
    smokeTests: ['features/revenue/pages/RevenueOverviewPage.test.tsx'],
    axeTests: ['features/revenue/pages/RevenueOverviewPage.test.tsx'],
  },
  {
    id: 'rates',
    routePaths: ['/rates'],
    routeFiles: ['rates.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/rates/pages/RatesPage.tsx',
    smokeTests: ['features/rates/pages/RatesPage.test.tsx'],
    axeTests: ['features/rates/pages/RatesPage.test.tsx'],
  },
  {
    id: 'channels',
    routePaths: ['/channels', '/channels/$channelId'],
    routeFiles: ['channels.tsx', 'channels.$channelId.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/channels/pages/ChannelsPage.tsx',
    smokeTests: [
      'features/channels/pages/ChannelsPage.test.tsx',
      'features/channels/pages/ChannelDetailPage.test.tsx',
    ],
    axeTests: ['features/channels/pages/ChannelsPage.test.tsx'],
  },
  {
    id: 'campaigns',
    routePaths: ['/campaigns'],
    routeFiles: ['campaigns.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/promotions/pages/PromotionManagementPage.tsx',
    smokeTests: ['features/promotions/pages/PromotionManagementPage.test.tsx'],
    axeTests: ['features/promotions/pages/PromotionManagementPage.test.tsx'],
    workflowTests: ['features/promotions/pages/PromotionManagementPage.test.tsx'],
  },
  {
    id: 'segments',
    routePaths: ['/segments'],
    routeFiles: ['segments.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/segments/pages/SegmentsPage.tsx',
    smokeTests: ['features/segments/pages/SegmentsPage.test.tsx'],
    axeTests: ['features/segments/pages/SegmentsPage.test.tsx'],
    workflowTests: ['features/segments/pages/SegmentsPage.test.tsx'],
  },
  {
    id: 'communications',
    routePaths: ['/communications'],
    routeFiles: ['communications.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/communications/pages/CommunicationsPage.tsx',
    smokeTests: ['features/communications/pages/CommunicationsPage.test.tsx'],
    axeTests: ['features/communications/pages/CommunicationsPage.test.tsx'],
    workflowTests: ['features/communications/pages/CommunicationsPage.test.tsx'],
  },
  {
    id: 'online-inventory',
    routePaths: ['/online-inventory'],
    routeFiles: ['online-inventory.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/onlineInventory/pages/OnlineInventoryPage.tsx',
    smokeTests: ['features/onlineInventory/pages/OnlineInventoryPage.test.tsx'],
    axeTests: ['features/onlineInventory/pages/OnlineInventoryPage.test.tsx'],
    workflowTests: ['features/onlineInventory/pages/OnlineInventoryPage.test.tsx'],
  },
  // ── finance ───────────────────────────────────────────────────────────────
  {
    id: 'company-ledger',
    routePaths: ['/company-ledger'],
    routeFiles: ['company-ledger.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/components/CustomerLedger/CustomerLedgerPage.tsx',
    smokeTests: ['features/admin/components/CustomerLedger/CustomerLedgerPage.test.tsx'],
    axeTests: ['features/admin/components/CustomerLedger/CustomerLedgerPage.test.tsx'],
    workflowTests: ['features/admin/components/CustomerLedger/CustomerLedgerPage.test.tsx'],
  },
  {
    id: 'payment-approvals',
    routePaths: ['/payment-approvals'],
    routeFiles: ['payment-approvals.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/components/PaymentApprovalsPage.tsx',
    smokeTests: ['features/admin/components/PaymentApprovalsPage.test.tsx'],
    axeTests: ['features/admin/components/PaymentApprovalsPage.test.tsx'],
    workflowTests: ['features/admin/components/PaymentApprovalsPage.test.tsx'],
  },
  {
    id: 'night-audit',
    routePaths: ['/night-audit'],
    routeFiles: ['night-audit.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/components/NightAuditPage.tsx',
    smokeTests: ['features/admin/components/NightAuditPage.test.tsx'],
    axeTests: ['features/admin/components/NightAuditPage.axe.test.tsx'],
    workflowTests: ['features/admin/components/NightAuditPage.test.tsx'],
  },
  {
    id: 'complimentary',
    routePaths: ['/complimentary'],
    routeFiles: ['complimentary.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/components/ComplimentaryManagementPage.tsx',
    smokeTests: ['features/admin/components/ComplimentaryManagementPage.test.tsx'],
    axeTests: ['features/admin/components/ComplimentaryManagementPage.test.tsx'],
  },
  // ── insights ──────────────────────────────────────────────────────────────
  {
    id: 'insights',
    routePaths: ['/insights'],
    routeFiles: ['insights.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/insights/pages/ReportLibraryPage.tsx',
    smokeTests: ['features/insights/pages/ReportLibraryPage.test.tsx'],
    axeTests: ['features/insights/pages/ReportLibraryPage.test.tsx'],
    workflowTests: ['features/insights/pages/ReportLibraryPage.test.tsx'],
  },
  // ── administration ────────────────────────────────────────────────────────
  {
    id: 'rbac',
    routePaths: ['/rbac'],
    routeFiles: ['rbac.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/components/rbac/RBACManagementPage.tsx',
    smokeTests: ['features/admin/components/rbac/RBACManagementPage.test.tsx'],
    axeTests: ['features/admin/components/rbac/RBACManagementPage.test.tsx'],
    workflowTests: ['features/admin/components/rbac/RBACManagementPage.test.tsx'],
  },
  {
    id: 'ekyc-admin',
    routePaths: ['/ekyc-admin'],
    routeFiles: ['ekyc-admin.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/ekyc/components/EkycManagementPage.tsx',
    smokeTests: ['features/ekyc/components/EkycManagementPage.test.tsx'],
    axeTests: ['features/ekyc/components/EkycManagementPage.test.tsx'],
    workflowTests: ['features/ekyc/components/EkycManagementPage.test.tsx'],
  },
  {
    id: 'ekyc',
    routePaths: ['/ekyc'],
    routeFiles: ['ekyc.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/ekyc/components/EkycRegistrationPage.tsx',
    smokeTests: ['features/ekyc/components/EkycRegistrationPage.test.tsx'],
    axeTests: ['features/ekyc/components/EkycRegistrationPage.test.tsx'],
    workflowTests: ['features/ekyc/components/EkycRegistrationPage.test.tsx'],
  },
  {
    id: 'settings',
    routePaths: ['/settings'],
    routeFiles: ['settings.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/user/components/SettingsPage.tsx',
    smokeTests: ['features/user/components/SettingsPage.test.tsx'],
    axeTests: ['features/user/components/SettingsPage.test.tsx'],
    workflowTests: ['features/user/components/SettingsPage.test.tsx'],
  },
  {
    id: 'room-config',
    routePaths: ['/room-config'],
    routeFiles: ['room-config.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/rooms/components/RoomConfigurationPage.tsx',
    smokeTests: ['features/rooms/components/RoomConfigurationPage.test.tsx'],
    axeTests: ['features/rooms/components/RoomConfigurationPage.test.tsx'],
  },
  {
    id: 'audit-log',
    routePaths: ['/audit-log'],
    routeFiles: ['audit-log.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/components/AuditLogPage.tsx',
    smokeTests: ['features/admin/components/AuditLogPage.test.tsx'],
    axeTests: ['features/admin/components/AuditLogPage.test.tsx'],
    workflowTests: ['features/admin/components/AuditLogPage.test.tsx'],
  },
  {
    id: 'data-transfer',
    routePaths: ['/data-transfer'],
    routeFiles: ['data-transfer.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/components/DataTransferPage.tsx',
    smokeTests: ['features/admin/components/DataTransferPage.test.tsx'],
    axeTests: ['features/admin/components/DataTransferPage.test.tsx'],
    workflowTests: [
      'features/admin/components/DataTransferPage.test.tsx',
      'features/admin/components/data-transfer/ImportWizard.test.tsx',
      'features/admin/components/data-transfer/ExportPanel.test.tsx',
    ],
  },
  {
    id: 'system-health',
    routePaths: ['/system-health'],
    routeFiles: ['system-health.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/system/SystemHealthPage.tsx',
    smokeTests: ['features/admin/system/SystemHealthPage.test.tsx'],
    axeTests: ['features/admin/system/SystemHealthPage.test.tsx'],
  },
  {
    id: 'jobs',
    routePaths: ['/jobs'],
    routeFiles: ['jobs.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/admin/system/JobsPage.tsx',
    smokeTests: ['features/admin/system/JobsPage.test.tsx'],
    axeTests: ['features/admin/system/JobsPage.test.tsx'],
  },
  // ── utility ───────────────────────────────────────────────────────────────
  {
    id: 'notifications',
    routePaths: ['/notifications'],
    routeFiles: ['notifications.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/notifications/pages/NotificationsPage.tsx',
    smokeTests: ['features/notifications/pages/NotificationsPage.test.tsx'],
    axeTests: ['features/notifications/pages/NotificationsPage.test.tsx'],
  },
  {
    id: 'help',
    routePaths: ['/help'],
    routeFiles: ['help.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/help/pages/HelpCenterPage.tsx',
    smokeTests: ['features/help/pages/HelpCenterPage.test.tsx'],
    axeTests: ['features/help/pages/HelpCenterPage.test.tsx'],
  },
  {
    id: 'help-article',
    routePaths: ['/help/$slug'],
    routeFiles: ['help.$slug.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/help/pages/HelpArticlePage.tsx',
    smokeTests: ['features/help/pages/HelpArticlePage.test.tsx'],
    axeTests: ['features/help/pages/HelpArticlePage.test.tsx'],
  },
  {
    id: 'profile',
    routePaths: ['/profile'],
    routeFiles: ['profile.tsx'],
    kind: 'page',
    visibility: 'auth',
    component: 'features/user/components/UserProfilePage.tsx',
    smokeTests: ['features/user/components/UserProfilePage.test.tsx'],
    axeTests: ['features/user/components/UserProfilePage.test.tsx'],
    workflowTests: ['features/user/components/UserProfilePage.test.tsx'],
  },
  // ── standalone public surfaces (file routes, not in the registry) ─────────
  {
    id: 'unsubscribe',
    routePaths: ['/unsubscribe/$token'],
    routeFiles: ['unsubscribe.$token.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/communications/pages/UnsubscribePage.tsx',
    smokeTests: ['features/communications/pages/UnsubscribePage.test.tsx'],
    axeTests: ['features/communications/pages/UnsubscribePage.test.tsx'],
  },
  {
    id: 'payment-recovery',
    routePaths: ['/booking/recover-payment/$token'],
    routeFiles: ['booking.recover-payment.$token.tsx'],
    kind: 'page',
    visibility: 'public',
    component: 'features/paymentRecovery/PaymentRecoveryPage.tsx',
    smokeTests: ['features/paymentRecovery/PaymentRecoveryPage.test.tsx'],
    axeTests: ['features/paymentRecovery/PaymentRecoveryPage.test.tsx'],
  },
  // ── status pages ──────────────────────────────────────────────────────────
  {
    id: 'status-403',
    routePaths: ['/403'],
    routeFiles: ['403.tsx'],
    kind: 'status',
    visibility: 'mixed',
    component: 'components/common/StatusPage.tsx',
    smokeTests: ['components/common/StatusPage.test.tsx'],
    axeTests: ['components/common/StatusPage.test.tsx'],
  },
  {
    id: 'status-423',
    routePaths: ['/423'],
    routeFiles: ['423.tsx'],
    kind: 'status',
    visibility: 'mixed',
    component: 'components/common/StatusPage.tsx',
    smokeTests: ['components/common/StatusPage.test.tsx'],
    axeTests: ['components/common/StatusPage.test.tsx'],
  },
  {
    id: 'status-404',
    routePaths: ['/$'],
    routeFiles: ['$.tsx'],
    kind: 'status',
    visibility: 'mixed',
    component: 'components/common/StatusPage.tsx',
    smokeTests: ['components/common/StatusPage.test.tsx'],
    axeTests: ['components/common/StatusPage.test.tsx'],
  },
];
