version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /hotel-app-be
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "sqlx"
      - dependency-name: "sqlx-*"
  - package-ecosystem: bun
    directory: /hotel-web-fe
    schedule:
      interval: weekly
