//! gRPC transport adapters (Phase 2 of the REST→gRPC migration).
//!
//! Tonic services live here and are merged into the existing Axum router on
//! the same port — deployment topology is unchanged. Every adapter is thin:
//! it translates protobuf messages into the existing domain models and calls
//! the *same* service-layer functions the REST handlers call, so permissions,
//! validation, audit logging, and broadcast side effects are identical.
//!
//! Authentication mirrors `routes::enforce_active_session` (bearer JWT + live
//! `sid` session check) but runs per-RPC via [`auth::authenticate`] because
//! session validation is async and tonic's `Interceptor` trait is sync-only.
//! REST endpoints, middleware, and websockets are untouched.

mod auth;
mod convert;
mod error;
mod guests;
mod housekeeping;
mod idempotency;
mod rooms;
mod server;

// Re-exported so integration tests (tests/grpc_equivalence.rs) can drive the
// service traits in-process. The bin target's private `mod grpc` never uses
// them, hence the allow.
#[allow(unused_imports)]
pub use guests::GuestGrpc;
#[allow(unused_imports)]
pub use housekeeping::{HousekeepingGrpc, MaintenanceGrpc};
#[allow(unused_imports)]
pub use rooms::{RoomGrpc, RoomTypeGrpc};
pub use server::grpc_router;

/// Protobuf bindings generated by `tonic-prost-build` (build.rs) from the
/// buf-managed contract in `../proto`. Module nesting must mirror the proto
/// package names: prost resolves cross-package references through `super::`
/// chains that assume this exact shape.
#[allow(clippy::all)]
#[allow(missing_docs)]
pub mod pb {
    pub mod google {
        pub mod api {
            include!(concat!(env!("OUT_DIR"), "/google.api.rs"));
        }
        pub mod r#type {
            include!(concat!(env!("OUT_DIR"), "/google.r#type.rs"));
        }
    }

    pub mod hotel {
        pub mod common {
            pub mod v1 {
                include!(concat!(env!("OUT_DIR"), "/hotel.common.v1.rs"));
            }
        }
        pub mod rooms {
            pub mod v1 {
                include!(concat!(env!("OUT_DIR"), "/hotel.rooms.v1.rs"));
            }
        }
        pub mod housekeeping {
            pub mod v1 {
                include!(concat!(env!("OUT_DIR"), "/hotel.housekeeping.v1.rs"));
            }
        }
        pub mod guests {
            pub mod v1 {
                include!(concat!(env!("OUT_DIR"), "/hotel.guests.v1.rs"));
            }
        }
    }
}
