/**
 * Static gate: no hardcoded user-visible strings outside the translation
 * bundles.
 *
 * This is the durable half of the i18n coverage plan's enforcement section —
 * `keyUsage.test.ts` proves every *key* exists; this test proves no *literal*
 * reaches a user without going through `t()`/`tOr()`. It walks every source
 * file under `src/` (minus tests, generated code, and the exempt corpora) and
 * fails on:
 *
 *   - literal JSX text nodes          `>Save changes<`
 *   - literal JSX attributes          `placeholder="Search"`  `label="Name"`
 *     (also `name='…'`, `name={"…"}`, `name={'…'}`) for the user-visible
 *     props: placeholder, title, aria-label, ariaLabel, alt, label,
 *     helperText, headerName
 *   - literal object properties       `{ label: 'Name' }`, `'aria-label': '…'`
 *   - literals in expression position `{'Save'}`  `cond && 'Save'`
 *     `a ?? 'Save'`  `cond ? 'A' : 'B'`
 *
 * The detection logic is a port of `scripts/i18n-scan.mjs` — the two share
 * ALLOWED_LITERALS / ALLOWED_PATTERNS and the same comment-blanker, and this
 * test's ALLOWLIST is a superset of the scanner's FILE_ALLOWLIST (the test's
 * wider jsx-text lookbehind flags strings the scanner cannot see — e.g. text
 * under a tag closed at line start — so its allowlist additionally carries
 * `⌘K`; the two tables can never be byte-identical). The scan script cannot
 * be imported (it runs main() at module load), which is why the tables are
 * embedded here — keep them in sync when one changes.
 *
 * Deliberate strengthening over the scanner: the jsx-text lookbehind also
 * accepts whitespace before `>`, so text inside a tag closed at the start of a
 * line (`<Button\n  …\n>\n  Text\n</Button>`) is caught — the scanner misses
 * that shape (the "New task" leak this task fixed).
 *
 * A finding is a *candidate*, not a verdict: currency codes, brand names,
 * glyphs, codes, route/URL/date-format shapes, and single-token enum values in
 * expression positions are globally exempt; genuinely exempt leftovers carry a
 * file-scoped ALLOWLIST entry with its reason. Anything else must move through
 * `t()` (or `tOr()` while a screen is mid-migration).
 */

import { describe, expect, it } from 'vitest';

/**
 * Every source file under `src/` (this test lives in `src/i18n`, so `../` is
 * `src/`), raw text, minus:
 *   - `*.test.*` / `*.spec.*` / `*.d.ts` — test code and declarations
 *   - `i18n/`    — the engine + resource registration itself
 *   - `test/`    — shared test support
 *   - `routeTree.gen.ts` — generated by TanStack Router
 *   - `ds-bundle/` — design preview package, not shipped app UI
 *   - `features/legal/content/` — PDPA notice corpus, en/ms by design
 *   - `features/help/content/`  — help article corpus (own parity test)
 */
const SOURCES = import.meta.glob(
  [
    '../**/*.{ts,tsx}',
    '!../**/*.test.{ts,tsx}',
    '!../**/*.spec.{ts,tsx}',
    '!../**/*.d.ts',
    '!../i18n/**',
    '!../test/**',
    '!../routeTree.gen.ts',
    '!../ds-bundle/**',
    '!../features/legal/content/**',
    '!../features/help/content/**',
  ],
  { eager: true, query: '?raw', import: 'default' }
) as Record<string, string>;

// ---------------------------------------------------------------------------
// Exempt literals — values that are never translated: currency codes, brand
// names/app title, N/A, ellipsis/keyboard glyphs, developer error codes.
// Mirror of i18n-scan.mjs ALLOWED_LITERALS.
// ---------------------------------------------------------------------------
const ALLOWED_LITERALS = new Set([
  'RM',
  'MYR',
  'N/A',
  '…',
  '×',
  'ERROR',
  'Hotel ERP System', // brand fallback title (GuestRootLayout FALLBACK_APP_TITLE)
  'Hotel ERP',
  'esc',              // keyboard glyph on the command-palette hint chip
  'px',               // CSS unit shown as a numeric input adornment
  'CSV',              // file-format name on export buttons
  'VIP',              // universal guest-tier acronym badge (not localized)
  'Cash',             // default payment/refund-method *value* persisted on
                      // booking/payment records; methods come from hotel
                      // settings, not the bundle
  'DLX',              // room-type code example shown as an input placeholder
  'VpnKey',           // MUI icon identifier fallback (useRBACData) — never rendered
]);

// Patterns applied to the trimmed literal — a match means "do not report".
// Mirror of i18n-scan.mjs ALLOWED_PATTERNS.
const ALLOWED_PATTERNS = [
  /[{}]/,                                          // '{'-expression fragment, not text
  /^\p{Lu}*[\d&+/._-][\p{Lu}\d&+/._ -]*$/u,        // codes w/ digit or symbol: 2FA, V1
  /^[dMyLhHmsS]{1,5}([/\-.,:\s][dMyLhHmsS]{1,5})+$/, // date-format tokens: dd/MM/yyyy, HH:mm
  /^[a-zA-Z][\w-]*([.:][\w-]+)+$/,                 // translation-key shaped: ns:key, a.b.c
  /^\/[\w\-./]*(\?[\w\-=&%]*)?$/,                  // route/path shaped: /bookings,
                                                   //   /salim-inn/index.html,
                                                   //   /guest-portal?section=stays
  /^https?:\/\/\S*$/,                              // absolute URL: 'http://localhost' SSR base
  /^(?:wss?|https?|mailto|tel|data|blob):$/,       // bare URL scheme: 'ws:', 'wss:'
  /^[a-z]{2,3}-([A-Z]{2}|[A-Z][a-z]{3,8}|\d{3})$/, // BCP-47 tag: 'zh-CN', 'ms-MY',
                                                   //   'zh-Hans' (Google Sign-In). The
                                                   //   subtag must be an UPPERCASE region,
                                                   //   Titlecase script, or numeric code —
                                                   //   deliberately not lowercase so
                                                   //   'in-house'/'pre-order' still flag
  /^extends\s+\w/,                                 // TS `extends Omit<…>` clause misparsed
                                                   //   as JSX text by the text-node regex
  /^#/,                                            // CSS colour: '#fff'
  /^var\(/,                                        // CSS variable: 'var(--hotel-…)'
  /^[a-z][a-zA-Z-]*\([^)]*\)$/,                    // CSS function: 'rotate(180deg)'
  /^(?:color-mix|light-dark|env|image-set)\(/,     // nested-paren CSS functions
  /^-?[\d.]+(px|em|rem|deg|vh|vw|s|ms|fr|ch|ex|%)(\s+-?[\d.]+(px|em|rem|deg|vh|vw|s|ms|fr|ch|ex|%))*$/,
                                                   // CSS measure list: '-0.015em', '1fr 1fr',
                                                   //   '1px 7px'
  /^-?[\d.]+(px|em|rem)\s+(solid|dashed|dotted|double|groove|ridge|inset|outset)\b/,
                                                   // CSS border shorthand: '1px solid',
                                                   //   '1px solid var(--hotel-border-subtle)'
];

// ---------------------------------------------------------------------------
// ALLOWLIST — file-scoped exemptions: literals legitimately untranslated only
// in one file, where a global entry would mask real misses elsewhere. `path`
// is tested against the path relative to `src/` (e.g. `features/rooms/config.ts`).
// Each entry carries its reason; every literal must currently be flagged in
// its file — a stale entry fails the suite so the list cannot rot.
// Mirror of i18n-scan.mjs FILE_ALLOWLIST.
// ---------------------------------------------------------------------------
const ALLOWLIST: { path: RegExp; literals: Set<string> }[] = [
  {
    // ROOM/BOOKING_STATUS_CONFIG `label` fields are the documented English
    // fallback and reference; components render via the getLocalizedStatus*
    // helpers (rooms:statusLabels/statusShort/…).
    path: /features\/rooms\/config\.ts$/,
    literals: new Set([
      'Vacant/Clean', 'Occupied', 'Reserved', 'Reserved / Dirty', 'Dirty',
      'Maintenance', 'Pending', 'Checked Out', 'Voided',
    ]),
  },
  {
    // Preset `label` is the English reference kept next to the size numbers;
    // the settings UI renders t('admin:settings.fontPresets.<key>.label').
    path: /features\/insights\/utils\/reportTypography\.ts$/,
    literals: new Set(['Very Small', 'Small', 'Medium', 'Large', 'Very Large']),
  },
  {
    // Font-family option names are proper nouns rendered as-is in every locale.
    path: /utils\/hotelSettings\.ts$/,
    literals: new Set([
      'Arial', 'Helvetica', 'Georgia', 'Times New Roman', 'Tahoma',
      'Courier New',
    ]),
  },
  {
    // English search alias kept so "new booking" still matches when the
    // interface runs in ms/zh (the localized label is checked alongside it).
    path: /components\/layout\/CommandPalette\.tsx$/,
    literals: new Set(['new booking']),
  },
  {
    // Keyboard-shortcut hint chip (⌘ + K); glyphs are not localized.
    path: /components\/layout\/AppTopbar\.tsx$/,
    literals: new Set(['⌘K']),
  },
  {
    // Default payment note persisted verbatim on the payment record.
    path: /features\/bookings\/components\/Bookings\/dialogs\/PaymentDialog\.tsx$/,
    literals: new Set(['Required before checkout']),
  },
  {
    // Default void reason persisted verbatim on the booking record.
    path: /features\/bookings\/components\/Bookings\/dialogs\/VoidDialog\.tsx$/,
    literals: new Set(['Voided by admin']),
  },
  {
    // Default deposit-waive reason persisted verbatim in payment_note.
    path: /features\/bookings\/components\/EnhancedCheckInModal\.tsx$/,
    literals: new Set(['No reason provided']),
  },
  {
    // Default for absent notes inside the room-status note stored on the room.
    path: /features\/invoices\/hooks\/useCheckoutFlow\.ts$/,
    literals: new Set(['None']),
  },
  {
    // Tag appended to booking remarks persisted verbatim on the booking.
    path: /features\/rooms\/components\/UnifiedBooking\/UnifiedBookingModal\.tsx$/,
    literals: new Set(['[Hourly Stay]']),
  },
  {
    // Default bed_type value stored on the room-type record.
    path: /features\/rooms\/components\/RoomConfigurationPage\.tsx$/,
    literals: new Set(['Queen']),
  },
];

// jsx-text heuristic: a "text node" that starts with a closing bracket, comma,
// colon or `=`, ends with an opening bracket, looks like a TS signature
// (`(cmd: string, args?: Record`), or carries a JS operator is really a code
// fragment caught between JSX siblings (`) : cond ? (`, `= TanStackColumnDef`,
// `(KEY) ?? store.get`). The final `\s\?\s*$` arm covers comparison-ternary
// spans the widened lookbehind admits (`x > y ? <A/>` → body `y ?`) — it
// anchors on whitespace BEFORE the `?` precisely so prose like
// `Are you sure?` still flags; a bare `\?` arm would exempt every question
// mark in the tree.
const JSX_CODE_FRAGMENT_RE =
  /^[)\],;:}=\[]|^[(\[][^<]*:|[([{&|]$|==|!=|&&|\|\||\?\?|\?\.|=>|\.\w+\s*\(|\s\?\s*$/;

// Attribute / property names whose literal values are user-visible.
const TEXT_PROP_NAMES = [
  'placeholder',
  'title',
  'aria-label',
  'ariaLabel',
  'alt',
  'label',
  'helperText',
  'headerName',
];

const NAME_RE = TEXT_PROP_NAMES.map((n) => n.replace(/-/g, '\\-')).join('|');

// Literal JSX attributes:  name="…" | name='…' | name={"…"} | name={'…'}
const JSX_ATTR_RE = new RegExp(
  `(?<=[\\s{(])(${NAME_RE})\\s*=\\s*(?:"([^"\\\\]*)"|'([^'\\\\]*)'|\\{\\s*"([^"\\\\]*)"\\s*\\}|\\{\\s*'([^'\\\\]*)'\\s*\\})`,
  'g'
);

// Literal object properties:  name: '…' | name: "…" (unquoted keys) and
// 'name': '…' (quoted keys, e.g. inputProps={{ 'aria-label': '…' }}).
const OBJ_PROP_RE = new RegExp(
  `(?<=[{,\\s])(${NAME_RE})\\s*:\\s*(?:"([^"\\\\]*)"|'([^'\\\\]*)')`,
  'g'
);
const QUOTED_PROP_RE = new RegExp(
  `['"](${NAME_RE})['"]\\s*:\\s*(?:'([^'\\\\]*)'|"([^"\\\\]*)")`,
  'g'
);

// Literal JSX text nodes: `>` …letters… `<`. The lookbehind restricts `>` to
// positions that can close a tag (tag name, quote, /, fragment <>, a preceding
// `{…}`/`>`, or whitespace — a tag closed at the start of a line after
// multiline props), so `a > b`, `(x) > (y)` and `=>` arrows do not produce
// text nodes; `(?!=)` additionally rejects `>=`. `;` is excluded from the text
// body — real JSX prose almost never carries one, and excluding it stops
// generic-call spans like `createContext<T>(…); … React.FC<` matching as text.
const JSX_TEXT_RE = /(?<=[A-Za-z0-9"'`\/><}\s])>(?!=)([^<>{};]*\p{L}[^<>{};]*)</gu;

// Any string literal — filtered afterwards by surrounding context so that
// {'…'}, {cond && '…'} and {cond ? '…' : '…'} surface while call arguments
// (t('key'), new Error(…)) and object keys do not.
const ANY_STRING_RE = /'([^'\\\n]*)'|"([^"\\\n]*)"/g;

// Lines whose findings are developer-only, never user-visible.
const DEV_ONLY_LINE_RE = /\bconsole\.|new Error\s*\(|throw\s+new\b/;

/**
 * Blank out // and /* *‍/ comment bodies (preserving offsets and newlines) so
 * doc examples like `title="x"` inside comments are not reported. String and
 * template literals are tracked so `//` inside 'https://…' is not a comment.
 */
function blankComments(src: string): string {
  const out = src.split('');
  const n = src.length;
  let i = 0;
  let mode: 'code' | 'line' | 'block' | 'sq' | 'dq' | 'tpl' = 'code';
  while (i < n) {
    const c = src[i];
    const next = src[i + 1];
    if (mode === 'code') {
      if (c === '/' && next === '/') mode = 'line';
      else if (c === '/' && next === '*') mode = 'block';
      else if (c === "'") mode = 'sq';
      else if (c === '"') mode = 'dq';
      else if (c === '`') mode = 'tpl';
    } else if (mode === 'line') {
      if (c === '\n') mode = 'code';
      else out[i] = ' ';
    } else if (mode === 'block') {
      if (c === '*' && next === '/') {
        out[i] = ' ';
        out[i + 1] = ' ';
        i += 1;
        mode = 'code';
      } else if (c !== '\n') {
        out[i] = ' ';
      }
    } else {
      // inside a string/template literal
      if (c === '\\') i += 1; // skip the escaped char
      else if (
        (mode === 'sq' && c === "'") ||
        (mode === 'dq' && c === '"') ||
        (mode === 'tpl' && c === '`')
      ) {
        mode = 'code';
      } else if (mode !== 'tpl' && c === '\n') {
        mode = 'code'; // unterminated string — recover at EOL
      }
    }
    i += 1;
  }
  return out.join('');
}

function lineNumberAt(lineStarts: number[], index: number): number {
  let lo = 0;
  let hi = lineStarts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (lineStarts[mid] <= index) lo = mid;
    else hi = mid - 1;
  }
  return lo + 1;
}

function isAllowedLiteral(text: string, kind: string): boolean {
  if (text.length <= 1) return true; // empty, single chars, keyboard glyphs
  if (ALLOWED_LITERALS.has(text)) return true;
  if (!/\p{L}/u.test(text)) return true; // digits/punctuation/glyphs: … × ⌘ 100%
  for (const pattern of ALLOWED_PATTERNS) {
    if (pattern.test(text)) return true;
  }
  if (kind === 'jsx-text' && JSX_CODE_FRAGMENT_RE.test(text)) return true;
  // {cond && 'primary'}, {x ? 'en' : 'ms'}, {ch === 'ONL'} — in expression
  // positions a lowercase/camelCase/short-CAPS single token is an enum,
  // style, locale, or channel code, not prose. Multi-word lowercase strings
  // in these positions ARE prose ('past checkout date', 'vs same period last
  // month') and must stay flagged, so spaces are deliberately not allowed
  // here — a CSS value like '1px solid' is acceptable residual noise.
  if (
    kind === 'jsx-expr' &&
    (/^[a-z0-9]+([._/-][a-z0-9]+)*$/.test(text) ||
      /^[a-z]+([A-Z][a-zA-Z0-9]*)+$/.test(text) ||
      /^\p{Lu}{2,6}$/u.test(text))
  ) {
    return true;
  }
  return false;
}

interface Finding {
  file: string;
  line: number;
  kind: string;
  text: string;
}

/**
 * Scan one source file. `relPath` is the `src/`-relative path used for
 * ALLOWLIST matching; `used` records which allowlisted literals fired so the
 * suite can reject stale entries.
 */
function scanFile(
  relPath: string,
  source: string,
  used: Set<string>
): Finding[] {
  const code = blankComments(source);

  const lineStarts = [0];
  for (let i = 0; i < source.length; i += 1) {
    if (source[i] === '\n') lineStarts.push(i + 1);
  }
  const lineAt = (index: number) => lineNumberAt(lineStarts, index);
  const lineTextAt = (index: number) => {
    const start = lineStarts[lineAt(index) - 1];
    const end = source.indexOf('\n', start);
    return source.slice(start, end === -1 ? undefined : end);
  };

  const findings: Finding[] = [];
  const reported = new Set<number>(); // index dedupe across kinds

  const consider = (index: number, kind: string, raw: string) => {
    const text = raw.trim().replace(/\s+/g, ' ');
    if (isAllowedLiteral(text, kind)) return;
    if (
      ALLOWLIST.some((entry) => {
        if (entry.path.test(relPath) && entry.literals.has(text)) {
          used.add(`${entry.path.source}::${text}`);
          return true;
        }
        return false;
      })
    )
      return;
    if (DEV_ONLY_LINE_RE.test(lineTextAt(index))) return;
    if (reported.has(index)) return;
    reported.add(index);
    findings.push({ file: relPath, line: lineAt(index), kind, text });
  };

  for (const m of code.matchAll(JSX_TEXT_RE)) {
    // report the line the text starts on (m.index is the closing `>` of the tag)
    const leadWs = m[1].length - m[1].trimStart().length;
    consider(m.index + 1 + leadWs, 'jsx-text', m[1]);
  }

  for (const m of code.matchAll(JSX_ATTR_RE)) {
    consider(m.index, `attr:${m[1]}`, m[2] ?? m[3] ?? m[4] ?? m[5] ?? '');
  }

  for (const m of code.matchAll(OBJ_PROP_RE)) {
    consider(m.index, `prop:${m[1]}`, m[2] ?? m[3] ?? '');
  }
  for (const m of code.matchAll(QUOTED_PROP_RE)) {
    consider(m.index, `prop:${m[1]}`, m[2] ?? m[3] ?? '');
  }

  // String literals in expression positions: {'x'}, cond && 'x', a ?? 'x',
  // cond ? 'x' : 'y'. Call arguments (preceded by `(` or `,`) and object keys
  // are skipped, so t('key')/tOr('k','fb') never surface. A trailing `:` is an
  // object key only when no `?` opened a ternary earlier on the same line —
  // `cond ? 'a' : 'b'` flags both arms, `{ 'key': v }` flags neither.
  for (const m of code.matchAll(ANY_STRING_RE)) {
    const value = m[1] ?? m[2] ?? '';
    const start = m.index;
    const end = start + m[0].length;

    const lineStart = lineStarts[lineAt(start) - 1];
    const before = code.slice(lineStart, start);
    const ternaryQ = before.lastIndexOf('?');
    const boundary = Math.max(
      before.lastIndexOf('{'),
      before.lastIndexOf('}'),
      before.lastIndexOf(','),
      before.lastIndexOf(';')
    );
    const inTernary = ternaryQ > boundary;

    let j = end;
    while (j < code.length && /\s/.test(code[j])) j += 1;
    if (code[j] === ':' && !inTernary) continue; // object key, not a value

    let k = start - 1;
    while (k >= 0 && /\s/.test(code[k])) k -= 1;
    const prev = code[k];

    if (prev === '{') {
      // {'x'} — unless the {} is an attribute value (name={'x'}), which the
      // attr pass already reported.
      let q = k - 1;
      while (q >= 0 && /\s/.test(code[q])) q -= 1;
      if (code[q] === '=') continue;
      consider(start, 'jsx-expr', value);
    } else if (prev === '?' || prev === '&' || prev === '|') {
      consider(start, 'jsx-expr', value); // cond && 'x', a ?? 'x', c ? 'x'
    } else if (prev === ':' && inTernary) {
      consider(start, 'jsx-expr', value); // second arm of cond ? 'a' : 'b'
    }
  }

  return findings.sort((a, b) => a.line - b.line);
}

describe('hardcoded-string audit', () => {
  const used = new Set<string>();
  const findings: Finding[] = [];
  for (const [globKey, source] of Object.entries(SOURCES)) {
    const relPath = globKey.replace(/^\.\.\//, '');
    findings.push(...scanFile(relPath, source, used));
  }

  it('flags question-mark prose while comparison-ternary fragments stay exempt', () => {
    // Regression probe for the `\s\?\s*$` fragment arm: `{a > b ? <i/> : <b/>}`
    // is a code fragment (whitespace before `?`); `…?` prose is not.
    const probe = [
      'const Probe = () => (',
      '  <div>',
      '    <span>Delete this booking?</span>',
      '    <span>Are you sure?</span>',
      '    <span>Continue?</span>',
      '    {a > b ? <i /> : <b />}',
      '  </div>',
      ');',
    ].join('\n');
    const found = scanFile('probe/fixture.tsx', probe, new Set());
    expect(found.map((f) => `${f.kind}  ${f.text}`).sort()).toEqual([
      'jsx-text  Are you sure?',
      'jsx-text  Continue?',
      'jsx-text  Delete this booking?',
    ]);
  });

  it('flags no user-visible literal outside the allowlist', () => {
    expect(
      findings.map((f) => `${f.file}:${f.line}  ${f.kind}  ${f.text}`),
      'hardcoded user-visible strings found — translate via t()/tOr() or add a commented ALLOWLIST entry'
    ).toEqual([]);
  });

  it('every ALLOWLIST entry still matches a finding (no stale exemptions)', () => {
    const all: string[] = [];
    for (const entry of ALLOWLIST) {
      for (const literal of entry.literals) {
        all.push(`${entry.path.source}::${literal}`);
      }
    }
    const stale = all.filter((key) => !used.has(key));
    expect(
      stale,
      'ALLOWLIST entries no longer match any finding — remove them'
    ).toEqual([]);
  });
});
