// Action/resource label + status tone. Colors are --hotel-* token references so
// chips follow the active theme instead of carrying a private palette.
export const AUDIT_ACTION_LABELS: Record<string, { labelKey: string; color: string }> = {
  login_success: { labelKey: 'admin:audit.action.login_success', color: 'var(--hotel-success)' },
  login_failure: { labelKey: 'admin:audit.action.login_failure', color: 'var(--hotel-danger)' },
  logout: { labelKey: 'admin:audit.action.logout', color: 'var(--hotel-neutral)' },
  booking_created: { labelKey: 'admin:audit.action.booking_created', color: 'var(--hotel-info)' },
  booking_updated: { labelKey: 'admin:audit.action.booking_updated', color: 'var(--hotel-warning)' },
  booking_cancelled: { labelKey: 'admin:audit.action.booking_cancelled', color: 'var(--hotel-danger)' },
  booking_voided: { labelKey: 'admin:audit.action.booking_voided', color: 'var(--hotel-danger)' },
  booking_checkin: { labelKey: 'admin:audit.action.booking_checkin', color: 'var(--hotel-success)' },
  booking_checkout: { labelKey: 'admin:audit.action.booking_checkout', color: 'var(--hotel-chart-4)' },
  payment_created: { labelKey: 'admin:audit.action.payment_created', color: 'var(--hotel-success)' },
  payment_recorded: { labelKey: 'admin:audit.action.payment_recorded', color: 'var(--hotel-success)' },
  payment_voided: { labelKey: 'admin:audit.action.payment_voided', color: 'var(--hotel-danger)' },
  payment_refunded: { labelKey: 'admin:audit.action.payment_refunded', color: 'var(--hotel-warning)' },
  customer_ledger_voided: { labelKey: 'admin:audit.action.customer_ledger_voided', color: 'var(--hotel-danger)' },
  customer_ledger_reversed: { labelKey: 'admin:audit.action.customer_ledger_reversed', color: 'var(--hotel-warning)' },
  night_audit_run: { labelKey: 'admin:audit.action.night_audit_run', color: 'var(--hotel-info)' },
  room_status_changed: { labelKey: 'admin:audit.action.room_status_changed', color: 'var(--hotel-warning)' },
  guest_created: { labelKey: 'admin:audit.action.guest_created', color: 'var(--hotel-info)' },
  guest_updated: { labelKey: 'admin:audit.action.guest_updated', color: 'var(--hotel-warning)' },
  guest_deleted: { labelKey: 'admin:audit.action.guest_deleted', color: 'var(--hotel-danger)' },
  user_created: { labelKey: 'admin:audit.action.user_created', color: 'var(--hotel-info)' },
  role_assigned: { labelKey: 'admin:audit.action.role_assigned', color: 'var(--hotel-success)' },
  role_removed: { labelKey: 'admin:audit.action.role_removed', color: 'var(--hotel-danger)' },
  settings_changed: { labelKey: 'admin:audit.action.settings_changed', color: 'var(--hotel-warning)' },
  password_changed: { labelKey: 'admin:audit.action.password_changed', color: 'var(--hotel-chart-4)' },
  ekyc_approved: { labelKey: 'admin:audit.action.ekyc_approved', color: 'var(--hotel-success)' },
  ekyc_rejected: { labelKey: 'admin:audit.action.ekyc_rejected', color: 'var(--hotel-danger)' },
};

export const AUDIT_RESOURCE_LABELS: Record<string, { labelKey: string; color: string }> = {
  user: { labelKey: 'admin:audit.resource.user', color: 'var(--hotel-info)' },
  guest: { labelKey: 'admin:audit.resource.guest', color: 'var(--hotel-success)' },
  booking: { labelKey: 'admin:audit.resource.booking', color: 'var(--hotel-chart-4)' },
  payment: { labelKey: 'admin:audit.resource.payment', color: 'var(--hotel-success)' },
  customer_ledger: { labelKey: 'admin:audit.resource.customer_ledger', color: 'var(--hotel-warning)' },
  invoice: { labelKey: 'admin:audit.resource.invoice', color: 'var(--hotel-chart-4)' },
  room: { labelKey: 'admin:audit.resource.room', color: 'var(--hotel-warning)' },
  user_role: { labelKey: 'admin:audit.resource.user_role', color: 'var(--hotel-neutral)' },
  system_setting: { labelKey: 'admin:audit.resource.system_setting', color: 'var(--hotel-warning)' },
  ekyc_verification: { labelKey: 'admin:audit.resource.ekyc_verification', color: 'var(--hotel-info)' },
};
