import type { HelpArticle } from '../types';

/**
 * Malay Help Centre articles — mirrors articles.en.ts (same slugs, same block
 * shapes; content.test.ts enforces parity). UI element names stay in English
 * because the admin portal renders them in English; surrounding prose is
 * Bahasa Melayu. Flagged for native-speaker review.
 */
export const ARTICLES_MS: HelpArticle[] = [
  // ---------------------------------------------------------- getting started
  {
    slug: 'sign-in-and-security',
    title: 'Log masuk dan selamatkan akaun anda',
    summary: 'Log masuk, tambah passkey atau pengesahan dua faktor, dan log keluar dengan selamat di stesen kerja berkongsi.',
    category: 'getting-started',
    keywords: ['log masuk', 'kata laluan', 'passkey', '2fa', 'dua faktor', 'log keluar', 'komputer berkongsi'],
    routePath: '/profile',
    lastReviewed: '2026-09-13',
    relatedSlugs: ['getting-around-admin-portal', 'page-missing-or-access-denied'],
    blocks: [
      { type: 'paragraph', text: 'Akaun kakitangan dicipta oleh pentadbir. Setelah menerima kelayakan, log masuk dari halaman login — portal akan mengembalikan anda ke halaman yang asalnya anda cuba buka.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka halaman login', body: 'Masukkan nama pengguna dan kata laluan. Jika sesi anda tamat, anda akan dibawa ke sini dahulu kemudian dihantar semula ke halaman yang dikehendaki.' },
          { title: 'Tambah passkey apabila diminta', body: 'Semasa log masuk pertama, anda mungkin diminta mendaftar passkey (cap jari, wajah, atau PIN peranti). Passkey ialah cara paling pantas dan selamat untuk masuk semula — anda boleh menolak prompt dan menetapkannya kemudian dari profil anda.' },
          { title: 'Daftar pengesahan dua faktor', body: 'Jika peranan anda memerlukannya, anda akan dibimbing melalui pendaftaran 2FA. Sediakan aplikasi pengesah anda.' },
          { title: 'Log keluar pada akhir syif', body: 'Buka menu akaun anda (atas kanan) dan pilih Sign Out. Di stesen kerja kaunter hadapan yang dikongsi, ini bukan pilihan — orang seterusnya mewarisi sesi yang ditinggalkan.' },
        ],
      },
      { type: 'callout', tone: 'warning', title: 'Stesen kerja berkongsi', body: 'Jangan biarkan sesi yang telah log masuk tanpa pengawasan di kaunter hadapan. Log keluar akan memadam token akses dalam ingatan.' },
      { type: 'callout', tone: 'tip', body: 'Jika halaman memaparkan Access denied, peranan anda sememangnya tidak merangkuminya — lihat “Kenapa saya tidak dapat melihat halaman?” sebelum menganggap ada kerosakan.' },
    ],
  },
  {
    slug: 'getting-around-admin-portal',
    title: 'Mengemudi portal admin',
    summary: 'Kumpulan navigasi, palet arahan, notifikasi, bahasa dan tema — lima kawalan yang akan anda gunakan setiap syif.',
    category: 'getting-started',
    keywords: ['navigasi', 'menu', 'palet arahan', 'carian', 'tema', 'bahasa', 'mod gelap', 'english'],
    lastReviewed: '2026-09-13',
    featured: true,
    relatedSlugs: ['sign-in-and-security', 'cant-find-a-booking'],
    blocks: [
      { type: 'paragraph', text: 'Bar atas membawa semua yang anda perlukan. Baris pertama mempunyai nama hotel, bar carian, pintasan New booking, bahasa, notifikasi dan menu akaun anda. Baris kedua mempunyai navigasi modul, dikumpulkan sebagai Main, Operations, Administration dan Configuration.' },
      {
        type: 'list',
        items: [
          'Modul Main dan Operations (Timeline, Guests, Bookings, Rooms, Online Inventory, Reports, Housekeeping, Support) muncul sebagai pill satu klik.',
          'Administration dan Configuration dilipat ke dalam menu lungsur supaya bar muat pada mana-mana skrin.',
          'Pada telefon atau tetingkap sempit, semua kumpulan berpindah ke laci sisi yang dibuka melalui butang menu.',
        ],
      },
      { type: 'heading', text: 'Cari apa-apa dengan ⌘K' },
      { type: 'paragraph', text: 'Tekan ⌘K (Ctrl+K pada Windows) atau klik bar carian untuk membuka palet arahan. Ia mencari tempahan, tetamu, entri lejar, bilik, halaman — dan artikel bantuan. Kekunci anak panah menggerakkan hasil, Enter membuka pilihan, Esc menutup. Taip / untuk tindakan pantas seperti New booking.' },
      { type: 'heading', text: 'Bahasa dan tema' },
      { type: 'paragraph', text: 'Ikon glob menukar antara English dan Bahasa Melayu serta-merta — tanpa muat semula. Tema cerah, gelap dan malam ditetapkan dari Hotel Settings; pilihan diingati mengikut stesen kerja.' },
      { type: 'callout', tone: 'tip', body: 'Palet mengingati enam destinasi terkini anda, jadi perjalanan berulang hanya mengambil dua ketukan kekunci.' },
    ],
  },
  {
    slug: 'page-missing-or-access-denied',
    title: 'Kenapa saya tidak dapat melihat halaman?',
    summary: 'Halaman muncul berdasarkan peranan dan kebenaran anda — item menu yang hilang atau skrin Access denied hampir selalu keputusan akses, bukan kerosakan.',
    category: 'getting-started',
    keywords: ['access denied', '403', 'kebenaran', 'menu tersembunyi', 'peranan', 'tidak nampak', 'halaman hilang'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security'],
    blocks: [
      { type: 'paragraph', text: 'Setiap modul dalam portal admin dilindungi oleh dasar akses laluan. Navigasi anda hanya menunjukkan destinasi yang dibenarkan oleh peranan dan kebenaran anda — dua kakitangan boleh melihat menu yang sangat berbeza pada skrin yang sama.' },
      {
        type: 'list',
        items: [
          'Item menu hilang → dasar laluan mengecualikan peranan anda atau anda tiada kebenarannya.',
          'Anda membuka pautan dan melihat Access denied (403) → anda boleh melihat portal tetapi bukan modul itu.',
          'Sesuatu berfungsi semalam tetapi tidak hari ini → peranan anda atau dasar laluan telah berubah. Semak Audit Log atau tanya pentadbir.',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: 'Sahkan modul itu wujud', body: 'Tanya rakan sekerja sama ada mereka dapat melihat halaman itu. Jika tiada siapa dapat, ia mungkin isu konfigurasi dan bukan akses.' },
          { title: 'Tanya pentadbir anda', body: 'Akses diberikan dalam Access Control → Users (lantik peranan) atau Roles (ubah apa yang peranan benarkan). Hanya pentadbir boleh mengubahnya.' },
        ],
      },
      { type: 'callout', tone: 'info', body: 'Kebenaran *:manage merangkumi setiap tindakan lain pada sumber itu — contohnya, bookings:manage merangkumi create, read, update dan delete.' },
    ],
  },

  // ------------------------------------------------------------------ bookings
  {
    slug: 'create-a-booking',
    title: 'Cipta tempahan',
    summary: 'Buat tempahan dari butang New booking — pilih tarikh, bilik, kadar dan bayaran dalam satu skrin.',
    category: 'bookings',
    keywords: ['tempahan', 'tempahan baharu', 'walk in', 'tempahan telefon', 'tempahan manual'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:create'],
    lastReviewed: '2026-09-13',
    featured: true,
    relatedSlugs: ['check-in-a-guest', 'find-a-reservation', 'void-reactivate-release'],
    blocks: [
      { type: 'paragraph', text: 'Tempahan walk-in, telefon dan tetamu berulang semuanya dicipta melalui skrin New booking yang sama. Ia menggabungkan tarikh penginapan, pemilihan bilik, butiran tetamu dan kadar/bayaran dalam satu aliran.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka New booking', body: 'Gunakan butang putih New booking di bar atas, atau buka Bookings dan mulakan di sana.' },
          { title: 'Pilih tarikh dan mod penginapan', body: 'Pilih tarikh check-in dan check-out. Pemilih mod tempahan menyesuaikan aliran mengikut jenis tempahan yang anda buat.' },
          { title: 'Pilih bilik', body: 'Pilih jenis bilik, kemudian bilik tertentu. Hanya bilik yang kosong untuk keseluruhan tempoh ditawarkan.' },
          { title: 'Masukkan butiran tetamu', body: 'Cari tetamu sedia ada atau masukkan yang baharu — nama, butiran hubungan dan warganegara menentukan cukai dan semakan identiti.' },
          { title: 'Tetapkan kadar dan bayaran', body: 'Semak harga semalam dan jumlah, pilih kaedah bayaran dan deposit, kemudian sahkan.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Warganegara Local vs Foreign mengawal sama ada cukai pelancongan dikenakan — ia dipilih pada bahagian tetamu, bukan semasa bayaran.' },
      { type: 'callout', tone: 'important', title: 'Hold dalam talian tanpa bayaran', body: 'Tempahan yang kekal dalam pending_payment ialah hold. Ia dilepaskan secara automatik selepas tempoh yang ditetapkan dalam Hotel Settings (unpaid hold release hours) dan boleh dilepaskan secara manual lebih awal.' },
    ],
  },
  {
    slug: 'find-a-reservation',
    title: 'Cari tempahan',
    summary: 'Cari mana-mana tempahan mengikut kod, nama tetamu atau bilik — dari senarai Bookings atau palet ⌘K.',
    category: 'bookings',
    keywords: ['cari tempahan', 'tempahan hilang', 'kod tempahan', 'bk-', 'carian'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-09-13',
    featured: true,
    relatedSlugs: ['cant-find-a-booking', 'check-in-a-guest', 'create-a-booking'],
    blocks: [
      { type: 'paragraph', text: 'Terdapat dua laluan pantas bergantung pada apa yang anda tahu: senarai Bookings apabila anda mahu menyemak dan menapis, atau palet ⌘K apabila anda tahu kod tempahan atau tetamu.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka palet ⌘K', body: 'Tekan ⌘K atau klik bar carian. Pilih cip skop Bookings untuk mengehadkan hasil.' },
          { title: 'Cari mengikut kod atau tetamu', body: 'Taip kod tempahan (contohnya BK-…) atau nama tetamu. Memilih hasil membuka Bookings yang sudah ditapis kepada tempahan itu.' },
          { title: 'Atau tapis senarai Bookings', body: 'Pada halaman Bookings, gunakan bar penapis — status, tarikh dan nombor bilik mengecilkan senarai tanpa meninggalkan halaman.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Menampal kod tempahan ke dalam palet ialah carian paling pantas — hasilnya memaut terus ke senarai yang ditapis.' },
      { type: 'callout', tone: 'info', title: 'Jika masih tidak muncul', body: 'Tempahan void dan hold tanpa bayaran yang dilepaskan dikecualikan daripada paparan biasa. Lihat “Tidak jumpa tempahan?” untuk senarai semak penuh.' },
    ],
  },
  {
    slug: 'check-in-a-guest',
    title: 'Daftar masuk tetamu',
    summary: 'Tandakan ketibaan pada hari check-in — tempahan confirmed dan pending layak; check-in awal ditandakan, bukan disekat.',
    category: 'bookings',
    keywords: ['ketibaan', 'checkin', 'daftar masuk', 'kaunter hadapan', 'check in awal'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['check-out-a-guest', 'find-a-reservation', 'housekeeping-maintenance'],
    blocks: [
      { type: 'paragraph', text: 'Tempahan boleh didaftar masuk apabila statusnya confirmed atau pending dan tarikh ketibaan telah tiba. Tindakan Check in berada pada tempahan itu sendiri.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka tempahan', body: 'Cari melalui ⌘K atau senarai Bookings dan buka butirannya.' },
          { title: 'Pilih Check in', body: 'Tindakan ini hanya muncul apabila tempahan layak — status confirmed atau pending dan hari ini pada atau selepas tarikh check-in.' },
          { title: 'Semak makluman check-in', body: 'Tetamu yang biasa dibilkan kepada syarikat boleh mencetuskan makluman sebelum anda meneruskan — bacanya, kemudian sahkan.' },
          { title: 'Sahkan', body: 'Tempahan berpindah ke checked_in dan bilik menunjukkan diduduki pada Rooms dan Timeline.' },
        ],
      },
      { type: 'callout', tone: 'info', title: 'Check-in awal', body: 'Tiba sebelum waktu check-in yang dikonfigurasi (Hotel Settings → check-in time, lalai 15:00) memaparkan prompt check-in awal dan bukannya sekatan keras.' },
      { type: 'callout', tone: 'warning', body: 'Butang Check in tidak akan muncul sebelum tarikh ketibaan — ini disengajakan. Jika tetamu tiba sehari awal, edit tarikh tempahan dahulu.' },
    ],
  },
  {
    slug: 'check-out-a-guest',
    title: 'Daftar keluar tetamu',
    summary: 'Tutup penginapan dari tempahan atau papan Rooms — hanya tempahan checked-in boleh check out.',
    category: 'bookings',
    keywords: ['pelepasan', 'checkout', 'daftar keluar', 'berlepas', 'selesai', 'checkout lewat'],
    routePath: '/room-management',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['check-in-a-guest', 'refund-a-deposit', 'housekeeping-maintenance'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: 'Buka tempahan atau papan Rooms', body: 'Check out tersedia dari tindakan tempahan, dan papan Rooms memaparkan Overdue Checkouts supaya tiada yang terlepas.' },
          { title: 'Pilih Check out', body: 'Tindakan ini hanya muncul semasa status tempahan checked_in.' },
          { title: 'Selesaikan penginapan', body: 'Tempahan yang melepasi tarikh check-out dengan baki tertunggak — termasuk penginapan bil syarikat yang melepasi terma bayaran — diketengahkan supaya anda boleh mengutip atau mengatur bayaran sebelum atau semasa pelepasan.' },
          { title: 'Serahkan bilik kepada housekeeping', body: 'Selepas check-out, bilik kembali ke aliran kerja housekeeping/penyelenggaraan untuk pengemasan sebelum ketibaan seterusnya.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Jika deposit telah dikutip, bayar balik semasa check-out — lihat “Bayar balik deposit”.' },
      { type: 'callout', tone: 'warning', body: 'Tempahan tidak boleh check out melainkan ia checked_in. Jika status kelihatan salah, semak garis masa tempahan untuk melihat apa yang berlaku.' },
    ],
  },
  {
    slug: 'void-reactivate-release',
    title: 'Void, reactivate atau release tempahan',
    summary: 'Void membatalkan tempahan, reactivate memulihkan yang void, dan release membebaskan hold dalam talian tanpa bayaran — tiga tindakan berbeza dengan peraturan berbeza.',
    category: 'bookings',
    keywords: ['batal', 'void', 'aktif semula', 'lepas', 'hold tanpa bayaran', 'tiada bayaran', 'noshow'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['create-a-booking', 'refund-a-deposit', 'find-a-reservation'],
    blocks: [
      { type: 'paragraph', text: 'Setiap tindakan wujud untuk situasi berbeza, dan setiap satu hanya ditawarkan apabila tempahan layak — jika butang hilang, status tempahan ialah puncanya.' },
      {
        type: 'list',
        items: [
          'Void — membatalkan tempahan. Tersedia pada mana-mana tempahan yang belum void. Gunakan untuk pembatalan.',
          'Reactivate — memulihkan tempahan void. Hanya ditawarkan pada tempahan void.',
          'Release — membebaskan bilik yang dipegang oleh tempahan dalam talian tanpa bayaran. Hanya ditawarkan semasa status pending_payment dan tiada bayaran telah dikutip.',
        ],
      },
      { type: 'heading', text: 'Hold tanpa bayaran lepas sendiri' },
      { type: 'paragraph', text: 'Tugas latar belakang melepaskan hold tanpa bayaran secara automatik selepas tempoh yang dikonfigurasi dalam Hotel Settings (unpaid hold release hours — lalai 24, 0 menyahaktif). Release manual ialah untuk mengosongkan bilik lebih awal.' },
      { type: 'callout', tone: 'important', title: 'Wang sudah dikutip?', body: 'Release sengaja tidak tersedia sebaik sahaja wujud sebarang bayaran — backend turut menguatkuasakannya. Void tempahan dan bayar balik tetamu sebaliknya.' },
      { type: 'callout', tone: 'tip', body: 'Setiap peralihan ini direkodkan dalam garis masa tempahan dan Audit Log — anda sentiasa boleh melihat siapa melakukan apa.' },
    ],
  },
  {
    slug: 'read-the-timeline',
    title: 'Baca garis masa tempahan',
    summary: 'Pandangan bilik-mengikut-hari tentang siapa tiba, menginap atau berlepas — cara terpantas melihat penghunian sepintas lalu.',
    category: 'bookings',
    keywords: ['garis masa', 'kalendar', 'paparan penghunian', 'pergerakan bilik', 'ketibaan pelepasan'],
    routePath: '/timeline',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['daily-room-operations', 'check-in-a-guest', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: 'Timeline menyusun tempahan merentasi bilik dan hari supaya anda dapat melihat ketibaan, penginapan dalaman dan pelepasan sebagai peta dan bukan senarai. Ia ialah skrin yang sesuai untuk perancangan perpindahan bilik dan mengesan kekosongan.' },
      {
        type: 'list',
        items: [
          'Imbas seminggu penghunian dalam beberapa saat — berguna sebelum menerima walk-in.',
          'Rancang perpindahan bilik mengelilingi tempahan berturut-turut pada bilik yang sama.',
          'Kenal pasti bilik kosong untuk check-in awal tanpa membuka setiap tempahan.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Padankan dengan papan Rooms: Timeline untuk “siapa di mana bila”, Rooms untuk “apa keadaan setiap bilik sekarang”.' },
    ],
  },

  // -------------------------------------------------------------------- guests
  {
    slug: 'manage-guest-profiles',
    title: 'Urus profil tetamu',
    summary: 'Cari, edit dan selenggara rekod tetamu — termasuk kesempurnaan profil dan pemindahan akaun portal.',
    category: 'guests',
    keywords: ['tetamu', 'profil', 'edit tetamu', 'sejarah tetamu', 'nombor ic', 'akaun portal'],
    routePath: '/guest-config',
    requiredPermissions: ['guests:read', 'guests:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['create-a-booking', 'notifications-guest-support', 'import-export-data'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: 'Buka Guests', body: 'Guest Management menyenaraikan setiap profil tetamu. Carian mengecilkan mengikut nama atau butiran hubungan.' },
          { title: 'Buka profil', body: 'Lihat butiran hubungan, medan identiti, sejarah tempahan dan kesempurnaan profil sepintas lalu.' },
          { title: 'Edit apa yang berubah', body: 'Pastikan telefon dan e-mel terkini — ia menggerakkan resit, kempen dan aliran pra-check-in.' },
          { title: 'Kendalikan akaun portal dengan teliti', body: 'Transfer Guest Portal Account memindahkan log masuk portal ke profil berbeza — gunakan hanya apabila anda pasti akaun itu milik orang yang sama.' },
        ],
      },
      { type: 'callout', tone: 'warning', title: 'Memadam tetamu', body: 'Delete Guest memadam profil. Utamakan edit berbanding padam apabila tempahan wujud — sejarah penting untuk lejar dan laporan.' },
      { type: 'callout', tone: 'tip', body: 'Kesempurnaan profil menandakan medan yang hilang (seperti telefon) yang menyekat aliran seperti notifikasi — ia tempat pertama untuk disemak apabila tetamu “tidak dapat dihubungi”.' },
    ],
  },

  // ----------------------------------------------------------- rooms & inventory
  {
    slug: 'room-types-and-rooms',
    title: 'Sediakan jenis bilik dan bilik',
    summary: 'Jenis bilik mentakrifkan apa sesuatu bilik dan harganya; bilik ialah unit fizikal tempat tetamu tidur — kedua-duanya diurus dalam Room Configuration.',
    category: 'rooms-inventory',
    keywords: ['jenis bilik', 'tambah bilik', 'bilik baharu', 'susunan katil', 'kapasiti', 'harga', 'padam bilik'],
    routePath: '/room-config',
    requiredPermissions: ['rooms:create', 'rooms:update'],
    lastReviewed: '2026-09-13',
    featured: true,
    relatedSlugs: ['daily-room-operations', 'online-inventory-grid', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: 'Room Configuration ialah tempat model hartanah berada. Jenis bilik membawa takrifan dikongsi — nama, susunan katil, kapasiti, harga dan status — dan setiap bilik ialah unit bernombor bagi sesuatu jenis.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Room Configuration', body: 'Cari ia di bawah menu Configuration.' },
          { title: 'Cipta atau edit jenis bilik', body: 'Lalui bahagian-bahagian — Basics (nama, penerangan), Bed Setup, Capacity (penghuni maksimum), Pricing (harga semalam) dan Status.' },
          { title: 'Tambah bilik kepada jenis itu', body: 'Setiap bilik mendapat nombor dan tergolong dalam sesuatu jenis. Bilik mewarisi harga dan kapasiti jenis itu.' },
          { title: 'Semak sebelum memadam', body: 'Delete Room memadam unit; Delete Room Type memadam takrifan — hanya apabila tiada apa bergantung padanya.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Harga bermula di sini', body: 'Kadar yang tetamu lihat bermula pada bahagian Pricing jenis bilik. Override dalam talian diurus secara berasingan dalam Online Inventory.' },
      { type: 'callout', tone: 'tip', body: 'Max Occupancy menggerakkan pengesahan tempahan dan perancangan housekeeping — pastikan ia tepat.' },
    ],
  },
  {
    slug: 'daily-room-operations',
    title: 'Jalankan operasi bilik harian',
    summary: 'Papan Rooms: status bilik langsung, check-in dan check-out, perpindahan bilik, sekatan penyelenggaraan dan pelepasan lewat.',
    category: 'rooms-inventory',
    keywords: ['status bilik', 'diduduki', 'penyelenggaraan', 'bilik disekat', 'pindah bilik', 'checkout lewat', 'bilik kotor'],
    routePath: '/room-management',
    requiredPermissions: ['rooms:read', 'rooms:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['check-out-a-guest', 'housekeeping-maintenance', 'read-the-timeline'],
    blocks: [
      { type: 'paragraph', text: 'Rooms ialah papan operasi untuk hartanah fizikal — bilik mana diduduki, mana kosong, mana disekat, dan pelepasan mana yang lewat.' },
      {
        type: 'list',
        items: [
          'Lajur Check-in / Check-out menunjukkan pergerakan hari ini sepintas lalu.',
          'Overdue Checkouts memaparkan tetamu yang sepatutnya sudah berlepas — selesaikan dahulu setiap syif.',
          'Maintenance / Blocked menandakan bilik tidak boleh dijual sehingga sekatan dilepaskan.',
          'Select New Room memindahkan tetamu antara bilik tanpa void tempahan.',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: 'Mulakan dari papan Rooms', body: 'Buka Rooms untuk gambaran keseluruhan hartanah.' },
          { title: 'Selesaikan checkout lewat dahulu', body: 'Susul atau check out setiap penginapan lewat supaya bilik boleh dikemas dan dijual semula.' },
          { title: 'Sekat bilik dengan jujur', body: 'Bilik dalam penyelenggaraan mesti ditanda Maintenance / Blocked — jika tidak, inventori dalam talian terus menjualnya.' },
          { title: 'Pindahkan tetamu dengan Select New Room', body: 'Untuk pertukaran bilik, pilih bilik baharu — tempahan mengikut tetamu.' },
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Bilik yang disekat masih memerlukan tiket penyelenggaraan untuk penjejakan — lihat “Tiket housekeeping dan penyelenggaraan”.' },
    ],
  },
  {
    slug: 'online-inventory-grid',
    title: 'Kawal inventori dalam talian',
    summary: 'Override ketersediaan dan harga mengikut jenis bilik dan tarikh pada grid Online Inventory — termasuk edit pukal.',
    category: 'rooms-inventory',
    keywords: ['inventori dalam talian', 'ketersediaan', 'jual online', 'override kadar', 'tutup tarikh', 'henti jual'],
    routePath: '/online-inventory',
    requiredPermissions: ['rooms:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['room-types-and-rooms', 'daily-room-operations', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: 'Online Inventory ialah grid tarikh-mengikut-jenis-bilik yang mengawal apa yang tetamu boleh tempah dalam talian. Setiap sel boleh memegang override — nilai asas datang dari jenis bilik.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Online Inventory', body: 'Grid menunjukkan jenis bilik sebagai baris dan tarikh akan datang sebagai lajur.' },
          { title: 'Edit satu sel', body: 'Klik sel untuk membuka popover editor dan tetapkan nilai tarikh itu.' },
          { title: 'Atau edit pukal satu julat', body: 'Pilih berbilang sel, kemudian gunakan panel Bulk Edit untuk mengenakan satu perubahan merentasi pilihan.' },
          { title: 'Semak sebelum menyimpan', body: 'Perubahan terkumpul dalam Review Changes — sahkan di sana, dan gunakan penapis “overrides only” untuk mengaudit apa yang berbeza dari tetapan asas.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Sel yang diubah dan di-override ditandakan, jadi anda sentiasa boleh membezakan konfigurasi asas dari keputusan sekali sahaja.' },
      { type: 'callout', tone: 'important', body: 'Untuk menghentikan jualan dalam talian bagi sesuatu tarikh, override sel itu — jangan sekat bilik secara fizikal melainkan ia benar-benar tidak boleh digunakan.' },
    ],
  },
  {
    slug: 'housekeeping-maintenance',
    title: 'Tiket housekeeping dan penyelenggaraan',
    summary: 'Jejaki keadaan bilik dan kerja penyelenggaraan — cipta tiket, lantik pemegang, dan kembalikan bilik ke dalam perkhidmatan.',
    category: 'rooms-inventory',
    keywords: ['housekeeping', 'pengemasan', 'tiket penyelenggaraan', 'baiki', 'kotor', 'dilantik kepada'],
    routePath: '/housekeeping',
    requiredPermissions: ['housekeeping:read', 'housekeeping:create'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['daily-room-operations', 'check-out-a-guest', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: 'Housekeeping menyelaraskan kerja pengemasan dan penyelenggaraan setiap bilik. Isu penyelenggaraan dijejaki sebagai tiket dengan bilik, kategori, keutamaan, pemegang dan status.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Housekeeping', body: 'Tapis papan mengikut tingkat, keutamaan atau status untuk memfokuskan syif.' },
          { title: 'Cipta tiket penyelenggaraan', body: 'New maintenance ticket merekodkan bilik, kategori, keutamaan, tajuk dan kepada siapa ia dilantik.' },
          { title: 'Selesaikan giliran', body: 'Kemas kini status tiket mengikut perkembangan kerja; bilik disekat kekal tidak boleh dijual sehingga diselesaikan.' },
          { title: 'Kembalikan bilik ke perkhidmatan', body: 'Setelah diselesaikan dan dikemas, kosongkan sebarang status Maintenance / Blocked pada papan Rooms.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Tapis mengikut keutamaan dahulu — penghawa dingin bocor lebih mendesak daripada dinding tercalar apabila bilik sedang dijual.' },
    ],
  },

  // ----------------------------------------------------------- payments & ledgers
  {
    slug: 'refund-a-deposit',
    title: 'Bayar balik deposit',
    summary: 'Pulangkan deposit tetamu dari tempahan — bayaran balik ialah tugas checkout biasa; membatalkannya sengaja dihadkan.',
    category: 'payments-ledgers',
    keywords: ['bayaran balik', 'deposit', 'pulangan wang', 'refund', 'batal refund'],
    routePath: '/bookings',
    requiredPermissions: ['payments:refund'],
    lastReviewed: '2026-09-13',
    featured: true,
    relatedSlugs: ['check-out-a-guest', 'review-payment-approvals', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: 'Bayaran balik deposit ialah kerja kaunter hadapan rutin semasa checkout. Tindakan bayaran balik berada pada tindakan bayaran tempahan dan memerlukan kebenaran payments:refund, yang dipegang oleh receptionist dan manager.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka tempahan', body: 'Cari penginapan dan buka butiran bayarannya.' },
          { title: 'Pilih tindakan bayaran balik deposit', body: 'Sahkan jumlah yang dipulangkan kepada tetamu.' },
          { title: 'Rekodkan kaedah', body: 'Bayar balik mengikut cara deposit dikutip melainkan ada sebaliknya — rekod itulah yang ditunjukkan oleh lejar dan jejak audit.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Membatalkan bayaran balik adalah terhad', body: 'Mengembalikan semula bayaran balik deposit membuka semula deposit untuk dibayar balik dan memerlukan payments:manage — receptionist tidak boleh kitar refund/revert sendiri. Semak dua kali sebelum mengesahkan.' },
      { type: 'callout', tone: 'tip', body: 'Jika butang bayaran balik hilang, anda tiada payments:refund — minta manager dan bukannya mengatasi dengan pelarasan manual.' },
    ],
  },
  {
    slug: 'review-payment-approvals',
    title: 'Semak kelulusan bayaran',
    summary: 'Bukti bayaran menunggu dalam giliran semakan — periksa resit berbanding tempahan, kemudian lulus atau tolak.',
    category: 'payments-ledgers',
    keywords: ['kelulusan bayaran', 'resit', 'bukti bayaran', 'lulus bayaran', 'tolak bayaran', 'pindahan bank'],
    routePath: '/payment-approvals',
    requiredPermissions: ['payments:approve'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['refund-a-deposit', 'company-ledgers', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: 'Payment Approvals menyenaraikan bukti bayaran yang diserahkan bersama tempahan, tetamu, jumlah, kaedah dan resit. Setiap item berpindah dari Submitted ke Reviewed sebaik sahaja anda bertindak.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Payment Approvals', body: 'Cari ia di bawah menu Administration.' },
          { title: 'Periksa bukti', body: 'Buka item dan muat turun resit — semak jumlah dan rujukan berbanding tempahan.' },
          { title: 'Lulus atau tolak', body: 'Lulus apabila bukti sepadan; tolak dengan sebab apabila tidak. Keputusan direkodkan atas akaun anda.' },
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Bayaran dalam talian yang ditolak mencetuskan aliran e-mel pemulihan bayaran kepada tetamu — tolak hanya apabila bukti benar-benar salah.' },
      { type: 'callout', tone: 'tip', body: 'Selesaikan giliran yang paling lama dahulu: check-in tetamu mungkin menunggu semakan anda.' },
    ],
  },
  {
    slug: 'company-ledgers',
    title: 'Bekerja dengan lejar syarikat',
    summary: 'Akaun korporat mengumpul penginapan yang dibilkan dalam lejar — semak baki, terma bayaran dan akaun lewat.',
    category: 'payments-ledgers',
    keywords: ['lejar', 'syarikat', 'korporat', 'invois', 'dibilkan', 'terma bayaran', 'city ledger'],
    routePath: '/company-ledger',
    requiredPermissions: ['ledgers:read'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['review-payment-approvals', 'reports-and-metrics', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: 'Company Ledger menjejaki penginapan yang dibilkan kepada akaun korporat dan bukannya dibayar semasa checkout. Setiap lejar menunjukkan syarikat, tempahannya dan baki berjalan.' },
      {
        type: 'list',
        items: [
          'Tetamu pada tempahan bil syarikat boleh mencetuskan makluman semasa check-in — bil pergi ke syarikat, bukan tetamu.',
          'Terma bayaran mentakrifkan berapa lama syarikat ada untuk melangsaikan; akaun yang melepasi terma dengan baki diketengahkan secara automatik.',
          'Senarai Bookings boleh menapis kepada penginapan bil syarikat sahaja.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Syarikat yang melepasi termanya ialah perbualan untuk manager — sistem menandakannya, manusia menyelesaikannya.' },
    ],
  },
  {
    slug: 'complimentary-nights-credits',
    title: 'Malam percuma dan kredit tetamu',
    summary: 'Tandakan penginapan sebagai percuma, tukarkannya kepada kredit, dan urus baki malam percuma setiap tetamu dan jenis bilik.',
    category: 'payments-ledgers',
    keywords: ['percuma', 'malam percuma', 'kredit', 'kredit bilik percuma', 'kredit hadiah', 'penginapan comp'],
    routePath: '/complimentary',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['create-a-booking', 'company-ledgers', 'loyalty-program'],
    blocks: [
      { type: 'paragraph', text: 'Pengurusan complimentary merangkumi penginapan percuma: menandakan tempahan sebagai complimentary, menukar penginapan complimentary kepada kredit tetamu, dan menempah dengan kredit itu — semuanya dijejaki setiap tetamu dan jenis bilik.' },
      {
        type: 'list',
        items: [
          'Tandakan tempahan complimentary dari tindakan tempahan.',
          'Tukar penginapan complimentary kepada kredit — baki berada dengan tetamu, mengikut skop jenis bilik.',
          'Tempah dengan kredit untuk menggunakan baki malam percuma tetamu pada penginapan baharu.',
          'Paparan ringkasan menunjukkan jumlah complimentary dan kredit tertunggak.',
        ],
      },
      { type: 'callout', tone: 'important', body: 'Membuang status complimentary atau memadam kredit mengubah apa yang tetamu berhak terima — anggap kedua-duanya sebagai keputusan peringkat manager walaupun kebenaran membenarkannya.' },
    ],
  },

  // ---------------------------------------------------------- rates & promotions
  {
    slug: 'promotions-vouchers',
    title: 'Urus promosi dan baucar',
    summary: 'Cipta tawaran yang tetamu lihat pada halaman Offers awam dan baucar yang mendiskaunkan tempahan.',
    category: 'rates-promotions',
    keywords: ['promosi', 'baucar', 'diskaun', 'kod promo', 'tawaran', 'deal', 'kempen'],
    routePath: '/campaigns',
    requiredPermissions: ['promotions:manage', 'vouchers:manage'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['email-campaigns-templates', 'online-inventory-grid', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: 'Promotions & Vouchers mengurus bahagian tawaran hartanah: tawaran awam yang tetamu boleh lihat pada halaman Offers, dan baucar yang dikenakan pada tempahan.' },
      {
        type: 'list',
        items: [
          'Promosi mentakrifkan tawaran — namanya, bila ia berjalan dan apa yang diberikannya.',
          'Baucar ialah kod tebus yang terikat pada tawaran itu.',
          'E-mel kempen boleh merujuk promosi secara langsung dari Communications.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Promosi menjual apa yang Online Inventory hargakan — pastikan tawaran awam, terma baucar dan kadar sebenar menceritakan kisah yang sama.' },
    ],
  },
  {
    slug: 'loyalty-program',
    title: 'Fahami program kesetiaan',
    summary: 'Loyalty menjejaki tetamu berulang dan ganjaran mereka — lihat dari bahagian Loyalty di bawah Administration.',
    category: 'rates-promotions',
    keywords: ['kesetiaan', 'ganjaran', 'mata', 'tetamu berulang', 'ahli'],
    routePath: '/loyalty',
    requiredPermissions: ['loyalty:read'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['complimentary-nights-credits', 'manage-guest-profiles', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: 'Bahagian Loyalty menunjukkan sisi program bagi tetamu berulang: keadaan keahlian dan kedudukan ganjaran. Kakitangan dengan loyalty:manage mentadbirnya; loyalty:read memadai untuk melihat.' },
      { type: 'callout', tone: 'tip', body: 'Loyalty, malam percuma dan kredit tetamu ialah tiga tuas berbeza — semak profil tetamu sebelum menggunakan mana-mana satunya supaya anda tidak memberi ganti dua kali.' },
    ],
  },

  // ------------------------------------------------------ reports & night audit
  {
    slug: 'reports-and-metrics',
    title: 'Baca laporan dan metrik',
    summary: 'Laporan operasi harian, penghunian (termasuk ADR dan RevPAR) dan hasil — apa maksud setiap angka.',
    category: 'reports-night-audit',
    keywords: ['laporan', 'penghunian', 'adr', 'revpar', 'hasil', 'ketibaan', 'pelepasan', 'analitik', 'metrik'],
    routePath: '/reports',
    requiredPermissions: ['reports:read'],
    lastReviewed: '2026-09-13',
    featured: true,
    relatedSlugs: ['run-night-audit', 'audit-log', 'online-inventory-grid'],
    blocks: [
      { type: 'paragraph', text: 'Reports menukar operasi mentah kepada ringkasan. Tiga keluarga merangkumi kebanyakan keperluan: Daily Operations untuk pergerakan hari ini, Occupancy untuk kepenuhan hartanah, dan Revenue untuk wang.' },
      {
        type: 'list',
        items: [
          'Daily Operations — ketibaan hari ini, pelepasan hari ini, tetamu dalaman dan kadar penghunian.',
          'Occupancy — bilik dijual berbanding jumlah bilik, serta ADR (kadar harian purata) dan RevPAR (hasil setiap bilik tersedia).',
          'Revenue — jumlah hasil dipecahkan mengikut jenis bilik dan sumber tempahan.',
        ],
      },
      { type: 'heading', text: 'Dua metrik yang orang tanya' },
      {
        type: 'list',
        items: [
          'ADR — harga purata dibayar setiap bilik dijual: hasil bilik ÷ bilik dijual. Ia menjawab “adakah kita menjual tinggi?”',
          'RevPAR — hasil diagihkan atas setiap bilik yang anda miliki, dijual atau tidak: hasil bilik ÷ jumlah bilik. Ia menjawab “adakah kita memenuhkan pada kadar baik?”',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Kadar penghunian tanpa ADR menyorokkan diskaun; ADR tanpa penghunian menyorokkan bilik kosong. Baca kedua-duanya bersama.' },
    ],
  },
  {
    slug: 'run-night-audit',
    title: 'Jalankan night audit',
    summary: 'Tutup hari perniagaan: sahkan audit, yang mengunci tempahan daripada editan dan merakamkan status bilik.',
    category: 'reports-night-audit',
    keywords: ['night audit', 'akhir hari', 'tutup hari', 'kunci tempahan', 'tarikh perniagaan'],
    routePath: '/night-audit',
    requiredPermissions: ['night_audit:execute'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['reports-and-metrics', 'audit-log', 'hotel-settings'],
    blocks: [
      { type: 'paragraph', text: 'Night audit menutup hari perniagaan hotel. Mengesahkannya merekodkan siapa menjalankannya dan bila, mengunci tempahan hari itu daripada editan lanjut, dan boleh merakamkan status bilik untuk pelaporan.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Night Audit', body: 'Cari ia di bawah menu Administration dan semak tarikh audit.' },
          { title: 'Semak apa yang larian itu akan lakukan', body: 'Pengesahan menyenaraikan pilihan — termasuk mengunci tempahan dan merekodkan gambaran status bilik.' },
          { title: 'Sahkan Night Audit', body: 'Larian direkodkan dengan akaun dan cap masa anda; Audit Log mencerminkannya.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Penguncian adalah nyata', body: 'Selepas audit, tempahan hari itu menahan editan lanjut — jalankan apabila hari benar-benar selesai, atau gunakan tetapan auto-run dalam Hotel Settings.' },
      { type: 'callout', tone: 'tip', body: 'Tarikh perniagaan mengikut zon masa hotel dalam Hotel Settings — audit menutup hari itu, bukan tengah malam UTC.' },
    ],
  },
  {
    slug: 'audit-log',
    title: 'Guna audit log',
    summary: 'Rekod baca-sahaja tentang siapa mengubah apa — persinggahan pertama apabila sesuatu kelihatan berbeza daripada semalam.',
    category: 'reports-night-audit',
    keywords: ['audit log', 'sejarah', 'siapa mengubah', 'aktiviti', 'jejak'],
    routePath: '/audit-log',
    requiredPermissions: ['audit:read'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['page-missing-or-access-denied', 'run-night-audit', 'roles-and-permissions'],
    blocks: [
      { type: 'paragraph', text: 'Audit Log merekodkan tindakan mengubah merentasi sistem — perubahan tempahan, editan tetapan, kemas kini peranan, larian night audit. Ia baca-sahaja mengikut reka bentuk.' },
      {
        type: 'list',
        items: [
          'Menyiasat tempahan atau tetapan yang berubah → mulakan di sini sebelum bertanya keliling.',
          'Semakan akses → log menunjukkan siapa memberi apa dan bila.',
          'Setiap entri menamakan pelaku dan cap masa, jadi susulan pergi kepada orang, bukan misteri.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Padankan dengan garis masa tempahan: log merekodkan tindakan, garis masa menceritakan kisah penginapan.' },
    ],
  },

  // ------------------------------------------------------------- communications
  {
    slug: 'email-campaigns-templates',
    title: 'Hantar kempen e-mel dan urus templat',
    summary: 'Bina templat e-mel boleh guna semula, kemudian hantar kempen kepada tetamu terpilih — dengan e-mel ujian sebelum apa-apa sebenar keluar.',
    category: 'communications',
    keywords: ['e-mel', 'kempen', 'templat', 'pengumuman', 'pemasaran', 'hantar ujian', 'pemboleh ubah'],
    routePath: '/communications',
    requiredPermissions: ['communications:compose', 'communications:send'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['email-not-sending', 'promotions-vouchers', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: 'Communications mempunyai dua bahagian: Email templates (kandungan boleh guna semula dengan pemboleh ubah) dan Campaigns (hantaran sebenar kepada penerima, seperti pengumuman yang dipautkan kepada promosi).' },
      {
        type: 'steps',
        steps: [
          { title: 'Cipta atau pilih templat', body: 'Templat membawa subjek dan isi dengan pemboleh ubah untuk nilai khusus tetamu.' },
          { title: 'Hantar e-mel ujian', body: 'Send test email membuktikan format dan penghantaran ke alamat anda sendiri sebelum mana-mana tetamu melihatnya.' },
          { title: 'Cipta kempen', body: 'Pilih jenis (contohnya Announcement), penerima, subjek dan isi — secara pilihan memautkan promosi.' },
          { title: 'Pantau hantaran', body: 'Kempen bergerak melalui draft → scheduled → running → completed; kiraan Sent / Failed dan lajur Last error mendedahkan masalah.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Sentiasa hantar ujian dahulu — pemboleh ubah yang rosak memalukan pada skala besar.' },
    ],
  },
  {
    slug: 'notifications-guest-support',
    title: 'Notifikasi dan peti masuk sokongan tetamu',
    summary: 'Suapan notifikasi anda ialah untuk anda; peti masuk Support ialah untuk tetamu — jawab mesej mereka di sana.',
    category: 'communications',
    keywords: ['notifikasi', 'loceng', 'peti masuk sokongan', 'mesej tetamu', 'perbualan', 'balas', 'lantik'],
    routePath: '/support',
    requiredPermissions: ['support:read', 'support:write'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['email-not-sending', 'manage-guest-profiles', 'getting-around-admin-portal'],
    blocks: [
      { type: 'paragraph', text: 'Terdapat dua permukaan “sokongan” berbeza. Loceng di bar atas ialah suapan notifikasi kakitangan anda. Support di bawah Operations ialah peti masuk tempat mesej tetamu dari portal tiba — itu memerlukan balasan kakitangan.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Support', body: 'Senarai perbualan menunjukkan perbualan tetamu yang terbuka.' },
          { title: 'Baca dan balas', body: 'Buka perbualan untuk melihat mesej tetamu dan balas dalam talian.' },
          { title: 'Lantik apabila perlu', body: 'Perbualan boleh dilantik kepada ejen — ambil atau serahkan pemilikan dan bukannya membalas secara selari.' },
          { title: 'Kemas kini status', body: 'Tutup atau kemas kini keadaan perbualan supaya giliran kekal tepat.' },
        ],
      },
      { type: 'callout', tone: 'info', title: 'Bukan sokongan IT kakitangan', body: 'Peti masuk ini ialah untuk tetamu yang meminta bantuan hotel. Untuk bantuan dengan portal admin sendiri, gunakan panduan “Dapatkan lebih bantuan” dalam Help Centre.' },
      { type: 'callout', tone: 'tip', body: 'Peti masuk sokongan boleh dimatikan untuk seluruh hartanah dalam Hotel Settings — jika keseluruhan modul hilang, togel itu ialah suspek pertama.' },
    ],
  },
  {
    slug: 'email-not-sending',
    title: 'E-mel tidak dihantar',
    summary: 'Kenal pasti kegagalan e-mel kempen dan notifikasi — kebanyakan punca kelihatan dalam lajur Last error atau hantaran ujian yang gagal.',
    category: 'communications',
    keywords: ['e-mel gagal', 'smtp', 'tidak dihantar', 'ralat e-mel', 'kempen gagal', 'last error'],
    routePath: '/communications',
    requiredPermissions: ['communications:read'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['email-campaigns-templates', 'notifications-guest-support', 'escalation'],
    blocks: [
      { type: 'paragraph', text: 'E-mel berjalan melalui pekerja latar belakang yang memerlukan kelayakan SMTP dikonfigurasi pada pelayan. Apabila mel berhenti, buktinya hampir selalu pada halaman Communications sendiri.' },
      {
        type: 'steps',
        steps: [
          { title: 'Hantar e-mel ujian', body: 'Ujian yang gagal membuktikan masalahnya ialah infrastruktur, bukan kandungan kempen anda.' },
          { title: 'Baca lajur Last error', body: 'Hantaran kempen merekodkan sebab kegagalan setiap penerima — ralat pengesahan, sambungan dan alamat masing-masing bermaksud pembetulan berbeza.' },
          { title: 'Semak kiraan Sent / Failed', body: 'Kegagalan separa menunjuk kepada alamat penerima; kegagalan penuh menunjuk kepada konfigurasi SMTP.' },
          { title: 'Eskalasi masalah SMTP', body: 'Tetapan mel pelayan ialah konfigurasi persekitaran, bukan skrin dalam portal — serahkan kepada sesiapa yang mengurus penggunaan.' },
        ],
      },
      { type: 'callout', tone: 'important', body: 'Jika tiada tetapan SMTP wujud, pekerja e-mel sememangnya dimatikan — tiada apa rosak pada skrin anda, keupayaan itu tidak pernah dikonfigurasi.' },
    ],
  },

  // -------------------------------------------------------------- staff & access
  {
    slug: 'add-manage-staff',
    title: 'Tambah dan urus akaun kakitangan',
    summary: 'Cipta log masuk untuk rakan sekerja, lantik peranan mereka, dan edit atau buang akaun dari Access Control.',
    category: 'staff-access',
    keywords: ['tambah pengguna', 'kakitangan baharu', 'akaun pekerja', 'cipta pengguna', 'padam pengguna', 'log masuk kakitangan'],
    routePath: '/rbac',
    requiredPermissions: ['users:create', 'users:update'],
    lastReviewed: '2026-09-13',
    featured: true,
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: 'Buka Access Control', body: 'Cari ia di bawah menu Configuration, kemudian buka tab Users.' },
          { title: 'Pilih Add User', body: 'Dialog Create New User mengumpul butiran akaun untuk ahli kakitangan baharu.' },
          { title: 'Lantik peranan', body: 'Peranan menentukan apa yang orang itu boleh lihat dan lakukan — receptionist dan manager mendapat portal berbeza. Lantik dalam aliran yang sama atau kemudian dari baris pengguna.' },
          { title: 'Edit atau buang kemudian', body: 'Edit User mengemas kini butiran; Delete User membuang akaun sepenuhnya apabila seseorang berhenti.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Peranan sebelum log masuk pertama', body: 'Pengguna tanpa peranan melihat hampir tiada apa — jika rakan sekerja melaporkan portal kosong, semak lantikan peranan mereka dahulu.' },
      { type: 'callout', tone: 'tip', body: 'Utamakan mengedit peranan berbanding mencipta akaun sekali sahaja; Audit Log menjejaki setiap perubahan walau apa pun.' },
    ],
  },
  {
    slug: 'roles-and-permissions',
    title: 'Peranan dan kebenaran',
    summary: 'Peranan menghimpun kebenaran; kebenaran mengawal halaman dan tindakan. Kebenaran *:manage merangkumi selebihnya dalam domainnya.',
    category: 'staff-access',
    keywords: ['peranan', 'kebenaran', 'rbac', 'kawalan akses', 'kebenaran manage', 'receptionist manager'],
    routePath: '/rbac',
    requiredPermissions: ['roles:read', 'roles:manage'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['add-manage-staff', 'page-missing-or-access-denied', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: 'Access Control mempunyai tiga tab: Users (akaun), Roles (himpunan bernama seperti Receptionist atau Manager) dan Permissions (keupayaan individu dihimpun mengikut domain).' },
      {
        type: 'list',
        items: [
          'Kebenaran kelihatan seperti sumber:tindakan — contohnya bookings:create atau payments:refund.',
          'Kebenaran sumber:manage merangkumi setiap tindakan pada sumber itu.',
          'Dasar laluan memetakan halaman kepada kebenaran, sebab itulah menu berbeza setiap pengguna.',
          'Peranan sistem datang dengan pemberian munasabah; peranan tersuai boleh dicipta untuk persediaan luar biasa.',
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Mengubah peranan sistem mengubahnya untuk semua yang memegangnya — utamakan peranan baharu apabila seorang sahaja memerlukan sesuatu yang berbeza.' },
      { type: 'callout', tone: 'tip', body: 'Kebenaran dihimpun mengikut kategori pada tab Permissions — kembangkan kategori untuk melihat dengan tepat apa yang peranan boleh lakukan.' },
    ],
  },
  {
    slug: 'ekyc-reviews',
    title: 'Semak penyerahan eKYC',
    summary: 'Kerja pengesahan identiti berlaku dalam giliran eKYC Admin — penyemak yang dilantik bertindak pada penyerahan mengikut tahap risiko.',
    category: 'staff-access',
    keywords: ['ekyc', 'identiti', 'pengesahan', 'kyc', 'penyemak', 'pematuhan'],
    routePath: '/ekyc-admin',
    requiredPermissions: ['ekyc:review'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['roles-and-permissions', 'audit-log', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: 'eKYC Admin ialah giliran semakan untuk pengesahan identiti elektronik. Peranan khusus — eKYC Reviewer, Senior Reviewer dan Compliance Administrator — mengendalikan penyerahan, dengan kes berisiko tinggi dieskalasi kepada semakan kanan.' },
      {
        type: 'list',
        items: [
          'Penyemak bertindak pada permohonan yang dilantik; penyemak kanan mengendalikan eskalasi dan kelulusan berisiko tinggi.',
          'Tindakan sensitif (mendedahkan dokumen, melihat data pembekal) mempunyai kebenaran tersendiri dan direkodkan.',
          'Jika anda tidak dapat melihat modul itu, anda tidak memegang peranan eKYC — itu mengikut reka bentuk, bukan pepijat.',
        ],
      },
      { type: 'callout', tone: 'info', body: 'Kebenaran eKYC sengaja terperinci — minta hanya tindakan yang diperlukan oleh tahap semakan anda.' },
    ],
  },

  // ------------------------------------------------------------- settings & data
  {
    slug: 'hotel-settings',
    title: 'Konfigurasi tetapan hotel',
    summary: 'Profil hartanah, waktu check-in/out, zon masa, cukai, deposit, fon laporan dan togel ciri — lalai yang diwarisi oleh setiap skrin lain.',
    category: 'settings-data',
    keywords: ['tetapan', 'nama hotel', 'zon masa', 'waktu check in', 'cukai', 'deposit', 'cukai pelancongan', 'cukai perkhidmatan', 'konfigurasi'],
    routePath: '/settings',
    requiredPermissions: ['settings:update'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['run-night-audit', 'room-types-and-rooms', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: 'Hotel Settings memegang lalai seluruh hartanah yang diwarisi skrin lain: nama dan butiran hubungan, waktu check-in/check-out, zon masa, jumlah deposit, kadar cukai perkhidmatan dan pelancongan, terma bayaran, tipografi laporan dan togel ciri.' },
      {
        type: 'list',
        items: [
          'Waktu check-in dan check-out menggerakkan prompt check-in awal dan sasaran housekeeping.',
          'Zon masa mentakrifkan tarikh perniagaan — laporan, night audit dan “hari ini” semuanya mengikutnya.',
          'Jumlah deposit, cukai perkhidmatan dan cukai pelancongan memberi makan kepada jumlah tempahan; tetamu asing membawa cukai pelancongan.',
          'Togel sokongan dan pembatalan tetamu menghidupkan atau mematikan keseluruhan ciri.',
          'Tetapan fon laporan membentuk output cetakan.',
        ],
      },
      { type: 'callout', tone: 'important', title: 'Tingkap hold tanpa bayaran juga di sini', body: 'Unpaid hold release hours mengawal berapa lama tempahan pending_payment memegang bilik sebelum auto-release (lalai 24; 0 menyahaktif).' },
      { type: 'callout', tone: 'warning', body: 'Simpan tetapan terpakai serta-merta — kadar cukai atau zon masa yang salah menyentuh setiap tempahan baharu.' },
    ],
  },
  {
    slug: 'import-export-data',
    title: 'Import dan eksport data',
    summary: 'Data Transfer menggerakkan sandaran masuk dan keluar — pratonton dahulu, dengan amaran keras sebelum apa-apa yang memusnahkan.',
    category: 'settings-data',
    keywords: ['import', 'eksport', 'sandaran', 'pulih', 'pemindahan data', 'migrasi', 'pangkalan data'],
    routePath: '/data-transfer',
    requiredPermissions: ['settings:manage'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['hotel-settings', 'audit-log', 'escalation'],
    blocks: [
      { type: 'paragraph', text: 'Data Transfer mengendalikan pemindahan data hotel masuk dan keluar — untuk sandaran, pemulihan dan migrasi. Pemindahan dipratonton sebelum digunakan dan direkodkan dalam Transfer History.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Data Transfer', body: 'Pilih fail sandaran untuk diimport atau mulakan eksport.' },
          { title: 'Semak pratonton import', body: 'Pratonton menunjukkan apa yang fail mengandungi dan menandakan kebergantungan hilang sebelum apa-apa ditulis.' },
          { title: 'Sahkan import', body: 'Pemulihan pangkalan data penuh memadam semua data sedia ada dahulu — UI menyatakannya dengan jelas. Teruskan hanya pada fail yang anda percayai.' },
          { title: 'Semak Transfer History', body: 'Import dan eksport lalu disenaraikan dengan siapa menjalankannya.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Memusnahkan mengikut reka bentuk', body: '“This deletes all existing data first” adalah literal — pemulihan penuh menggantikan pangkalan data. Sahkan fail dan pemasaan dengan pentadbir anda.' },
    ],
  },

  // ------------------------------------------------------------- troubleshooting
  {
    slug: 'cant-find-a-booking',
    title: 'Tidak jumpa tempahan?',
    summary: 'Lalui senarai semak: istilah carian, penapis, dan dua keadaan (void, released) yang menyembunyikan tempahan daripada paparan biasa.',
    category: 'troubleshooting',
    keywords: ['tempahan hilang', 'tempahan tidak jumpa', 'tiada hasil', 'lesap'],
    routePath: '/bookings',
    lastReviewed: '2026-09-13',
    relatedSlugs: ['find-a-reservation', 'void-reactivate-release', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          'Cuba kod tempahan dalam ⌘K — kod BK- dan nama tetamu kedua-duanya mencari.',
          'Buang penapis pada senarai Bookings — penapis status atau bilik yang tertinggal ialah punca biasa.',
          'Semak tarikh: penginapan mungkin berada di luar julat yang anda lihat.',
          'Tanya sama ada tempahan telah void — penginapan void meninggalkan paparan biasa.',
          'Semak hold tanpa bayaran yang dilepaskan — tempahan dalam talian yang tidak pernah dibayar dilepaskan semula ke inventori secara automatik.',
          'Sahkan anda dapat melihat Bookings langsung — modul yang hilang ialah soalan kebenaran, bukan masalah carian.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Garis masa tempahan dan Audit Log kedua-duanya tahan terhadap void — jika tempahan itu pernah wujud, kisahnya masih ada.' },
    ],
  },
  {
    slug: 'payment-problems',
    title: 'Masalah bayaran',
    summary: 'Bayaran dalam talian gagal, kelulusan tersangkut dan ralat bayaran balik — padankan simptom dengan giliran yang betul.',
    category: 'troubleshooting',
    keywords: ['bayaran gagal', 'ralat bayaran', 'ditolak', 'pulih bayaran', 'kelulusan tersangkut', 'ralat refund'],
    routePath: '/payment-approvals',
    lastReviewed: '2026-09-13',
    relatedSlugs: ['refund-a-deposit', 'review-payment-approvals', 'email-not-sending'],
    blocks: [
      {
        type: 'list',
        items: [
          'Bayaran tetamu gagal dalam talian → e-mel pemulihan bayaran boleh membiarkan mereka cuba semula melalui pautan selamat — semak keadaan tempahan sebelum menganggap wang itu hilang.',
          'Bukti bayaran menunggu → ia berada dalam Payment Approvals sehingga seseorang menyemaknya; tetamu melihat “submitted”, bukan “confirmed”.',
          'Butang bayaran balik hilang → anda memerlukan payments:refund; mengembalikan semula bayaran balik memerlukan payments:manage.',
          'Tempahan tersangkut dalam pending_payment → ia ialah hold tanpa bayaran; ia auto-release atau boleh dilepaskan secara manual.',
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Jangan “perbaiki” bayaran tersangkut dengan mengedit tempahan — selesaikan giliran kelulusan atau eskalasi; lejar dan jejak audit memerlukan sebab yang sebenar.' },
    ],
  },
  {
    slug: 'session-and-stale-data',
    title: 'Isu sesi dan data lapuk',
    summary: 'Apabila skrin kelihatan lapuk atau sesi tidak bertingkah — susunan refresh, tamat masa terbiar dan perangkap tarikh perniagaan.',
    category: 'troubleshooting',
    keywords: ['data lapuk', 'refresh', 'sesi tamat', 'keluar log', 'tarikh salah', 'zon masa'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['sign-in-and-security', 'hotel-settings', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          'Refresh halaman — selepas tempoh terbiar yang lama token sesi diperbaharui secara automatik; skrin lapuk hanya memerlukan muat semula.',
          'Log keluar dan masuk semula jika keadaan sesi tidak konsisten.',
          'Tarikh kelihatan salah → tarikh perniagaan mengikut zon masa hotel dalam Hotel Settings, bukan jam komputer riba anda.',
          'Tetapan berubah tetapi tiada apa bergerak → sesetengah perubahan terpakai pada aktiviti baharu sahaja, bukan secara retroaktif.',
          'Peranti lain kelihatan berbeza → tema dan bahasa mengikut stesen kerja, kebenaran mengikut akaun.',
        ],
      },
      { type: 'callout', tone: 'info', body: 'Log keluar berulang bukan kerosakan — token akses jangka pendek mengikut reka bentuk dan diperbaharui secara senyap di latar belakang.' },
    ],
  },
  {
    slug: 'escalation',
    title: 'Dapatkan lebih bantuan',
    summary: 'Apa yang perlu dilakukan apabila Help Centre tidak menyelesaikannya — siapa untuk ditanya dan apa yang perlu dibawa kepada mereka.',
    category: 'troubleshooting',
    keywords: ['hubungi', 'eskalasi', 'manager', 'pentadbir', 'lebih bantuan', 'sokongan'],
    lastReviewed: '2026-09-13',
    relatedSlugs: ['page-missing-or-access-denied', 'payment-problems', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: 'Help Centre merangkumi cara portal berfungsi. Untuk akses akaun, perubahan kebenaran dan apa-apa yang kelihatan seperti kecacatan, eskalasi dalam rantaian hartanah anda sendiri.' },
      {
        type: 'steps',
        steps: [
          { title: 'Tanya pentadbir atau manager anda', body: 'Perubahan akses, peranan dan tetapan adalah milik mereka — bawa nama halaman dan apa yang anda jangkakan untuk dilihat.' },
          { title: 'Bawa bukti', body: 'Entri Audit Log, kod tempahan, teks Last error kempen — rekod tertentu mengalahkan penerangan simptom.' },
          { title: 'Untuk isu berdepan tetamu', body: 'Jika tetamu melaporkan masalah, semak peti masuk Support untuk perbualan sedia ada mereka dan bukannya memulakan urutan selari.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Tangkapan skrin membantu, tetapi teks ralat tepat dan masa ia berlaku membantu lebih — kedua-duanya berada dalam rekod aplikasi sendiri.' },
    ],
  },
];
