import type { HelpArticle } from '../types';

/**
 * 中文幫助中心文章（繁體中文，映象 articles.en.ts 的 slug 與區塊結構；
 * content.test.ts 負責校驗結構一致性）。
 *
 * 以下每個流程都已在管理埠中核實：頁面名稱與導航登錄檔一致、按鈕標籤與
 * 渲染 UI 一致、許可權標識與 seed.sql 一致。介面變更時，請同步更新對應文章並
 * 更新 `lastReviewed`。
 */
export const ARTICLES_ZH_TW: HelpArticle[] = [
  // ---------------------------------------------------------- 入門
  {
    slug: 'sign-in-and-security',
    title: '登入並保護您的帳戶',
    summary: '登入、新增通行金鑰或雙重驗證，並在共用工作站上安全退出。',
    category: 'getting-started',
    keywords: ['登入', '密碼', '通行金鑰', '2fa', '雙重驗證', '退出', '共用電腦'],
    routePath: '/profile',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['getting-around-admin-portal', 'page-missing-or-access-denied'],
    blocks: [
      { type: 'paragraph', text: '員工帳戶由管理員建立。獲得憑據後，從登入頁登入——門戶會恢復您最初嘗試開啟的頁面。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟登入頁', body: '輸入使用者名稱和密碼。如果會話已過期，系統會先帶您回到此頁，然後再跳轉到您想去的頁面。' },
          { title: '按提示新增通行金鑰', body: '首次登入時，系統可能會要求您註冊通行金鑰（指紋、人臉或裝置 PIN）。通行金鑰是最快、最安全的再次登入方式——您可以暫時忽略提示，稍後在個人資料中設定。' },
          { title: '註冊雙重驗證', body: '如果您的角色有此要求，系統會引導您完成 2FA 註冊。請準備好您的驗證器應用。' },
          { title: '班次結束時登出', body: '點選頂欄最右端、帳戶頭像旁的“登出”圖示。在共用的前檯工作站上，這不是可選項——下一位使用者會繼承您未登出的工作階段。' },
        ],
      },
      { type: 'callout', tone: 'warning', title: '共用工作站', body: '切勿在前檯留下無人看管的已登入工作階段。登出會清除記憶體中的存取權杖。手機寬度的螢幕不顯示“登出”圖示——請改用平板或桌面結束工作階段。' },
      { type: 'callout', tone: 'tip', body: '如果頁面顯示“訪問被拒絕”，通常只是您的角色不包含該頁面——在懷疑係統故障之前，請先檢視“為什麼看不到某個頁面？”。' },
    ],
  },
  {
    slug: 'getting-around-admin-portal',
    title: '熟悉管理門戶',
    summary: '導航分組、命令面板、通知、語言與主題——每個班次都會用到的五個控制元件。',
    category: 'getting-started',
    keywords: ['導航', '選單', '命令面板', '搜尋', '主題', '語言', '深色模式', '馬來語'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['sign-in-and-security', 'cant-find-a-booking'],
    blocks: [
      { type: 'paragraph', text: '門戶由兩個區域承載。側邊欄是酒店名稱、“新增預訂”按鈕和模組導航，分為“總覽”、“前檯作業”、“賓客”、“營收與行銷”、“財務”、“分析洞察”、“行政管理”和“工具”八組。頂欄是搜尋、通知鈴鐺、語言、帳戶選單和“登出”圖示。' },
      {
        type: 'list',
        items: [
          '“前檯作業”涵蓋前檯的日常工作——預訂、時間軸、客房和房務；“賓客”包含賓客關係、賓客目錄、客服支援和忠誠計畫。',
          '“營收與行銷”是營收、房價、行銷活動、客群、通路、通訊和線上庫存；“財務”是帳冊、付款核准、夜間稽核和免費房晚。',
          '“行政管理”是存取控制、eKYC 管理、飯店設定、客房設定、稽核紀錄、資料轉移、系統健康度和工作；“工具”是發送紀錄與本說明中心。',
          '在手機上，導航移到螢幕底欄——幾個主要目的地加“更多”，點開後列出您能看到的其餘全部模組，語言列表在其下方。沒有側邊抽屜，也沒有頁首選單按鈕。',
          '只有您的角色可見的分組才會出現——同一個螢幕上，兩位員工的側邊欄可能完全不同。',
        ],
      },
      { type: 'heading', text: '用 ⌘K 找到任何東西' },
      { type: 'paragraph', text: '按 ⌘K（Windows 上為 Ctrl+K）或點選搜尋欄——手機上為搜尋圖示——開啟命令面板。它可以搜尋預訂、賓客、帳條、客房、頁面——以及說明文章。方向鍵瀏覽結果，回車開啟所選，Esc 關閉。輸入 / 可執行“新增預訂”等快捷操作。' },
      { type: 'heading', text: '語言與主題' },
      { type: 'paragraph', text: '地球圖示可在 English、Bahasa Melayu、简体中文和繁體中文之間即時切換——無需重新整理；在手機上它位於“更多”面板底部。飯店設定 → 外觀只有淺色和深色。已儲存的夜間模式會以深色開啟，選擇按這台工作站記住。' },
      { type: 'callout', tone: 'tip', body: '命令面板會記住您最近去過的六個目的地，重複跳轉只需按兩下鍵盤。' },
    ],
  },
  {
    slug: 'page-missing-or-access-denied',
    title: '為什麼看不到某個頁面？',
    summary: '頁面根據您的角色和許可權顯示——選單項缺失或“訪問被拒絕”頁面幾乎都是許可權決定，而非故障。',
    category: 'getting-started',
    keywords: ['訪問被拒絕', '403', '許可權', '選單缺失', '角色', '看不到', '頁面缺失'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security'],
    blocks: [
      { type: 'paragraph', text: '管理門戶中的每個模組都受路由訪問策略保護。您的導航只顯示角色和許可權允許的目的地——在同一螢幕上，兩位員工可能看到完全不同的選單。' },
      {
        type: 'list',
        items: [
          '選單項缺失 → 路由策略排除了您的角色，或您缺少相應許可權。',
          '開啟連結後看到“訪問被拒絕”（403）→ 您可以訪問門戶，但不能訪問該模組。',
          '昨天能用今天不行 → 您的角色或路由策略發生了變化。請檢視審計日誌或詢問管理員。',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: '確認模組存在', body: '詢問同事是否能看到該頁面。如果沒人能看到，可能是配置問題而非許可權問題。' },
          { title: '詢問管理員', body: '權限在“行政管理 → 存取控制”中授予：“使用者”標籤頁指派角色，“角色與權限”標籤頁編輯角色允許的操作。只有管理員可以更改。' },
        ],
      },
      { type: 'callout', tone: 'info', body: '*:manage 權限隱含該資源的所有其他操作——例如 bookings:manage 涵蓋建立、讀取、更新和刪除。' },
    ],
  },
  {
    slug: 'front-desk-overview',
    title: '在「總覽」開始您的班次',
    summary: '「總覽」是門戶首頁——前檯的當日抵達、離店和房態，或經理的分析儀表板。',
    category: 'getting-started',
    keywords: ['總覽', '儀表板', '首頁', '前檯', '今日抵達', '離店', '房態'],
    routePath: '/',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['getting-around-admin-portal', 'daily-room-operations', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: '「總覽」是門戶開啟後落地的頁面。顯示什麼取決於您的角色：前檯員工看到的是營運當日看板——抵達、離店和即時房態快照；經理和管理員看到的是分析儀表板。' },
      {
        type: 'list',
        items: [
          '前檯看板呈現當天的進出動態——待入住的抵達、待退房的離店、需要留意的客房——以及新預訂到達時的滾動條。',
          '管理儀表板彙總營收、入住率和趨勢分析，而不是前檯的工作佇列。',
          '看板上的每一項都能繼續跳轉——一列即開啟對應預訂或客房，所以「總覽」是起點而不是終點。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '從這裡開始班次，先清抵達和離店，再讓「預訂」或客房看板接手剩下的時間。' },
    ],
  },

  // ------------------------------------------------------------------ 預訂
  {
    slug: 'create-a-booking',
    title: '建立預訂',
    summary: '通過“新建預訂”按鈕建立預訂——在一個螢幕內選擇日期、房間、房價和支付方式。',
    category: 'bookings',
    keywords: ['預訂', '新建預訂', '上門客', '電話預訂', '手動預訂'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:create'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['check-in-a-guest', 'find-a-reservation', 'void-reactivate-release'],
    blocks: [
      { type: 'paragraph', text: '上門、電話和回頭客預訂都通過同一個“新建預訂”介面建立。它把住宿日期、選房、客人資料和房價/支付合併為單一流程。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「新增預訂」', body: '使用側邊欄頂部的「新增預訂」按鈕，或「預訂」頁面上的「新增預訂」按鈕。在手機上它也在快捷操作面板中。' },
          { title: '選擇住宿日期和模式', body: '選擇入住和退房日期。預訂模式選擇器會按預訂型別調整流程。' },
          { title: '選擇房間', body: '先選房型，再選具體房間。系統只提供整個期間都空閒的房間。' },
          { title: '填寫客人資料', body: '搜尋現有客人或錄入新客人——姓名、聯絡方式和國籍欄位會影響稅費和身份核驗。' },
          { title: '設定房價和支付', body: '核對每晚價格和總價，選擇支付方式和押金方式，然後確認。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '客人國籍中的“本地/外籍”決定旅遊稅是否適用——它在客人區域選擇，而不是在支付時。' },
      { type: 'callout', tone: 'important', title: '未付款的線上保留', body: '停留在 pending_payment 狀態的預訂屬於保留房。它們會在“飯店設定”中配置的時長（未付款保留釋放小時數）後自動釋放，也可以提前手動釋放。' },
    ],
  },
  {
    slug: 'find-a-reservation',
    title: '查詢預訂',
    summary: '通過編號、客人姓名或房間查詢任意預訂——使用“預訂”列表或 ⌘K 面板。',
    category: 'bookings',
    keywords: ['搜尋預訂', '查詢預訂', '預訂丟失', '預訂編號', 'bk-', '查詢'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['cant-find-a-booking', 'check-in-a-guest', 'create-a-booking'],
    blocks: [
      { type: 'paragraph', text: '取決於您掌握的資訊，有兩條快速路徑：想瀏覽和篩選時用“預訂”列表；知道預訂編號或客人時用 ⌘K 面板。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟 ⌘K 面板', body: '按 ⌘K 或點選搜尋欄。選擇“預訂”範圍標籤以限定結果。' },
          { title: '按編號或客人搜尋', body: '輸入預訂編號（例如 BK-…）或客人姓名。選擇結果會開啟已過濾到該預訂的“預訂”頁面。' },
          { title: '或者篩選「預訂」列表', body: '在「預訂」頁面，搜尋框可比對預訂、賓客、發票和房號，檢視標籤（全部、抵達、在住、即將到來、逾期餘額）以及付款方式、線上通路、日期和月份篩選都能在不離開頁面的情況下縮小範圍。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '把預訂編號貼上到面板是最快的查詢方式——結果會直接深鏈到過濾後的列表。' },
      { type: 'callout', tone: 'info', title: '如果仍然找不到', body: '已作廢的預訂和已釋放的未付款保留不會出現在日常檢視中。完整排查清單見“找不到預訂？”。' },
    ],
  },
  {
    slug: 'check-in-a-guest',
    title: '為客人辦理入住',
    summary: '在入住當天標記到店——已確認和待確認的預訂都符合條件；提前入住會被提示而非阻止。',
    category: 'bookings',
    keywords: ['到店', '入住', '前臺', '提前入住', '客人到達'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['check-out-a-guest', 'find-a-reservation', 'housekeeping-maintenance'],
    blocks: [
      { type: 'paragraph', text: '當預訂狀態為已確認或待確認且到達入住日期後，即可辦理入住。“入住”操作位於預訂本身。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟預訂', body: '通過 ⌘K 或“預訂”列表找到它並開啟詳情。' },
          { title: '選擇“入住”', body: '該操作只在預訂符合條件時出現——狀態為已確認或待確認，且今天不早於入住日期。' },
          { title: '檢視入住提示', body: '通常由公司結算的客人可能會在繼續前觸發提示——閱讀後確認。' },
          { title: '確認', body: '預訂狀態變為 checked_in，房間在“房間”和“時間線”上顯示為已入住。' },
        ],
      },
      { type: 'callout', tone: 'info', title: '提前入住', body: '早於配置的入住時間（飯店設定 → 入住時間，預設 15:00）到達會彈出提前入住提示，而不是硬性阻止。' },
      { type: 'callout', tone: 'warning', body: '在到達日期之前不會出現“入住”按鈕——這是有意設計。如果客人提前一天到達，請先修改預訂日期。' },
    ],
  },
  {
    slug: 'check-out-a-guest',
    title: '為客人辦理退房',
    summary: '從預訂或房間看板結束住宿——只有已入住的預訂才能退房。',
    category: 'bookings',
    keywords: ['離店', '退房', '離開', '結賬', '逾期退房'],
    routePath: '/room-management',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['check-in-a-guest', 'refund-a-deposit', 'housekeeping-maintenance'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: '開啟預訂或房間看板', body: '退房可從預訂操作中進行；房間看板會顯示“逾期退房”，確保無一遺漏。' },
          { title: '選擇“退房”', body: '該操作只在預訂狀態為 checked_in 時出現。' },
          { title: '結清住宿', body: '超過退房日期且仍有餘額未付的預訂——包括超過付款期限的公司掛賬住宿——會被列出，以便您在離店前或離店時收款或安排付款。' },
          { title: '把客房送回清潔', body: '退房後，客房回到房務佇列並自動建立清潔任務——客房本身不會自動開維修工單。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '如果收過押金，請在退房時退還——見“退還押金”。' },
      { type: 'callout', tone: 'warning', body: '預訂必須處於 checked_in 狀態才能退房。如果狀態看起來不對，請檢視預訂時間線瞭解發生了什麼。' },
    ],
  },
  {
    slug: 'void-reactivate-release',
    title: '作廢、恢復或釋放預訂',
    summary: '作廢即取消預訂，恢復可還原已作廢的預訂，釋放可騰出未付款線上保留——三個操作，三套規則。',
    category: 'bookings',
    keywords: ['取消', '作廢', '恢復', '釋放', '未付款保留', '未付款', '爽約'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['create-a-booking', 'refund-a-deposit', 'find-a-reservation'],
    blocks: [
      { type: 'paragraph', text: '每個操作針對不同情形，且只在預訂符合條件時出現——如果按鈕缺失，原因就在預訂狀態上。' },
      {
        type: 'list',
        items: [
          '作廢——取消預訂。任何未作廢的預訂都可使用，用於處理取消。',
          '恢復——把已作廢的預訂還原。只在已作廢的預訂上提供。',
          '釋放——騰出由未付款線上預訂佔用的房間。只在狀態為 pending_payment 且未收任何款項時提供。',
        ],
      },
      { type: 'heading', text: '未付款保留會自動釋放' },
      { type: 'paragraph', text: '後臺任務會在“飯店設定”配置的時長（未付款保留釋放小時數——預設 24，0 為停用）後自動釋放未付款保留。手動釋放用於更快騰出房間。' },
      { type: 'callout', tone: 'important', title: '已收款？', body: '一旦存在任何付款，釋放就被有意停用——後端同樣強制此規則。請作廢預訂並向客人退款。' },
      { type: 'callout', tone: 'tip', body: '這些狀態變化都會寫入預訂時間線和審計日誌——您始終可以檢視誰在何時做了什麼。' },
    ],
  },
  {
    slug: 'read-the-timeline',
    title: '讀懂預訂時間線',
    summary: '按房間和日期檢視誰將到達、在住或離店——一眼掌握入住率的最快方式。',
    category: 'bookings',
    keywords: ['時間線', '日曆', '入住率檢視', '房間排程', '到店離店'],
    routePath: '/timeline',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['daily-room-operations', 'check-in-a-guest', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: '時間線把預訂鋪在房間和日期的網格上，讓到店、在住和離店像地圖一樣呈現，而不是列表。它是規劃換房和發現空檔的正確介面。' },
      {
        type: 'list',
        items: [
          '幾秒內掃完一週的入住情況——接待上門客之前很有用。',
          '圍繞同一房間的緊挨預訂規劃換房。',
          '不用逐個開啟預訂就能找到可提前入住的空房。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '與房間看板搭配使用：時間線回答“誰在何時住哪間”，房間看板回答“每個房間現在是什麼狀態”。' },
    ],
  },

  // -------------------------------------------------------------------- 客人
  {
    slug: 'manage-guest-profiles',
    title: '管理客人資料',
    summary: '搜尋、編輯和維護賓客檔案——包括「資料不完整」標記和門戶帳戶轉移。',
    category: 'guests',
    keywords: ['賓客', '客人', '資料', '編輯賓客', '賓客歷史', '證件號碼', '門戶帳戶'],
    routePath: '/guest-relations/guests',
    requiredPermissions: ['guests:read', 'guests:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['create-a-booking', 'notifications-guest-support', 'guest-relations-hub'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: '開啟「賓客」', body: '「賓客」頁面列出所有賓客檔案，並帶有「資料不完整」和「缺少旅客類型」等分群篩選。搜尋可按姓名或聯絡方式縮小範圍。' },
          { title: '開啟一份資料', body: '一覽聯絡方式、身份欄位、預訂歷史和缺失資訊標記。' },
          { title: '更新有變化的欄位', body: '保持電話和電郵為最新——它們驅動收據、行銷活動和預入住流程。' },
          { title: '謹慎處理門戶帳戶', body: '「轉移賓客門戶帳戶」會把門戶登入移到另一份資料——只有在確定兩個帳戶屬於同一人時才使用。' },
        ],
      },
      { type: 'callout', tone: 'warning', title: '刪除賓客', body: '「刪除賓客」會移除該資料。存在預訂時請優先編輯而非刪除——歷史記錄對賬目和報表很重要。' },
      { type: 'callout', tone: 'tip', body: '「資料不完整」篩選會列出缺失欄位的檔案——當賓客「聯絡不上」時，先從這裡查起。' },
    ],
  },
  {
    slug: 'guest-relations-hub',
    title: '從「賓客關係」開始一天',
    summary: '賓客關係把今天到達、在住、離店和待跟進事項彙成一個看板——前檯的賓客側儀表板。',
    category: 'guests',
    keywords: ['賓客關係', '到達', '在住', '離店', '跟進', 'vip', '評論', '等待回覆'],
    routePath: '/guest-relations',
    requiredPermissions: ['guests:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['manage-guest-profiles', 'check-in-a-guest', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: '「賓客關係」是「賓客」分組下的首頁——一個按住宿階段組織當天賓客工作的看板，而不是一張扁平的檔案列表。' },
      {
        type: 'list',
        items: [
          '到達、在住和離店卡片呈現當天的人流——VIP 到達有專屬卡片。',
          '待回覆的評論和待跟進事項列出誰在等回應。',
          '「賓客」分組下還有賓客目錄、客服收件箱和忠誠計畫。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '每個班次從這裡開始，先處理等待中的跟進，再進入「預訂」或「時間軸」處理細節。' },
    ],
  },

  // ----------------------------------------------------------- 房間與庫存
  {
    slug: 'room-types-and-rooms',
    title: '設定房型和房間',
    summary: '房型定義客房是什麼、價格多少；客房是賓客實際入住的物理單元——兩者都在「客房設定」中管理。',
    category: 'rooms-inventory',
    keywords: ['房型', '新增房間', '新房間', '床型', '容納人數', '定價', '刪除房間'],
    routePath: '/room-config',
    requiredPermissions: ['rooms:create', 'rooms:update'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['daily-room-operations', 'online-inventory-grid', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: '客房設定是物業模型的所在。房型承載共享定義——名稱、床型、容納人數、定價和狀態——每間客房都是某房型下的編號單元。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「客房設定」', body: '在「行政管理」選單下找到它。' },
          { title: '建立或編輯房型', body: '依次完成各區塊——基本資訊（名稱、描述）、床型、容納人數（最大入住）、定價（每晚價格）和狀態。' },
          { title: '為房型新增客房', body: '每間客房有一個編號並歸屬某房型。客房預設沿用房型價格，但可設定自己的每晚價格覆蓋房型價。' },
          { title: '刪除前先檢查', body: '「刪除客房」移除一個單元；「刪除房型」移除整個定義——只在沒有任何依賴時可用。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '定價在這裡維護', body: '客人看到的房價來自房型的“定價”區塊。線上渠道的覆蓋價在“線上庫存”中單獨處理。' },
      { type: 'callout', tone: 'tip', body: '“最大入住人數”同時驅動預訂校驗和客房服務規劃——請如實填寫。' },
    ],
  },
  {
    slug: 'daily-room-operations',
    title: '日常房間運營',
    summary: '客房看板：即時房態、入住與退房、換房、維修中客房和逾期未退房。',
    category: 'rooms-inventory',
    keywords: ['房態', '已入住', '維修', '封房', '換房', '逾期退房', '髒房'],
    routePath: '/room-management',
    requiredPermissions: ['rooms:read', 'rooms:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['check-out-a-guest', 'housekeeping-maintenance', 'read-the-timeline'],
    blocks: [
      { type: 'paragraph', text: '「客房」是物業實體的營運看板——哪些客房已入住、哪些空閒、哪些在維修中、哪些退房已逾期。' },
      {
        type: 'list',
        items: [
          '「入住/退房」列一覽當天的進出動態。',
          '「逾期退房」列出本該離店的賓客——每個班次優先處理。',
          '「維修」狀態讓客房退出服務，直到狀態清除。',
          '「選擇新客房」可為賓客換房而不作廢預訂。',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: '從客房看板開始', body: '開啟「客房」檢視物業全貌。' },
          { title: '先處理逾期退房', body: '跟進或為每個逾期住宿辦理退房，讓客房得以清潔並重新銷售。' },
          { title: '如實標記維修中客房', body: '把維修中的客房設為「維修」，讓前檯知道它已退出服務。要停止某房型某天的線上銷售，請在「線上庫存」中覆蓋該單元格——線上開關與房態是兩回事。' },
          { title: '用「選擇新客房」換房', body: '需要換房時選擇新客房——預訂會跟隨賓客。' },
        ],
      },
      { type: 'callout', tone: 'warning', body: '維修中的客房仍需要維修工單來追蹤——見「房務與維修工單」。' },
    ],
  },
  {
    slug: 'online-inventory-grid',
    title: '控制線上庫存',
    summary: '在“線上庫存”網格上按房型按日期覆蓋可售量和價格——支援批次編輯。',
    category: 'rooms-inventory',
    keywords: ['線上庫存', '可售量', '線上售賣', '價格覆蓋', '關閉日期', '停售'],
    routePath: '/online-inventory',
    requiredPermissions: ['rooms:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['room-types-and-rooms', 'daily-room-operations', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: '“線上庫存”是一個按日期×房型的網格，控制客人在線上能訂到什麼。每個單元格可以持有覆蓋值——基礎值來自房型。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟“線上庫存”', body: '網格中房型為行、未來日期為列。' },
          { title: '編輯單個單元格', body: '點選單元格開啟編輯浮層，設定當天的值。' },
          { title: '或批次編輯一段區間', body: '選中多個單元格，然後用“批次編輯”面板把同一修改應用到整個選擇。' },
          { title: '儲存前先檢查', body: '修改會彙集到“檢查變更”中——在那裡確認，並用“僅覆蓋項”過濾器審計哪些與基礎配置不同。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '已修改和被覆蓋的單元格會有標記，您始終能區分基礎配置與一次性決定。' },
      { type: 'callout', tone: 'important', body: '要停止某天的線上銷售，請覆蓋該單元格——客房看板上的維修狀態並不會關閉線上單元格；除非客房真的停用，否則不要標記維修。' },
    ],
  },
  {
    slug: 'housekeeping-maintenance',
    title: '房務與維修工單',
    summary: '清潔任務和維修工單是「房務」裡兩條不同的佇列——一個管打掃，一個管修理。',
    category: 'rooms-inventory',
    keywords: ['房務', '客房服務', '清潔', '維修工單', '維修', '髒房', '回報維修', '指派給'],
    routePath: '/housekeeping',
    requiredPermissions: ['housekeeping:read', 'housekeeping:create'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['daily-room-operations', 'check-out-a-guest', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: '「房務」協調客房狀況：即時房態看板、用於清潔工作的「任務」佇列，以及用於維修工單的「維修」標籤頁。退房客房會自動生成清潔任務；其餘都要手動建立。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「房務」', body: '按樓層、優先順序或狀態篩選看板，聚焦本班次。' },
          { title: '為日常工作建立任務', body: '「新增任務」建立的是房務任務——指派給某人並帶排定日期的清潔與客房工作。' },
          { title: '把維修報成工單', body: '客房上的「回報維修」，或「維修」標籤頁上的「新增工單」，會開出一張帶客房、類別、優先順序和負責人的維修工單。該標籤頁需要 maintenance:read，開工單需要 maintenance:write——沒有這些權限的員工看不到這條路徑。' },
          { title: '處理佇列', body: '隨工作進展更新任務和工單狀態；處於「維修」狀態的客房在狀態清除前保持不可售。' },
          { title: '恢復客房可售', body: '工單解決並清潔後，在客房看板上將「維修」狀態恢復。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '先按優先順序篩選——客房在售賣時，漏水的空調比踢腳線劃痕更緊急。' },
    ],
  },

  // ----------------------------------------------------------- 支付與賬目
  {
    slug: 'refund-a-deposit',
    title: '退還押金',
    summary: '從預訂中退還客人押金——退款是退房的常規操作；撤銷退款則被有意限制。',
    category: 'payments-ledgers',
    keywords: ['退款', '押金', '退錢', '退還押金', '撤銷退款', '沒收'],
    routePath: '/bookings',
    requiredPermissions: ['payments:refund'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['check-out-a-guest', 'review-payment-approvals', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: '押金退款是退房時的前檯常規操作。退款操作位於預訂的「發票」內的押金區塊，需要 payments:refund 權限，前檯和經理都持有該權限。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟預訂的「發票」', body: '找到該住宿並開啟其發票——押金區塊顯示已收金額和仍持有的金額。' },
          { title: '選擇「退還押金」', body: '退款金額固定為持有餘額全額——員工不能自選金額。選擇退款方式，可附可選備註。' },
          { title: '或改為沒收', body: '「沒收押金」是獨立操作。可保留部分或全部持有餘額，並選擇原因——房間損壞、遺失物品、未結費用或其他。未保留的部分仍可退還。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '復原退款受限', body: '復原押金退款會重新開放該押金供再次退款，且需要 payments:manage——前檯無法自行迴圈退款/復原。確認前請再次核對。' },
      { type: 'callout', tone: 'tip', body: '如果看不到退款按鈕，說明您缺少 payments:refund——請找經理，而不是用手動調整繞過。' },
    ],
  },
  {
    slug: 'review-payment-approvals',
    title: '稽核付款核准',
    summary: '付款憑證在稽核佇列中等待——對照預訂核對收據，然後核准或拒絕。',
    category: 'payments-ledgers',
    keywords: ['付款核准', '收據', '付款憑證', '核准付款', '拒絕付款', '銀行轉賬'],
    routePath: '/payment-approvals',
    requiredPermissions: ['payments:approve'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['refund-a-deposit', 'company-ledgers', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: '「付款核准」列出已提交的付款憑證及其預訂、賓客、金額、方式和收據。每個條目在您處理後從「已提交」變為「已稽核」。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「付款核准」', body: '在「財務」選單下找到它。' },
          { title: '檢查憑證', body: '開啟條目並下載收據——對照預訂核對金額和參考號。' },
          { title: '核准或拒絕', body: '憑證相符時核准；不符時附理由拒絕。該決定會記錄到您的帳戶名下。' },
        ],
      },
      { type: 'callout', tone: 'warning', body: '拒絕線上付款會觸發發給客人的付款挽回郵件流程——只在憑證確實有誤時拒絕。' },
      { type: 'callout', tone: 'tip', body: '按提交時間從舊到新處理佇列：客人的入住可能正等著您的稽核。' },
    ],
  },
  {
    slug: 'company-ledgers',
    title: '處理公司賬',
    summary: '公司帳戶把掛賬住宿累積到賬上——核對餘額、付款期限和逾期帳戶。',
    category: 'payments-ledgers',
    keywords: ['賬目', '公司', '企業', '發票', '掛賬', '付款期限', '城市賬'],
    routePath: '/company-ledger',
    requiredPermissions: ['ledgers:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['review-payment-approvals', 'reports-and-metrics', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: '“公司賬”跟蹤掛到公司帳戶而非退房時支付的住宿。每本賬顯示公司、其預訂和滾動餘額。' },
      {
        type: 'list',
        items: [
          '公司掛賬預訂的客人在入住時可能觸發提示——賬單記到公司而非客人。',
          '付款期限定義公司結賬的時限；超期且仍有餘額的帳戶會被自動列出。',
          '「預訂」列表的「逾期餘額」檢視分為「一般」和「公司」——「公司」標籤顯示的是超過付款期限仍有餘額的公司掛賬住宿，不是所有公司住宿。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '公司超期未結屬於經理層面的溝通——系統負責標記，人來負責解決。' },
    ],
  },
  {
    slug: 'complimentary-nights-credits',
    title: '免費房晚與客人額度',
    summary: '把住宿標記為免費、轉換為額度，並按客人和房型管理免費房晚餘額。',
    category: 'payments-ledgers',
    keywords: ['免費', '免費房晚', '額度', '免費房額度', '贈送額度', '招待住宿'],
    routePath: '/complimentary',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['create-a-booking', 'company-ledgers', 'loyalty-program'],
    blocks: [
      { type: 'paragraph', text: '免費管理涵蓋免費住宿：把預訂標記為免費、把免費住宿轉換為客人額度、以及用額度訂房——全部按客人和房型跟蹤。' },
      {
        type: 'list',
        items: [
          '從預訂操作中把預訂標記為免費。',
          '把免費住宿轉換為額度——餘額記在客人名下，按房型限定。',
          '用額度訂房，消耗客人的免費房晚餘額。',
          '彙總檢視顯示未使用的免費和額度總量。',
        ],
      },
      { type: 'callout', tone: 'important', body: '取消免費狀態或刪除額度會改變客人應得的權益——即使許可權允許，也請把兩者都當作經理級決定。' },
    ],
  },

  // ---------------------------------------------------------- 價格與促銷
  {
    slug: 'promotions-vouchers',
    title: '管理促銷與優惠券',
    summary: '建立客人在公開“優惠”頁看到的促銷活動，以及可為預訂打折的優惠券。',
    category: 'rates-promotions',
    keywords: ['促銷', '優惠券', '折扣', '優惠碼', '優惠', '活動', '已暫停'],
    routePath: '/campaigns',
    requiredPermissions: ['promotions:manage', 'vouchers:manage'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'online-inventory-grid', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: '員工頁面名為「行銷活動」，位於「營收與行銷」下，用兩個標籤頁管理物業的優惠側——「行銷活動」（賓客在「優惠」頁看到的公開優惠，含績效）和「優惠券」（繫結到這些優惠的可兌換券）。' },
      {
        type: 'list',
        items: [
          '行銷活動定義優惠本身——名稱、時間和內容。狀態篩選為草稿、已排程、上線中、已暫停、已過期、已取消和已封存。',
          '優惠券是繫結到這些優惠的可兌換代碼——可直接發給賓客，或讓會員用忠誠積分領取。',
          '行銷郵件可以在「通訊」中直接引用行銷活動。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '行銷活動賣的是「線上庫存」所定價的東西——讓公開優惠、券規則和實際房價保持一致口徑。' },
    ],
  },
  {
    slug: 'loyalty-program',
    title: '瞭解忠誠計畫',
    summary: '忠誠計畫追蹤回頭客及其獎勵——在「賓客」下的「忠誠計畫」檢視。',
    category: 'guests',
    keywords: ['忠誠計畫', '獎勵', '積分', '回頭客', '會員'],
    routePath: '/loyalty',
    requiredPermissions: ['loyalty:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['complimentary-nights-credits', 'manage-guest-profiles', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: '「賓客」下的「忠誠計畫」展示回頭客計畫側的資訊：會員、積分、獎勵和待處理的兌換請求。持有 loyalty:manage 的員工負責管理獎勵與核准兌換；loyalty:read（或 analytics:read）即可檢視。' },
      { type: 'callout', tone: 'tip', body: '忠誠計畫、免費房晚和賓客額度是三個不同的槓桿——使用任何一個之前先檢視賓客資料，避免重複補償。' },
    ],
  },
  {
    slug: 'revenue-overview',
    title: '讀懂「營收」總覽',
    summary: '住宿日期維度的營收表現對比上一期間——KPI、每日趨勢，以及收入來自哪些通路。',
    category: 'rates-promotions',
    keywords: ['營收', 'adr', 'revpar', '通路組合', '淨營收', '績效', '趨勢'],
    routePath: '/revenue',
    requiredPermissions: ['revenue:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['reports-and-metrics', 'booking-channels', 'rates-and-rate-plans'],
    blocks: [
      { type: 'paragraph', text: '「營收」回答「錢的狀況如何？」，以您選擇的住宿日期範圍為準。KPI 列把該範圍與上一期間對比——營收、ADR、RevPAR、平均住宿天數、預訂數（含作廢率與爽約率）和直訂佔淨營收份額。' },
      {
        type: 'list',
        items: [
          '趨勢圖按住宿日期展示住房率與房晚——發現的是弱的夜晚，而不只是弱的總量。',
          '通路組合表按預訂通路拆分淨營收，讓 OTA 佣金體現在您實際留下的錢裡，而不只是開出的賬單。',
          '改變日期範圍會把每個數字重新對比到對應的上一期間。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '要看按房型、按公司、按通路的細分——「分析洞察」報表庫鑽得更深。「營收」是儀表板，「分析洞察」是下鑽。' },
    ],
  },
  {
    slug: 'rates-and-rate-plans',
    title: '管理房價與房價方案',
    summary: '「房價日曆」展示各房型每晚的最終售價；「房價方案」管理帶區間、調整和批次更新的具名價格組。',
    category: 'rates-promotions',
    keywords: ['房價', '房價方案', '價格日曆', '平日週末', '批次房價', '定價', '房價區間'],
    routePath: '/rates',
    requiredPermissions: ['revenue:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['revenue-overview', 'online-inventory-grid', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: '「房價」有兩個標籤頁。「房價日曆」展示各房型各日期的最終每晚售價——含線上覆蓋價和每格的銷售情況。「房價方案」管理具名方案（標準、季節、促銷、企業……），方案的房價區間在一個日期範圍內為房型定價；重疊時優先順序高的方案生效。' },
      {
        type: 'steps',
        steps: [
          { title: '先讀日曆', body: '翻動日期，檢查賓客為每種房型實際支付的價格——每格顯示有效房價、價格來源和當日住房率。' },
          { title: '在房價方案中編輯', body: '「新增方案」或現有方案的區間，在有效期起止之間為每種房型設定價格（或百分比/固定額調整），可選地受住宿天數和提前預訂天數約束。' },
          { title: '批次更新一段區間', body: '「批量房價」一次性為某方案在日期範圍內重新定價——重疊區間以最後寫入的為準。' },
        ],
      },
      { type: 'callout', tone: 'important', body: '房價方案是員工側的定價工具——賓客看到的公開線上價格仍來自房型加「線上庫存」覆蓋，覆蓋價優先於所有房價規則。' },
    ],
  },
  {
    slug: 'guest-segments',
    title: '建立賓客客群',
    summary: '按規則即時評估的賓客受眾——掛到郵件行銷活動上以收窄收件人範圍。',
    category: 'rates-promotions',
    keywords: ['客群', '受眾', '目標賓客', '行銷名單', '規則', '活動受眾'],
    routePath: '/segments',
    requiredPermissions: ['segments:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['email-campaigns-templates', 'manage-guest-profiles', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: '客群是動態的、按規則定義的受眾：一組對賓客資料（國家、住宿次數、標籤、會員級別……）的條件，在發送時即時評估——不是一份會過期的靜態名單。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「客群」', body: 'segments:read 可檢視客群庫；建立和編輯需要 segments:manage。' },
          { title: '建立客群', body: '「新增客群」把欄位、運算子和值組成行——「國家是其中之一……」「住宿次數至少……」——構成受眾定義。' },
          { title: '掛到行銷活動', body: '在「通訊 → 電子郵件行銷活動」選擇客群以收窄收件範圍——受眾計數會隨選擇即時更新。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '因為客群即時評估，同一個活動定義永遠發給今天符合條件的賓客——而不是名單儲存那天符合的人。' },
    ],
  },
  {
    slug: 'booking-channels',
    title: '管理預訂通路',
    summary: '預訂經由哪些通路到達——售價、佣金和通路矩陣。',
    category: 'rates-promotions',
    keywords: ['通路', 'ota', 'booking.com', 'agoda', 'expedia', '佣金', '上門', '直訂', '通路矩陣'],
    routePath: '/channels',
    requiredPermissions: ['channels:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['revenue-overview', 'online-inventory-grid', 'rates-and-rate-plans'],
    blocks: [
      { type: 'paragraph', text: '「通路」列出預訂可以到達的分銷管道——直訂、上門、電話和各 OTA——各自帶售價和佣金設定。「價格矩陣」標籤頁把通路與房型交叉排列，一眼看到並調整整個網格。' },
      {
        type: 'list',
        items: [
          '通路記錄攜帶該通路收取的佣金——這正是「營收」和「分析洞察」中淨營收與毛額不同的原因。',
          '建立和編輯通路需要 channels:write；啟用和刪除需要 channels:manage。',
          '預訂的通路決定它落入「分析洞察」中通路淨營收和 OTA 報表的哪個數字。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '新增房型後稽核一次矩陣——沒有通路列的房型按預設值定價，這通常不是您的本意。' },
    ],
  },

  // ------------------------------------------------------ 報表與夜審
  {
    slug: 'reports-and-metrics',
    title: '在「分析洞察」中讀報表',
    summary: '「分析洞察」報表庫：營運、財務、分析和會計報表——住房率、營收、日記帳、對帳單等。',
    category: 'reports-night-audit',
    keywords: ['報表', '分析洞察', '住房率', 'adr', 'revpar', '營收', '到達', '離店', '分析', '指標', '日記帳', '資產負債表', '班次報表', 'ota'],
    routePath: '/insights',
    requiredPermissions: ['analytics:read'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['run-night-audit', 'audit-log', 'revenue-overview'],
    blocks: [
      { type: 'paragraph', text: '「分析洞察」是報表庫——每份報表都透過同一個帶篩選的外殼呈現，分為四個家族。（舊的 /reports 地址會重新導向到這裡。）' },
      {
        type: 'list',
        items: [
          '營運——每日營運（到達、離店、在住、住房率）、住房率（含 ADR 和 RevPAR）、客房銷售、客房績效、班次報表和免費房晚。',
          '財務——營收、通路淨營收、OTA 佣金、OTA 月結單和付款狀態。',
          '分析——賓客統計：不重複賓客、新客與回頭客、國籍組成和頭部賓客。',
          '會計——總日記帳、分類日記帳、資產負債表和公司帳冊對帳單（按公司的對帳單含賬齡）。',
        ],
      },
      { type: 'heading', text: '最常被問到的兩個指標' },
      {
        type: 'list',
        items: [
          'ADR——每間已售房的平均成交價：客房收入 ÷ 已售房數。它回答「我們賣得夠不夠高」。',
          'RevPAR——收入攤到每間可售房（無論售出與否）：客房收入 ÷ 總房數。它回答「我們是否在以好價格填滿房間」。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '只看住房率會掩蓋打折，只看 ADR 會掩蓋空房——兩個指標要一起讀。' },
    ],
  },
  {
    slug: 'run-night-audit',
    title: '執行夜審',
    summary: '結束營業日：確認夜審，它會鎖定當天預訂禁止編輯並快照房間狀態。',
    category: 'reports-night-audit',
    keywords: ['夜審', '日結', '關賬', '鎖定預訂', '營業日期'],
    routePath: '/night-audit',
    requiredPermissions: ['night_audit:execute'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['reports-and-metrics', 'audit-log', 'hotel-settings'],
    blocks: [
      { type: 'paragraph', text: '夜審結束酒店的營業日。確認夜審會記錄執行人和時間、鎖定當天預訂禁止再編輯，並可快照房間狀態供報表使用。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「夜間稽核」', body: '在「財務」選單下找到它，並核對稽核日期。' },
          { title: '檢視本次執行的內容', body: '確認框會列出選項——包括鎖定預訂和記錄房間狀態快照。' },
          { title: '確認夜審', body: '執行會以您的帳戶和時間戳記錄；審計日誌會同步反映。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '鎖定是真實生效的', body: '夜審之後，當天的預訂會抵抗進一步編輯——請在當天真正結束時執行，或使用“飯店設定”中的自動執行選項。' },
      { type: 'callout', tone: 'tip', body: '營業日期遵循“飯店設定”中的酒店時區——夜審關閉的是那一天，而不是 UTC 零點。' },
    ],
  },
  {
    slug: 'audit-log',
    title: '使用審計日誌',
    summary: '誰改了什麼的只讀記錄——發現與昨天不一樣時第一站該看的地方。',
    category: 'reports-night-audit',
    keywords: ['審計日誌', '歷史', '誰修改', '活動', '軌跡'],
    routePath: '/audit-log',
    requiredPermissions: ['audit:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['page-missing-or-access-denied', 'run-night-audit', 'roles-and-permissions'],
    blocks: [
      { type: 'paragraph', text: '審計日誌記錄全系統的變更操作——預訂修改、設定編輯、角色調整、夜審執行。它在設計上就是隻讀的。' },
      {
        type: 'list',
        items: [
          '調查被改動的預訂或設定 → 先來這裡，再到處打聽。',
          '許可權審查 → 日誌顯示誰在何時授予了什麼。',
          '每條記錄都標明操作者和時間戳，跟進能找到具體的人而不是謎。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '與預訂時間線搭配使用：日誌記錄動作，時間線講述住宿的故事。' },
    ],
  },

  // ------------------------------------------------------------- 通訊
  {
    slug: 'email-campaigns-templates',
    title: '傳送營銷郵件與管理模板',
    summary: '構建可複用的郵件模板，然後向選定客人傳送活動——正式傳送前先測發。',
    category: 'communications',
    keywords: ['郵件', '活動', '模板', '公告', '營銷', '測發', '變數'],
    routePath: '/communications',
    requiredPermissions: ['communications:compose', 'communications:send'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-not-sending', 'promotions-vouchers', 'guest-deliveries'],
    blocks: [
      { type: 'paragraph', text: '「通訊」有三個標籤頁：「電子郵件行銷活動」（真正發送）、「範本」（帶變數的可複用內容）和「拒收名單」（絕不可傳送的地址）。' },
      {
        type: 'steps',
        steps: [
          { title: '建立或選擇範本', body: '範本承載主題和正文，變數用於填入賓客相關的值。' },
          { title: '傳送測試郵件', body: '「傳送測試郵件」先驗證格式和送達，發到您自己的地址，賓客還看不到。' },
          { title: '建立行銷活動', body: '選擇型別（例如「公告」）、收件人——可選地收窄到某個客群——主題和正文，可選地關聯一個行銷活動優惠。' },
          { title: '觀察傳送', body: '狀態標籤為草稿、已排程、執行中、已完成、已取消或失敗。啟用、已暫停和已結束不是郵件發送狀態——已暫停屬於「行銷活動」優惠頁，與上線中、已過期、已取消和已封存並列。「已傳送/失敗」計數和「最近錯誤」列會暴露問題。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '務必先發測試郵件——一個失效的變數在批次傳送時會很難堪。' },
    ],
  },
  {
    slug: 'notifications-guest-support',
    title: '通知與賓客支援收件箱',
    summary: '通知鈴鐺是給您的；「客服支援」收件箱是給賓客的——在那裡回覆他們的訊息。',
    category: 'communications',
    keywords: ['通知', '鈴鐺', '支援收件箱', '客服支援', '賓客訊息', '會話', '回覆', '認領'],
    routePath: '/support',
    requiredPermissions: ['support:read', 'support:write'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['email-not-sending', 'manage-guest-profiles', 'guest-deliveries'],
    blocks: [
      { type: 'paragraph', text: '存在三個不同的「通知」入口。頂欄的鈴鐺是員工通知中心——您的提醒、系統通知和發送分層。「賓客」下的「客服支援」是接收賓客門戶訊息的收件箱——那些需要員工回覆。「工具」下的「發送紀錄」是發往外部的賓客郵件發送紀錄。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「客服支援」', body: '會話列表顯示未關閉的賓客會話，包括未認領佇列。' },
          { title: '先認領再回覆', body: '未認領的會話必須先被認領才有人能回覆——由您自己（持有 support:assign 或 support:manage 時）或由持有該權限的人認領。只有寫權限是不夠的。' },
          { title: '閱讀並回覆', body: '開啟會話檢視賓客訊息並內聯回覆。會話一旦被指派，由其負責人（或 support:manage 持有者）回覆——而不是大家一起上。' },
          { title: '更新狀態', body: '關閉或更新會話狀態，讓佇列保持真實。' },
        ],
      },
      { type: 'callout', tone: 'info', title: '不是員工 IT 支援', body: '這個收件箱面向向酒店求助的賓客。關於管理門戶本身的幫助，請使用說明中心的「獲取更多幫助」指引。' },
      { type: 'callout', tone: 'tip', body: '支援收件箱可以在「飯店設定」中全物業關閉——如果整個模組消失了，那個開關是第一嫌疑人。' },
    ],
  },
  {
    slug: 'email-not-sending',
    title: '郵件發不出去',
    summary: '排查營銷與通知郵件的傳送失敗——多數原因都能在“最近錯誤”列或失敗的測發中看到。',
    category: 'communications',
    keywords: ['郵件失敗', 'smtp', '發不出', '郵件錯誤', '活動失敗', '最近錯誤'],
    routePath: '/communications',
    requiredPermissions: ['communications:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['email-campaigns-templates', 'notifications-guest-support', 'escalation'],
    blocks: [
      { type: 'paragraph', text: '郵件由後臺工作程序傳送，需要在伺服器上配置 SMTP 憑據。郵件停發時，證據幾乎都在“通訊”頁面本身。' },
      {
        type: 'steps',
        steps: [
          { title: '傳送測試郵件', body: '測發失敗證明問題出在基礎設施而非活動內容。' },
          { title: '看“最近錯誤”列', body: '活動傳送會按收件人記錄失敗原因——認證、連線和地址錯誤各自對應不同的修法。' },
          { title: '檢視“已傳送/失敗”計數', body: '部分失敗指向收件人地址；全部失敗指向 SMTP 配置。' },
          { title: '上報 SMTP 問題', body: '伺服器郵件設定屬於環境配置而非門戶內的介面——交給管理部署的人。' },
        ],
      },
      { type: 'callout', tone: 'important', body: '如果根本沒有 SMTP 設定，郵件工作程序就是關閉的——您的螢幕沒有故障，是這項能力從未被配置。' },
    ],
  },
  {
    slug: 'guest-deliveries',
    title: '檢視賓客郵件發送紀錄',
    summary: '發往賓客的郵件流——酒店發出或排隊的每條訊息，及其分層、狀態和最近錯誤。',
    category: 'communications',
    keywords: ['發送紀錄', '賓客訊息發送', '郵件流', '寄件匣', '已發郵件', '發送狀態', '排隊中', '被屏蔽', '交易通知', '行銷推廣'],
    routePath: '/notifications',
    requiredPermissions: ['communications:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'email-not-sending', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: '頁面標題是「賓客訊息發送」。側欄項目是「工具」下的「發送紀錄」，與頂欄鈴鐺分開，記錄發往賓客的郵件。酒店發出或排隊的每條訊息都帶脫敏收件人、型別、分層、狀態、嘗試次數、最近錯誤和發送時間。' },
      {
        type: 'list',
        items: [
          '「交易通知」與「行銷推廣」兩個分層，把收據和預訂郵件與行銷活動群發分開。',
          '狀態篩選可收窄到排隊中、傳送中、已傳送、失敗、被屏蔽或已取消——失敗行帶著最近錯誤。',
          '鈴鐺裡的發送標籤頁展示同一資料流的縮圖版；本頁才是完整的可篩選列表。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '賓客堅稱收據沒收到？先來這裡找到那一行——已傳送、失敗還是被屏蔽，勝過瞎猜。' },
    ],
  },

  // -------------------------------------------------------------- 員工與許可權
  {
    slug: 'add-manage-staff',
    title: '新增與管理員工帳戶',
    summary: '為同事建立登入、分配角色，並在“訪問控制”中編輯或移除帳戶。',
    category: 'staff-access',
    keywords: ['新增使用者', '新員工', '員工帳戶', '建立使用者', '刪除使用者', '員工登入'],
    routePath: '/rbac',
    requiredPermissions: ['users:create', 'users:update'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: '開啟「存取控制」', body: '在「行政管理」選單下找到它，然後開啟「使用者」標籤頁。' },
          { title: '選擇“新增使用者”', body: '“建立新使用者”對話方塊收集新員工的帳戶資訊。' },
          { title: '分配角色', body: '角色決定這個人能看什麼、能做什麼——前臺和經理看到的是不同的門戶。可在同一流程中分配，也可事後在使用者行上調整。' },
          { title: '之後編輯或移除', body: '“編輯使用者”更新資訊；員工離職時“刪除使用者”會移除整個帳戶。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '先配角色再首次登入', body: '沒有角色的使用者幾乎什麼都看不到——如果同事反饋門戶是空的，先檢查角色分配。' },
      { type: 'callout', tone: 'tip', body: '優先調整角色而不是建立一次性帳戶；無論哪種方式，審計日誌都會記錄每次變更。' },
    ],
  },
  {
    slug: 'roles-and-permissions',
    title: '角色與許可權',
    summary: '角色打包許可權；許可權控制頁面和操作。*:manage 許可權隱含其領域內的其他許可權。',
    category: 'staff-access',
    keywords: ['角色', '許可權', 'rbac', '訪問控制', 'manage 許可權', '前臺 經理'],
    routePath: '/rbac',
    requiredPermissions: ['roles:read', 'roles:manage'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['add-manage-staff', 'page-missing-or-access-denied', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: '「存取控制」有兩個標籤頁：「角色與權限」——如前檯、經理這樣的命名權限包，每個角色內按領域分組管理單項權限——和「使用者」，即持有這些角色的員工帳戶。' },
      {
        type: 'list',
        items: [
          '許可權形如 資源:操作——例如 bookings:create 或 payments:refund。',
          '資源:manage 許可權隱含該資源的所有操作。',
          '路由策略把頁面對映到許可權，這就是不同使用者選單不同的原因。',
          '系統角色自帶合理的授權；特殊配置可以建立自定義角色。',
        ],
      },
      { type: 'callout', tone: 'warning', body: '修改系統角色會影響所有持有該角色的人——當只有一個人需要不同的許可權時，請新建角色。' },
      { type: 'callout', tone: 'tip', body: '權限在「角色與權限」標籤頁的每個角色內按領域分組——展開一個類別即可看到角色究竟能做什麼。' },
    ],
  },
  {
    slug: 'ekyc-reviews',
    title: '稽核 eKYC 提交',
    summary: '身份核驗工作在 eKYC 管理佇列中進行——被指派的稽核員按風險級別處理提交。',
    category: 'staff-access',
    keywords: ['ekyc', '身份', '核驗', 'kyc', '稽核員', '合規'],
    routePath: '/ekyc-admin',
    requiredPermissions: ['ekyc:review'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['roles-and-permissions', 'audit-log', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: '“eKYC 管理”是電子身份核驗的稽核佇列。專門角色——eKYC 稽核員、高階稽核員和合規管理員——處理提交，高風險個案升級到高階稽核。' },
      {
        type: 'list',
        items: [
          '稽核員處理指派給自己的申請；高階稽核員負責升級和高風險批准。',
          '敏感操作（檢視證件、檢視供應商資料）有獨立許可權並會被記錄。',
          '如果看不到該模組，說明您沒有任何 eKYC 角色——這是設計而非故障。',
        ],
      },
      { type: 'callout', tone: 'info', body: 'eKYC 許可權被有意細分——只申請您的稽核級別所需的操作。' },
    ],
  },

  // ------------------------------------------------------------- 設定與資料
  {
    slug: 'hotel-settings',
    title: '配置飯店設定',
    summary: '物業資料、入住/退房時間、時區、稅費、押金、報表字型和功能開關——其他介面繼承的預設值。',
    category: 'settings-data',
    keywords: ['設定', '酒店名稱', '時區', '入住時間', '稅', '押金', '旅遊稅', '服務稅', '配置'],
    routePath: '/settings',
    requiredPermissions: ['settings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['run-night-audit', 'room-types-and-rooms', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: '“飯店設定”儲存其他介面繼承的物業級預設值：名稱與聯絡方式、入住/退房時間、時區、押金金額、服務稅和旅遊稅率、付款期限、報表排版以及功能開關。' },
      {
        type: 'list',
        items: [
          '入住與退房時間驅動提前入住提示和客房服務目標。',
          '時區定義營業日期——報表、夜審和“今天”都跟隨它。',
          '押金金額、服務稅和旅遊稅計入預訂總額；外籍客人需付旅遊稅。',
          '支援和客人取消開關可整體啟停對應功能。',
          '報表字型設定決定列印輸出的版式。',
        ],
      },
      { type: 'callout', tone: 'important', title: '未付款保留視窗也在這裡', body: '“未付款保留釋放小時數”控制 pending_payment 預訂佔用房間的時長（預設 24；0 為停用）。' },
      { type: 'callout', tone: 'warning', body: '設定儲存後立即生效——錯誤的稅率或時區會影響每一筆新預訂。' },
    ],
  },
  {
    slug: 'import-export-data',
    title: '匯入與匯出資料',
    summary: '「資料轉移」負責備份的進出——四個匯出檔位、先預覽，以及在任何特權或破壞性操作前重新驗證身份。',
    category: 'settings-data',
    keywords: ['匯入', '匯出', '備份', '恢復', '資料轉移', '遷移', '資料庫', '系統備份', '密碼片語'],
    routePath: '/data-transfer',
    requiredPermissions: ['data_transfer:view'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['hotel-settings', 'audit-log', 'escalation'],
    blocks: [
      { type: 'paragraph', text: '“資料轉移”負責酒店資料的遷入遷出——用於備份、恢復和遷移。您能做什麼取決於資料轉移許可權：檢視頁面、匯出和匯入各自需要獨立授權，涉及機密或破壞性的操作還會要求您重新輸入密碼（如已啟用，還需驗證器驗證碼）。' },
      {
        type: 'steps',
        steps: [
          { title: '開啟「資料轉移」', body: '需要 data_transfer:view。「匯出」標籤頁有四個檔位：標準匯出（僅營運資料）、完整匯出（全部可轉移業務資料）、移轉備份（完整資料集加關聯中繼資料）和完整系統備份（僅限超級管理員）。' },
          { title: '匯出', body: '標準檔需要 data_transfer:export。完整匯出和移轉備份攜帶機密的賓客、支付和賬目資料——需要 data_transfer:export_sensitive 並重新驗證身份。完整系統備份更進一步：使用者帳戶、密碼雜湊、工作階段、RBAC 授權、eKYC 紀錄和稽核歷史——僅限超級管理員，且檔案一律用您提供的密碼片語加密。' },
          { title: '檢查匯入預覽', body: '上傳備份檔案（data_transfer:import）。預覽顯示檔案內容、在包含敏感資料時警告，並指明您仍缺少的許可權。' },
          { title: '確認匯入', body: '“合併”只新增、不動現有行；“更新”式衝突處理需要 data_transfer:override。完整恢復會先刪除現有資料，需要 data_transfer:restore 並重新驗證身份。只在您信任的檔案上繼續。' },
          { title: '檢視“轉移歷史”', body: '過去的匯入、匯出和提權嘗試都連同操作者一起列出——與審計日誌記錄的是同一批行。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '設計上即具破壞性', body: '“先刪除所有現有資料”是字面意思——完整恢復會替換整個資料庫。請與管理員確認檔案和時機。' },
      { type: 'callout', tone: 'tip', title: '機密只留在最高檔', body: '標準、完整和移轉備份絕不含憑據——密碼、工作階段、權杖或身份核驗證據。完整系統備份有意包含它們，以便在全新安裝上重建登入；這正是它一律加密、憑密碼片語解鎖且僅限超級管理員的原因。請妥善保管密碼片語——遺失後無法找回。' },
    ],
  },
  {
    slug: 'system-health-and-jobs',
    title: '系統健康度與工作',
    summary: '「行政管理」下照看平台本身的兩個面板——服務健康，以及讓酒店正常運轉的背景工作。',
    category: 'settings-data',
    keywords: ['系統健康度', '系統健康', '工作', '背景工作', '計劃任務', '排程', '服務狀態', '夜審工作', '執行時間'],
    routePath: '/system-health',
    requiredPermissions: ['settings:manage'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['hotel-settings', 'audit-log', 'run-night-audit'],
    blocks: [
      { type: 'paragraph', text: '「行政管理」下有兩個頁面照看的是平台而非物業。「系統健康度」回報部署的運作狀況——服務狀態、資料庫和 worker 健康。「工作」列出伺服器按排程執行的背景工作——夜間稽核、未付款保留釋放、付款收據、通訊發送——以及最近一次執行狀態。' },
      {
        type: 'list',
        items: [
          '多個頁面同時出問題時先看「系統健康度」——它能把應用問題和資料問題分開。',
          '「工作」顯示計劃工作是否在跑——停滯的夜審或郵件工作能解釋「它自己停了」這類回報。',
          '兩者都屬於 settings:manage 的領地——如果看不到，那是管理員的檢視。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '一行失敗的工作加上稽核紀錄通常就能指名原因——上報時兩個都帶上。' },
    ],
  },

  // ------------------------------------------------------------- 故障排查
  {
    slug: 'cant-find-a-booking',
    title: '找不到預訂？',
    summary: '按清單排查：搜尋詞、篩選器，以及讓預訂從日常檢視消失的兩種狀態（已作廢、已釋放）。',
    category: 'troubleshooting',
    keywords: ['預訂丟失', '預訂缺失', '找不到', '無結果', '消失了'],
    routePath: '/bookings',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['find-a-reservation', 'void-reactivate-release', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          '在 ⌘K 中試預訂編號——BK- 編號和客人姓名都能搜。',
          '清除「預訂」列表上的篩選——遺留的搜尋詞、「抵達」或「逾期餘額」等檢視標籤、日期或月份篩選是常見元兇。',
          '檢查日期：住宿可能在您檢視的範圍之外。',
          '詢問預訂是否已被作廢——已作廢的住宿會從日常檢視消失。',
          '檢查是否為已釋放的未付款保留——始終未付款的線上預訂會自動釋放回庫存。',
          '確認您能看到“預訂”模組本身——模組缺失是許可權問題，不是搜尋問題。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '預訂時間線和審計日誌在作廢後依然保留——只要預訂存在過，它的記錄就還在。' },
    ],
  },
  {
    slug: 'payment-problems',
    title: '支付問題',
    summary: '線上付款失敗、審批卡住和退款報錯——把症狀對應到正確的佇列。',
    category: 'troubleshooting',
    keywords: ['付款失敗', '支付錯誤', '被拒', '挽回付款', '審批卡住', '退款錯誤'],
    routePath: '/payment-approvals',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['refund-a-deposit', 'review-payment-approvals', 'email-not-sending'],
    blocks: [
      {
        type: 'list',
        items: [
          '客人線上付款失敗 → 付款挽回郵件可以讓客人通過安全連結重試——在斷定錢丟了之前先檢視預訂狀態。',
          '付款憑證在等待 → 它會留在“付款審批”中直到有人稽核；客人看到的是“已提交”而非“已確認”。',
          '退款按鈕缺失 → 您需要 payments:refund；撤銷退款需要 payments:manage。',
          '預訂卡在 pending_payment → 它是未付款保留；會自動釋放或可手動釋放。',
        ],
      },
      { type: 'callout', tone: 'warning', body: '絕不要通過編輯預訂來“修好”卡住的付款——走審批佇列或上報；賬目和審計軌跡需要真實的理由。' },
    ],
  },
  {
    slug: 'session-and-stale-data',
    title: '會話與過期資料問題',
    summary: '當介面看起來過時或會話行為異常時——重新整理順序、空閒過期和營業日期陷阱。',
    category: 'troubleshooting',
    keywords: ['資料過期', '重新整理', '會話過期', '被退出', '日期不對', '時區'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['sign-in-and-security', 'hotel-settings', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          '重新整理頁面——長時間空閒後會話令牌會自動續期；介面過時只需重新載入。',
          '會話狀態不一致時登出並重新登入——「登出」圖示在頂欄最右端（手機寬度的螢幕不顯示）。',
          '日期看起來不對 → 營業日期遵循“飯店設定”中的酒店時區，而不是您筆記本的時鐘。',
          '設定改了但沒生效 → 有些變更只對新活動生效，不追溯。',
          '另一臺裝置上看起來不同 → 主題和語言按工作站記憶，許可權按帳戶生效。',
        ],
      },
      { type: 'callout', tone: 'info', body: '反覆被退出不是故障——訪問令牌有意設計為短時效，並會在後臺靜默續期。' },
    ],
  },
  {
    slug: 'escalation',
    title: '獲取更多幫助',
    summary: '當幫助中心解決不了時該怎麼辦——找誰問、帶上什麼。',
    category: 'troubleshooting',
    keywords: ['聯絡', '上報', '經理', '管理員', '更多幫助', '支援'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['page-missing-or-access-denied', 'payment-problems', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: '幫助中心覆蓋門戶的使用方法。帳戶訪問、許可權變更以及任何疑似缺陷的問題，請沿物業自身的鏈路逐級上報。' },
      {
        type: 'steps',
        steps: [
          { title: '詢問您的管理員或經理', body: '許可權、角色和設定變更歸他們管——帶上頁面名稱和您預期看到的內容。' },
          { title: '帶上證據', body: '審計日誌記錄、預訂編號、活動的“最近錯誤”文本——一條具體記錄勝過對症狀的描述。' },
          { title: '客人側的問題', body: '如果是客人在反映問題，先到“支援”收件箱查詢現有會話，而不是另起一條並行線索。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '截圖有幫助，但準確的錯誤文本和發生時間更有用——兩者都在應用自己的記錄裡。' },
    ],
  },
];
