import type { HelpArticle } from '../types';

/**
 * 中文帮助中心文章（简体中文，镜像 articles.en.ts 的 slug 与区块结构；
 * content.test.ts 负责校验结构一致性）。
 *
 * 以下每个流程都已在管理端口中核实：页面名称与导航注册表一致、按钮标签与
 * 渲染 UI 一致、权限标识与 seed.sql 一致。界面变更时，请同步更新对应文章并
 * 更新 `lastReviewed`。
 */
export const ARTICLES_ZH: HelpArticle[] = [
  // ---------------------------------------------------------- 入门
  {
    slug: 'sign-in-and-security',
    title: '登录并保护您的账户',
    summary: '登录、添加通行密钥或双重验证，并在共用工作站上安全退出。',
    category: 'getting-started',
    keywords: ['登录', '密码', '通行密钥', '2fa', '双重验证', '退出', '共用电脑'],
    routePath: '/profile',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['getting-around-admin-portal', 'page-missing-or-access-denied'],
    blocks: [
      { type: 'paragraph', text: '员工账户由管理员创建。获得凭据后，从登录页登录——门户会恢复您最初尝试打开的页面。' },
      {
        type: 'steps',
        steps: [
          { title: '打开登录页', body: '输入用户名和密码。如果会话已过期，系统会先带您回到此页，然后再跳转到您想去的页面。' },
          { title: '按提示添加通行密钥', body: '首次登录时，系统可能会要求您注册通行密钥（指纹、人脸或设备 PIN）。通行密钥是最快、最安全的再次登录方式——您可以暂时忽略提示，稍后在个人资料中设置。' },
          { title: '注册双重验证', body: '如果您的角色有此要求，系统会引导您完成 2FA 注册。请准备好您的验证器应用。' },
          { title: '班次结束时退出登录', body: '点击顶栏最右端、账户头像旁的“退出登录”图标。在共用的前台工作站上，这不是可选项——下一位使用者会继承您未退出的会话。' },
        ],
      },
      { type: 'callout', tone: 'warning', title: '共用工作站', body: '切勿在前台留下无人看管的已登录会话。退出登录会清除内存中的访问令牌。手机宽度的屏幕不显示“退出登录”图标——请改用平板或桌面结束会话。' },
      { type: 'callout', tone: 'tip', body: '如果页面显示“访问被拒绝”，通常只是您的角色不包含该页面——在怀疑系统故障之前，请先查看“为什么看不到某个页面？”。' },
    ],
  },
  {
    slug: 'getting-around-admin-portal',
    title: '熟悉管理门户',
    summary: '导航分组、命令面板、通知、语言与主题——每个班次都会用到的五个控件。',
    category: 'getting-started',
    keywords: ['导航', '菜单', '命令面板', '搜索', '主题', '语言', '深色模式', '马来语'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['sign-in-and-security', 'cant-find-a-booking'],
    blocks: [
      { type: 'paragraph', text: '门户由两个区域承载。侧边栏是酒店名称、“新建预订”按钮和模块导航，分为“概览”、“前厅”、“客人”、“收益与营销”、“财务”、“经营分析”、“系统管理”和“工具”八组。顶栏是搜索、通知铃铛、语言、账户菜单和“退出登录”图标。' },
      {
        type: 'list',
        items: [
          '“前厅”覆盖前台的日常工作——预订管理、时间轴、客房和客房服务；“客人”包含宾客关系、客人目录、客服和会员忠诚度。',
          '“收益与营销”是收益、房价、营销活动、客群细分、渠道、通信管理和线上库存；“财务”是公司台账、支付审批、夜审和免费房晚。',
          '“系统管理”是访问控制、eKYC 管理、酒店设置、客房配置、审计日志、数据迁移、系统健康和后台任务；“工具”是通知与本帮助中心。',
          '在手机上，导航移到屏幕底栏——几个主要目的地加“更多”，点开后列出您能看到的其余全部模块，语言列表在其下方。没有侧边抽屉，也没有页头菜单按钮。',
          '只有您的角色可见的分组才会出现——同一个屏幕上，两位员工的侧边栏可能完全不同。',
        ],
      },
      { type: 'heading', text: '用 ⌘K 找到任何东西' },
      { type: 'paragraph', text: '按 ⌘K（Windows 上为 Ctrl+K）或点击搜索栏——手机上为搜索图标——打开命令面板。它可以搜索预订、客人、账条、房间、页面——以及帮助文章。方向键浏览结果，回车打开所选，Esc 关闭。输入 / 可运行“新建预订”等快捷操作。' },
      { type: 'heading', text: '语言与主题' },
      { type: 'paragraph', text: '地球图标可在 English、Bahasa Melayu、简体中文和繁體中文之间即时切换——无需刷新；在手机上它位于“更多”面板底部。酒店设置 → 外观只有浅色和深色。已保存的夜间模式会按深色打开，选择按这台工作站记住。' },
      { type: 'callout', tone: 'tip', body: '命令面板会记住您最近去过的六个目的地，重复跳转只需按两下键盘。' },
    ],
  },
  {
    slug: 'page-missing-or-access-denied',
    title: '为什么看不到某个页面？',
    summary: '页面根据您的角色和权限显示——菜单项缺失或“访问被拒绝”页面几乎都是权限决定，而非故障。',
    category: 'getting-started',
    keywords: ['访问被拒绝', '403', '权限', '菜单缺失', '角色', '看不到', '页面缺失'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security'],
    blocks: [
      { type: 'paragraph', text: '管理门户中的每个模块都受路由访问策略保护。您的导航只显示角色和权限允许的目的地——在同一屏幕上，两位员工可能看到完全不同的菜单。' },
      {
        type: 'list',
        items: [
          '菜单项缺失 → 路由策略排除了您的角色，或您缺少相应权限。',
          '打开链接后看到“访问被拒绝”（403）→ 您可以访问门户，但不能访问该模块。',
          '昨天能用今天不行 → 您的角色或路由策略发生了变化。请查看审计日志或询问管理员。',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: '确认模块存在', body: '询问同事是否能看到该页面。如果没人能看到，可能是配置问题而非权限问题。' },
          { title: '询问管理员', body: '权限在“系统管理 → 访问控制”中授予：“用户”标签页分配角色，“角色与权限”标签页编辑角色允许的操作。只有管理员可以更改。' },
        ],
      },
      { type: 'callout', tone: 'info', body: '*:manage 权限隐含该资源的所有其他操作——例如 bookings:manage 涵盖创建、读取、更新和删除。' },
    ],
  },
  {
    slug: 'front-desk-overview',
    title: '在“概览”开始您的班次',
    summary: '“概览”是门户首页——前台的当日到店、离店和房态，或经理的分析仪表盘。',
    category: 'getting-started',
    keywords: ['概览', '仪表盘', '首页', '前台', '今日到店', '离店', '房态'],
    routePath: '/',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['getting-around-admin-portal', 'daily-room-operations', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: '“概览”是门户打开后落地的页面。显示什么取决于您的角色：前台员工看到的是运营当日看板——到店、离店和实时房态快照；经理和管理员看到的是分析仪表盘。' },
      {
        type: 'list',
        items: [
          '前台看板呈现当天的进出动态——待入住的到店、待退房的离店、需要留意的房间——以及新预订到达时的滚动条。',
          '管理仪表盘汇总收入、入住率和趋势分析，而不是前台的工作队列。',
          '看板上的每一项都能继续跳转——一行即打开对应预订或房间，所以“概览”是起点而不是终点。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '从这里开始班次，先清到店和离店，再让“预订管理”或房间看板接手剩下的时间。' },
    ],
  },

  // ------------------------------------------------------------------ 预订
  {
    slug: 'create-a-booking',
    title: '创建预订',
    summary: '通过“新建预订”按钮创建预订——在一个屏幕内选择日期、房间、房价和支付方式。',
    category: 'bookings',
    keywords: ['预订', '新建预订', '上门客', '电话预订', '手动预订'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:create'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['check-in-a-guest', 'find-a-reservation', 'void-reactivate-release'],
    blocks: [
      { type: 'paragraph', text: '上门、电话和回头客预订都通过同一个“新建预订”界面创建。它把住宿日期、选房、客人资料和房价/支付合并为单一流程。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“新建预订”', body: '使用侧边栏顶部的“新建预订”按钮，或“预订管理”页面上的“新建预订”按钮。在手机上它也在快捷操作面板中。' },
          { title: '选择住宿日期和模式', body: '选择入住和退房日期。预订模式选择器会按预订类型调整流程。' },
          { title: '选择房间', body: '先选房型，再选具体房间。系统只提供整个期间都空闲的房间。' },
          { title: '填写客人资料', body: '搜索现有客人或录入新客人——姓名、联系方式和国籍字段会影响税费和身份核验。' },
          { title: '设置房价和支付', body: '核对每晚价格和总价，选择支付方式和押金方式，然后确认。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '客人国籍中的“本地/外籍”决定旅游税是否适用——它在客人区域选择，而不是在支付时。' },
      { type: 'callout', tone: 'important', title: '未付款的线上保留', body: '停留在 pending_payment 状态的预订属于保留房。它们会在“酒店设置”中配置的时长（未付款保留释放小时数）后自动释放，也可以提前手动释放。' },
    ],
  },
  {
    slug: 'find-a-reservation',
    title: '查找预订',
    summary: '通过编号、客人姓名或房间查找任意预订——使用“预订”列表或 ⌘K 面板。',
    category: 'bookings',
    keywords: ['搜索预订', '查找预订', '预订丢失', '预订编号', 'bk-', '查询'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['cant-find-a-booking', 'check-in-a-guest', 'create-a-booking'],
    blocks: [
      { type: 'paragraph', text: '取决于您掌握的信息，有两条快速路径：想浏览和筛选时用“预订”列表；知道预订编号或客人时用 ⌘K 面板。' },
      {
        type: 'steps',
        steps: [
          { title: '打开 ⌘K 面板', body: '按 ⌘K 或点击搜索栏。选择“预订”范围标签以限定结果。' },
          { title: '按编号或客人搜索', body: '输入预订编号（例如 BK-…）或客人姓名。选择结果会打开已过滤到该预订的“预订”页面。' },
          { title: '或者筛选“预订”列表', body: '在“预订管理”页面，搜索框可匹配预订、客人、发票和房号，视图标签（全部、抵店、在住、未来预订、逾期未结）以及支付方式、线上渠道、日期和月份筛选都能在不离开页面的情况下缩小范围。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '把预订编号粘贴到面板是最快的查找方式——结果会直接深链到过滤后的列表。' },
      { type: 'callout', tone: 'info', title: '如果仍然找不到', body: '已作废的预订和已释放的未付款保留不会出现在日常视图中。完整排查清单见“找不到预订？”。' },
    ],
  },
  {
    slug: 'check-in-a-guest',
    title: '为客人办理入住',
    summary: '在入住当天标记到店——已确认和待确认的预订都符合条件；提前入住会被提示而非阻止。',
    category: 'bookings',
    keywords: ['到店', '入住', '前台', '提前入住', '客人到达'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['check-out-a-guest', 'find-a-reservation', 'housekeeping-maintenance'],
    blocks: [
      { type: 'paragraph', text: '当预订状态为已确认或待确认且到达入住日期后，即可办理入住。“入住”操作位于预订本身。' },
      {
        type: 'steps',
        steps: [
          { title: '打开预订', body: '通过 ⌘K 或“预订”列表找到它并打开详情。' },
          { title: '选择“入住”', body: '该操作只在预订符合条件时出现——状态为已确认或待确认，且今天不早于入住日期。' },
          { title: '查看入住提示', body: '通常由公司结算的客人可能会在继续前触发提示——阅读后确认。' },
          { title: '确认', body: '预订状态变为 checked_in，房间在“房间”和“时间线”上显示为已入住。' },
        ],
      },
      { type: 'callout', tone: 'info', title: '提前入住', body: '早于配置的入住时间（酒店设置 → 入住时间，默认 15:00）到达会弹出提前入住提示，而不是硬性阻止。' },
      { type: 'callout', tone: 'warning', body: '在到达日期之前不会出现“入住”按钮——这是有意设计。如果客人提前一天到达，请先修改预订日期。' },
    ],
  },
  {
    slug: 'check-out-a-guest',
    title: '为客人办理退房',
    summary: '从预订或房间看板结束住宿——只有已入住的预订才能退房。',
    category: 'bookings',
    keywords: ['离店', '退房', '离开', '结账', '逾期退房'],
    routePath: '/room-management',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['check-in-a-guest', 'refund-a-deposit', 'housekeeping-maintenance'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: '打开预订或房间看板', body: '退房可从预订操作中进行；房间看板会显示“逾期退房”，确保无一遗漏。' },
          { title: '选择“退房”', body: '该操作只在预订状态为 checked_in 时出现。' },
          { title: '结清住宿', body: '超过退房日期且仍有余额未付的预订——包括超过付款期限的公司挂账住宿——会被列出，以便您在离店前或离店时收款或安排付款。' },
          { title: '把房间送回清洁', body: '退房后，房间回到客房服务队列并自动创建清洁任务——房间本身不会自动开维修工单。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '如果收过押金，请在退房时退还——见“退还押金”。' },
      { type: 'callout', tone: 'warning', body: '预订必须处于 checked_in 状态才能退房。如果状态看起来不对，请查看预订时间线了解发生了什么。' },
    ],
  },
  {
    slug: 'void-reactivate-release',
    title: '作废、恢复或释放预订',
    summary: '作废即取消预订，恢复可还原已作废的预订，释放可腾出未付款线上保留——三个操作，三套规则。',
    category: 'bookings',
    keywords: ['取消', '作废', '恢复', '释放', '未付款保留', '未付款', '爽约'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['create-a-booking', 'refund-a-deposit', 'find-a-reservation'],
    blocks: [
      { type: 'paragraph', text: '每个操作针对不同情形，且只在预订符合条件时出现——如果按钮缺失，原因就在预订状态上。' },
      {
        type: 'list',
        items: [
          '作废——取消预订。任何未作废的预订都可使用，用于处理取消。',
          '恢复——把已作废的预订还原。只在已作废的预订上提供。',
          '释放——腾出由未付款线上预订占用的房间。只在状态为 pending_payment 且未收任何款项时提供。',
        ],
      },
      { type: 'heading', text: '未付款保留会自动释放' },
      { type: 'paragraph', text: '后台任务会在“酒店设置”配置的时长（未付款保留释放小时数——默认 24，0 为禁用）后自动释放未付款保留。手动释放用于更快腾出房间。' },
      { type: 'callout', tone: 'important', title: '已收款？', body: '一旦存在任何付款，释放就被有意禁用——后端同样强制此规则。请作废预订并向客人退款。' },
      { type: 'callout', tone: 'tip', body: '这些状态变化都会写入预订时间线和审计日志——您始终可以查看谁在何时做了什么。' },
    ],
  },
  {
    slug: 'read-the-timeline',
    title: '读懂预订时间线',
    summary: '按房间和日期查看谁将到达、在住或离店——一眼掌握入住率的最快方式。',
    category: 'bookings',
    keywords: ['时间线', '日历', '入住率视图', '房间调度', '到店离店'],
    routePath: '/timeline',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['daily-room-operations', 'check-in-a-guest', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: '时间线把预订铺在房间和日期的网格上，让到店、在住和离店像地图一样呈现，而不是列表。它是规划换房和发现空档的正确界面。' },
      {
        type: 'list',
        items: [
          '几秒内扫完一周的入住情况——接待上门客之前很有用。',
          '围绕同一房间的紧挨预订规划换房。',
          '不用逐个打开预订就能找到可提前入住的空房。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '与房间看板搭配使用：时间线回答“谁在何时住哪间”，房间看板回答“每个房间现在是什么状态”。' },
    ],
  },

  // -------------------------------------------------------------------- 客人
  {
    slug: 'manage-guest-profiles',
    title: '管理客人资料',
    summary: '搜索、编辑和维护客人档案——包括“资料不全”标记和门户账户转移。',
    category: 'guests',
    keywords: ['客人', '资料', '编辑客人', '客人历史', '证件号码', '门户账户', '资料不全'],
    routePath: '/guest-relations/guests',
    requiredPermissions: ['guests:read', 'guests:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['create-a-booking', 'notifications-guest-support', 'guest-relations-hub'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: '打开“客人”', body: '“客人”页面列出所有客人档案。搜索可按姓名或联系方式缩小范围。' },
          { title: '打开一份资料', body: '一览联系方式、身份字段、预订历史以及“资料不全”等提示。' },
          { title: '更新有变化的字段', body: '保持电话和邮箱为最新——它们驱动收据、营销活动和预入住流程。' },
          { title: '谨慎处理门户账户', body: '“转移客人门户账户”会把门户登录移到另一份资料——只有在确定两个账户属于同一人时才使用。' },
        ],
      },
      { type: 'callout', tone: 'warning', title: '删除客人', body: '“删除客人”会移除该资料。存在预订时请优先编辑而非删除——历史记录对账目和报表很重要。' },
      { type: 'callout', tone: 'tip', body: '“资料不全”标签会标出存在缺口的档案（如电话），这些字段会阻塞通知等流程——当客人“联系不上”时，先从这里查起。' },
    ],
  },
  {
    slug: 'guest-relations-hub',
    title: '用好“宾客关系”看板',
    summary: '一块看板承载对客工作——到店、在住、离店、VIP 到店、跟进、待处理客服和点评。',
    category: 'guests',
    keywords: ['宾客关系', '到店', '离店', '跟进', 'vip', '点评', '客人 360'],
    routePath: '/guest-relations',
    requiredPermissions: ['guests:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['manage-guest-profiles', 'check-in-a-guest', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: '“宾客关系”是对客工作队列：一条统计栏加每个队列各一张卡片——到店、在住、离店、VIP 到店和待跟进；当您的角色可以处理时，还会出现待处理客服会话和待回点评。每张卡片预览接下来的几条并链接到完整列表。' },
      {
        type: 'list',
        items: [
          '“到店”、“在住”和“离店”预览当天的客人流动——与“预订”视图覆盖同一批工作，只是按客人维度组织。',
          '“VIP 到店”标出值得在开门前就准备妥当的住宿。',
          '“跟进”是带截止日期的对客承诺——完整队列在“宾客关系 → 跟进”下。',
          '“待处理客服”和“待回点评”卡片只在您的角色可以处理时出现。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '卡片会打开对应的工作流——到店行落在客人资料上，客服行落在会话上。用看板找下一件事，而不是在上面办。' },
    ],
  },

  // ----------------------------------------------------------- 房间与库存
  {
    slug: 'room-types-and-rooms',
    title: '设置房型和房间',
    summary: '房型定义房间是什么、价格多少；房间是客人实际入住的物理单元——两者都在“客房配置”中管理。',
    category: 'rooms-inventory',
    keywords: ['房型', '添加房间', '新房间', '床型', '容纳人数', '定价', '删除房间'],
    routePath: '/room-config',
    requiredPermissions: ['rooms:create', 'rooms:update'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['daily-room-operations', 'online-inventory-grid', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: '客房配置是物业模型的所在。房型承载共享定义——名称、床型、容纳人数、定价和状态——每个房间都是某房型下的编号单元。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“客房配置”', body: '在“系统管理”菜单下找到它。' },
          { title: '创建或编辑房型', body: '依次完成各区块——基本信息（名称、描述）、床型、容纳人数（最大入住）、定价（每晚价格）和状态。' },
          { title: '为房型添加房间', body: '每个房间有一个编号并归属某房型。房间默认沿用房型的定价和容纳人数，但单个房间可以设置自己的每晚自定义价。' },
          { title: '删除前先检查', body: '“删除房间”移除一个单元；“删除房型”移除整个定义——只在没有任何依赖时可用。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '定价在这里维护', body: '客人看到的房价来自房型的“定价”区块；房间级自定义价会对该单元覆盖它。线上渠道的覆盖价在“线上库存”中单独处理。' },
      { type: 'callout', tone: 'tip', body: '“最大入住人数”同时驱动预订校验和客房服务规划——请如实填写。' },
    ],
  },
  {
    slug: 'daily-room-operations',
    title: '日常房间运营',
    summary: '房间看板：实时房态、入住与退房、换房、维修封房和逾期未退房。',
    category: 'rooms-inventory',
    keywords: ['房态', '已入住', '维修', '封房', '换房', '逾期退房', '脏房'],
    routePath: '/room-management',
    requiredPermissions: ['rooms:read', 'rooms:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['check-out-a-guest', 'housekeeping-maintenance', 'read-the-timeline'],
    blocks: [
      { type: 'paragraph', text: '“房间”是物业实体的运营看板——哪些房间已入住、哪些空闲、哪些被封、哪些退房已逾期。' },
      {
        type: 'list',
        items: [
          '“入住/退房”列一览当天的进出动态。',
          '“逾期退房”列出本该离店的客人——每个班次优先处理。',
          '“维修”让房间退出服务，直到状态被清除。',
          '“选择新房间”可为客人换房而不作废预订。',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: '从房间看板开始', body: '打开“房间”查看物业全貌。' },
          { title: '先处理逾期退房', body: '跟进或为每个逾期住宿办理退房，让房间得以清洁并重新销售。' },
          { title: '如实标记维修', body: '把维修中的房间设为“维修”，让前台知道它已退出服务。要停止某房型某天的线上销售，请在“线上库存”中覆盖该单元格——线上开关与房态是两回事。' },
          { title: '用“选择新房间”换房', body: '需要换房时选择新房间——预订会跟随客人。' },
        ],
      },
      { type: 'callout', tone: 'warning', body: '维修中的房间仍需要维修工单来跟踪——见“客房服务与维修工单”。' },
    ],
  },
  {
    slug: 'online-inventory-grid',
    title: '控制在线库存',
    summary: '在“在线库存”网格上按房型按日期覆盖可售量和价格——支持批量编辑。',
    category: 'rooms-inventory',
    keywords: ['在线库存', '可售量', '线上售卖', '价格覆盖', '关闭日期', '停售'],
    routePath: '/online-inventory',
    requiredPermissions: ['rooms:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['room-types-and-rooms', 'daily-room-operations', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: '“在线库存”是一个按日期×房型的网格，控制客人在线上能订到什么。每个单元格可以持有覆盖值——基础值来自房型。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“在线库存”', body: '网格中房型为行、未来日期为列。' },
          { title: '编辑单个单元格', body: '点击单元格打开编辑浮层，设置当天的值。' },
          { title: '或批量编辑一段区间', body: '选中多个单元格，然后用“批量编辑”面板把同一修改应用到整个选择。' },
          { title: '保存前先检查', body: '修改会汇集到“检查变更”中——在那里确认，并用“仅覆盖项”过滤器审计哪些与基础配置不同。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '已修改和被覆盖的单元格会有标记，您始终能区分基础配置与一次性决定。' },
      { type: 'callout', tone: 'important', body: '要停止某天的线上销售，请覆盖该单元格——除非房间真的停用，否则不要物理封房。' },
    ],
  },
  {
    slug: 'housekeeping-maintenance',
    title: '客房服务与维修工单',
    summary: '跟踪房间状态和维修工作——创建工单、指派人员，并把房间恢复为可售。',
    category: 'rooms-inventory',
    keywords: ['客房服务', '清洁', '维修工单', '维修', '脏房', '指派给'],
    routePath: '/housekeeping',
    requiredPermissions: ['housekeeping:read', 'housekeeping:create'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['daily-room-operations', 'check-out-a-guest', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: '“客房服务”协调房间状态：实时房态看板、用于清洁工作的“任务”队列，以及用于维修工单的“维修”标签页。退房房间会自动生成清洁任务；其余都要手动创建。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“客房服务”', body: '按楼层、优先级或状态筛选看板，聚焦本班次。' },
          { title: '为日常工作创建任务', body: '“新建任务”创建客房服务任务——指派给某人并带排期日期的清洁和房间工作。' },
          { title: '把维修报成工单', body: '房间上的“报告维修”，或“维修”标签页上的“新建工单”，会开出一张带房间、类别、优先级和负责人的维修工单。该标签页需要 maintenance:read，开工单需要 maintenance:write——没有这些权限的员工看不到这条路径。' },
          { title: '处理队列', body: '随工作进展更新任务和工单状态；“维修”中的房间在状态清除前一直退出可售池。' },
          { title: '恢复房间可售', body: '工作解决并清洁后，在房间看板上清除“维修”状态。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '先按优先级筛选——房间在售卖时，漏水的空调比踢脚线划痕更紧急。' },
    ],
  },

  // ----------------------------------------------------------- 支付与账目
  {
    slug: 'refund-a-deposit',
    title: '退还押金',
    summary: '从预订中退还客人押金——退款是退房的常规操作；撤销退款则被有意限制。',
    category: 'payments-ledgers',
    keywords: ['退款', '押金', '退钱', '退还押金', '撤销退款', '没收'],
    routePath: '/bookings',
    requiredPermissions: ['payments:refund'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['check-out-a-guest', 'review-payment-approvals', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: '押金退款是退房时的前台常规操作。该操作位于预订“发票”的押金区域，需要 payments:refund 权限，前台和经理都持有该权限。' },
      {
        type: 'steps',
        steps: [
          { title: '打开预订的“发票”', body: '找到该住宿并打开发票——押金区域显示已收取和仍冻结的金额。' },
          { title: '选择“退还押金”', body: '退款始终是全部剩余冻结余额——员工不能自选金额。选择退款方式并可附备注。' },
          { title: '或改为没收', body: '“没收押金”是独立操作。可保留部分或全部冻结余额，并选择原因——房间损坏、物品缺失、未付杂费或其他。未保留的部分仍可退还。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '撤销退款受限', body: '撤销押金退款会重新开放该押金供再次退款，且需要 payments:manage——前台无法自行循环退款/撤销。确认前请再次核对。' },
      { type: 'callout', tone: 'tip', body: '如果看不到退款按钮，说明您缺少 payments:refund——请找经理，而不是用手动调整绕过。' },
    ],
  },
  {
    slug: 'review-payment-approvals',
    title: '审核付款审批',
    summary: '付款凭证在审核队列中等待——对照预订核对收据，然后批准或拒绝。',
    category: 'payments-ledgers',
    keywords: ['付款审批', '收据', '付款凭证', '批准付款', '拒绝付款', '银行转账'],
    routePath: '/payment-approvals',
    requiredPermissions: ['payments:approve'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['refund-a-deposit', 'company-ledgers', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: '“付款审批”列出已提交的付款凭证及其预订、客人、金额、方式和收据。每个条目在您处理后从“已提交”变为“已审核”。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“支付审批”', body: '在“财务”菜单下找到它。' },
          { title: '检查凭证', body: '打开条目并下载收据——对照预订核对金额和参考号。' },
          { title: '批准或拒绝', body: '凭证相符时批准；不符时附理由拒绝。该决定会记录到您的账户名下。' },
        ],
      },
      { type: 'callout', tone: 'warning', body: '拒绝线上付款会触发发给客人的付款挽回邮件流程——只在凭证确实有误时拒绝。' },
      { type: 'callout', tone: 'tip', body: '按提交时间从旧到新处理队列：客人的入住可能正等着您的审核。' },
    ],
  },
  {
    slug: 'company-ledgers',
    title: '处理公司账',
    summary: '公司账户把挂账住宿累积到账上——核对余额、付款期限和逾期账户。',
    category: 'payments-ledgers',
    keywords: ['账目', '公司', '企业', '发票', '挂账', '付款期限', '城市账'],
    routePath: '/company-ledger',
    requiredPermissions: ['ledgers:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['review-payment-approvals', 'reports-and-metrics', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: '“公司账”跟踪挂到公司账户而非退房时支付的住宿。每本账显示公司、其预订和滚动余额。' },
      {
        type: 'list',
        items: [
          '公司挂账预订的客人在入住时可能触发提示——账单记到公司而非客人。',
          '付款期限定义公司结账的时限；超期且仍有余额的账户会被自动列出。',
          '在“预订”列表中，“逾期未结”视图又分为“普通”和“公司”——“公司”标签显示的是超过付款期限的公司挂账住宿，而非所有公司住宿。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '公司超期未结属于经理层面的沟通——系统负责标记，人来负责解决。' },
    ],
  },
  {
    slug: 'complimentary-nights-credits',
    title: '免费房晚与客人额度',
    summary: '把住宿标记为免费、转换为额度，并按客人和房型管理免费房晚余额。',
    category: 'payments-ledgers',
    keywords: ['免费', '免费房晚', '额度', '免费房额度', '赠送额度', '招待住宿'],
    routePath: '/complimentary',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['create-a-booking', 'company-ledgers', 'loyalty-program'],
    blocks: [
      { type: 'paragraph', text: '免费管理涵盖免费住宿：把预订标记为免费、把免费住宿转换为客人额度、以及用额度订房——全部按客人和房型跟踪。' },
      {
        type: 'list',
        items: [
          '从预订操作中把预订标记为免费。',
          '把免费住宿转换为额度——余额记在客人名下，按房型限定。',
          '用额度订房，消耗客人的免费房晚余额。',
          '汇总视图显示未使用的免费和额度总量。',
        ],
      },
      { type: 'callout', tone: 'important', body: '取消免费状态或删除额度会改变客人应得的权益——即使权限允许，也请把两者都当作经理级决定。' },
    ],
  },

  // ---------------------------------------------------------- 价格与促销
  {
    slug: 'promotions-vouchers',
    title: '管理促销与优惠券',
    summary: '创建客人在公开“优惠”页看到的促销活动，以及可为预订打折的优惠券。',
    category: 'rates-promotions',
    keywords: ['促销', '优惠券', '折扣', '优惠码', '优惠', '活动', '已暂停'],
    routePath: '/campaigns',
    requiredPermissions: ['promotions:manage', 'vouchers:manage'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'online-inventory-grid', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: '员工端页面名为“营销活动”，位于“收益与营销”下。它用两个标签页管理物业的优惠侧——“营销活动”（客人在公开“优惠”页看到的促销，含效果数据）和“优惠券”（绑定到这些促销的可兑换代码）。' },
      {
        type: 'list',
        items: [
          '营销活动定义优惠本身——名称、时间和内容。状态筛选为草稿、已排期、进行中、已暂停、已过期、已取消和已归档。',
          '优惠券是绑定到这些促销的可兑换代码——发给客人，或让会员用忠诚度积分兑换。',
          '营销邮件可以在“通信”中直接引用促销。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '促销卖的是“在线库存”所定价的东西——让公开优惠、券规则和实际房价保持一致口径。' },
    ],
  },
  {
    slug: 'loyalty-program',
    title: '了解会员忠诚度计划',
    summary: '忠诚度模块跟踪回头客及其奖励——在“客人”下的“会员忠诚度”查看。',
    category: 'guests',
    keywords: ['忠诚度', '奖励', '积分', '回头客', '会员'],
    routePath: '/loyalty',
    requiredPermissions: ['loyalty:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['complimentary-nights-credits', 'manage-guest-profiles', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: '“会员忠诚度”位于“客人”下，展示回头客计划侧的信息：会员、积分、奖励和待处理的兑换请求。持有 loyalty:manage 的员工管理奖励并审批兑换；loyalty:read（或 analytics:read）即可查看。' },
      { type: 'callout', tone: 'tip', body: '忠诚度、免费房晚和客人额度是三个不同的杠杆——使用任何一个之前先查看客人资料，避免重复补偿。' },
    ],
  },
  {
    slug: 'revenue-overview',
    title: '读懂“收益”总览',
    summary: '按住宿日期口径的收益表现，对比上一周期——KPI、每日趋势，以及收入来自哪些渠道。',
    category: 'rates-promotions',
    keywords: ['收益', 'adr', 'revpar', '渠道构成', '净收入', '业绩', '趋势'],
    routePath: '/revenue',
    requiredPermissions: ['revenue:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['reports-and-metrics', 'booking-channels', 'rates-and-rate-plans'],
    blocks: [
      { type: 'paragraph', text: '“收益”回答“钱的表现如何”，范围是您选择的住宿日期区间。KPI 栏把该区间与上一周期对比——收入、ADR、RevPAR、平均住宿天数、预订量（含作废率和爽约率）以及直销占净收入的比例。' },
      {
        type: 'list',
        items: [
          '趋势图按住宿日期显示入住率和间夜——找出的是弱的夜晚，而不只是弱的总量。',
          '渠道构成表按预订渠道拆分净收入，让 OTA 佣金体现在您实际留下的钱里，而不只是开出的账单。',
          '调整区间会让每个数字重新与对应的上一周期对比。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '想要按报表细分——按房型、按公司、按渠道——“经营分析”报表库更深入。“收益”是仪表盘，“经营分析”是下钻。' },
    ],
  },
  {
    slug: 'rates-and-rate-plans',
    title: '管理房价与房价计划',
    summary: '“房价日历”显示每个房型解析后的每晚价格；“房价计划”维护命名的价格集，含价格段、调整方式和批量更新。',
    category: 'rates-promotions',
    keywords: ['房价', '房价计划', '价格日历', '周中周末', '批量房价', '定价', '价格段'],
    routePath: '/rates',
    requiredPermissions: ['revenue:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['revenue-overview', 'online-inventory-grid', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: '“房价”有两个标签页。“房价日历”显示每个房型每天解析后的价格——包括线上覆盖价和该格售出情况。“房价计划”管理命名计划（标准、季节性、促销、公司协议等），其价格段在一段日期内为房型定价；多个计划重叠时优先级高者生效。' },
      {
        type: 'steps',
        steps: [
          { title: '先看日历', body: '浏览日期，核对客人每个房型要付多少钱——单元格显示生效价、来源以及当天入住情况。' },
          { title: '在房价计划内编辑', body: '“新建计划”或既有计划的价格段在“生效起止”之间按房型设置价格（或百分比/定额调整），可选地限定住宿天数和提前预订天数。' },
          { title: '批量更新一段区间', body: '“批量房价”一次为一个计划在一段日期内重新定价——重叠的价格段以最新写入为准。' },
        ],
      },
      { type: 'callout', tone: 'important', body: '房价计划是员工侧的定价工具——公开的线上价格仍来自房型加任何“线上库存”覆盖，且线上覆盖优先于一切房价规则。' },
    ],
  },
  {
    slug: 'guest-segments',
    title: '构建客群细分',
    summary: '基于规则实时评估的客人受众——挂到邮件活动上即可收窄收件人范围。',
    category: 'rates-promotions',
    keywords: ['客群细分', '受众', '目标客人', '营销名单', '规则', '活动受众'],
    routePath: '/segments',
    requiredPermissions: ['segments:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['email-campaigns-templates', 'manage-guest-profiles', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: '客群细分是基于规则的动态受众：一组作用于客人数据的条件（国家、住宿次数、标签、等级……），在发送时实时评估——而不是一份会过期的静态名单。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“客群细分”', body: 'segments:read 可查看细分库；创建和编辑需要 segments:manage。' },
          { title: '创建细分', body: '“新建客群细分”把“字段 + 运算符 + 值”一行行组合——“国家为以下之一…”、“住宿次数至少…”——构成受众定义。' },
          { title: '挂到活动上', body: '在“通信管理 → 邮件活动”中选择该细分以收窄发送受众——受众数量会随选择实时更新。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '因为细分是实时评估的，同一条活动定义发出的邮件永远面向“今天匹配”的客人——而不是名单保存那天匹配的人。' },
    ],
  },
  {
    slug: 'booking-channels',
    title: '管理预订渠道',
    summary: '预订经哪些渠道进来——售卖价格、佣金，以及渠道价格矩阵。',
    category: 'rates-promotions',
    keywords: ['渠道', 'ota', 'booking.com', 'agoda', 'expedia', '佣金', '上门客', '直销', '价格矩阵'],
    routePath: '/channels',
    requiredPermissions: ['channels:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['revenue-overview', 'online-inventory-grid', 'rates-and-rate-plans'],
    blocks: [
      { type: 'paragraph', text: '“渠道”列出预订可以到达的分销渠道——直销、上门、电话和各 OTA——每个渠道有自己的售卖价和佣金设置。“价格矩阵”标签页把渠道与房型排成网格，一次看清并调整整张表。' },
      {
        type: 'list',
        items: [
          '渠道记录带有该渠道抽取的佣金——这正是“收益”和“经营分析”上净收入与毛收入不同的原因。',
          '创建和编辑渠道需要 channels:write；启用和删除需要 channels:manage。',
          '预订的渠道决定它在“经营分析”的“渠道净收入”和 OTA 报表中落入哪些数字。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '新增房型后请检查矩阵——没有渠道行的房型会按默认值定价，而这通常不是您的本意。' },
    ],
  },

  // ------------------------------------------------------ 报表与夜审
  {
    slug: 'reports-and-metrics',
    title: '在“经营分析”中看报表',
    summary: '“经营分析”报表库：运营、财务、分析和会计报表——入住率、收入、流水、对账单等。',
    category: 'reports-night-audit',
    keywords: ['报表', '经营分析', '入住率', 'adr', 'revpar', '收入', '到店', '离店', '分析', '指标', '日记账', '资产负债表', '班次报告', 'ota'],
    routePath: '/insights',
    requiredPermissions: ['analytics:read'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['run-night-audit', 'audit-log', 'revenue-overview'],
    blocks: [
      { type: 'paragraph', text: '“经营分析”是报表库——每张报表都通过同一个带各自筛选器的外壳呈现，分为四个家族。（旧的 /reports 地址会重定向到这里。）' },
      {
        type: 'list',
        items: [
          '运营——每日运营（到店、离店、在住、入住率）、入住率（含 ADR 和 RevPAR）、已售客房、客房表现、班次报告和免费房晚。',
          '财务——收入、渠道净收入、OTA 佣金、OTA 月度对账单和付款状态。',
          '分析——客人统计：唯一客人、新客与回头客、国籍构成和高价值客人。',
          '会计——总日记账、按类型日记账、资产负债表和公司账册对账单（按公司的对账单，含账龄）。',
        ],
      },
      { type: 'heading', text: '最常被问到的两个指标' },
      {
        type: 'list',
        items: [
          'ADR——每间已售房的平均成交价：客房收入 ÷ 已售房数。它回答“我们卖得够不够高”。',
          'RevPAR——收入摊到每间可售房（无论售出与否）：客房收入 ÷ 总房数。它回答“我们是否在以好价格填满房间”。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '只看入住率会掩盖打折，只看 ADR 会掩盖空房——两个指标要一起读。' },
    ],
  },
  {
    slug: 'run-night-audit',
    title: '运行夜审',
    summary: '结束营业日：确认夜审，它会锁定当天预订禁止编辑并快照房间状态。',
    category: 'reports-night-audit',
    keywords: ['夜审', '日结', '关账', '锁定预订', '营业日期'],
    routePath: '/night-audit',
    requiredPermissions: ['night_audit:execute'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['reports-and-metrics', 'audit-log', 'hotel-settings'],
    blocks: [
      { type: 'paragraph', text: '夜审结束酒店的营业日。确认夜审会记录执行人和时间、锁定当天预订禁止再编辑，并可快照房间状态供报表使用。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“夜审”', body: '在“财务”菜单下找到它，并核对审计日期。' },
          { title: '查看本次运行的内容', body: '确认框会列出选项——包括锁定预订和记录房间状态快照。' },
          { title: '确认夜审', body: '运行会以您的账户和时间戳记录；审计日志会同步反映。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '锁定是真实生效的', body: '夜审之后，当天的预订会抵抗进一步编辑——请在当天真正结束时运行，或使用“酒店设置”中的自动运行选项。' },
      { type: 'callout', tone: 'tip', body: '营业日期遵循“酒店设置”中的酒店时区——夜审关闭的是那一天，而不是 UTC 零点。' },
    ],
  },
  {
    slug: 'audit-log',
    title: '使用审计日志',
    summary: '谁改了什么的只读记录——发现与昨天不一样时第一站该看的地方。',
    category: 'reports-night-audit',
    keywords: ['审计日志', '历史', '谁修改', '活动', '轨迹'],
    routePath: '/audit-log',
    requiredPermissions: ['audit:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['page-missing-or-access-denied', 'run-night-audit', 'roles-and-permissions'],
    blocks: [
      { type: 'paragraph', text: '审计日志记录全系统的变更操作——预订修改、设置编辑、角色调整、夜审运行。它在设计上就是只读的。' },
      {
        type: 'list',
        items: [
          '调查被改动的预订或设置 → 先来这里，再到处打听。',
          '权限审查 → 日志显示谁在何时授予了什么。',
          '每条记录都标明操作者和时间戳，跟进能找到具体的人而不是谜。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '与预订时间线搭配使用：日志记录动作，时间线讲述住宿的故事。' },
    ],
  },

  // ------------------------------------------------------------- 通信
  {
    slug: 'email-campaigns-templates',
    title: '发送营销邮件与管理模板',
    summary: '构建可复用的邮件模板，然后向选定客人发送活动——正式发送前先测发。',
    category: 'communications',
    keywords: ['邮件', '活动', '模板', '公告', '营销', '测发', '变量'],
    routePath: '/communications',
    requiredPermissions: ['communications:compose', 'communications:send'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-not-sending', 'promotions-vouchers', 'guest-deliveries'],
    blocks: [
      { type: 'paragraph', text: '“通信”有三个标签页：“邮件活动”（真实发送）、“模板”（带变量的可复用内容）和“屏蔽名单”（绝不可发送的地址）。' },
      {
        type: 'steps',
        steps: [
          { title: '创建或选择模板', body: '模板承载主题和正文，变量用于填入客人相关的值。' },
          { title: '发送测试邮件', body: '“发送测试邮件”先验证格式和送达，发到您自己的地址，客人还看不到。' },
          { title: '创建活动', body: '选择类型（例如“公告”）、收件人——可选地收窄到某个客群细分——主题和正文，可选地关联一个促销。' },
          { title: '观察发送', body: '状态标签为草稿、已排期、进行中、已完成、已取消或失败。已上线、已暂停和已结束不是邮件发送状态——已暂停属于“营销活动”优惠页，与进行中、已过期、已取消和已归档并列。“已发送/失败”计数和“最近错误”列会暴露问题。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '务必先发测试邮件——一个失效的变量在批量发送时会很难堪。' },
    ],
  },
  {
    slug: 'notifications-guest-support',
    title: '通知与客人支持收件箱',
    summary: '通知铃铛是给您的；“支持”收件箱是给客人的——在那里回复他们的消息。',
    category: 'communications',
    keywords: ['通知', '铃铛', '支持收件箱', '客人消息', '会话', '回复', '指派'],
    routePath: '/support',
    requiredPermissions: ['support:read', 'support:write'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['email-not-sending', 'manage-guest-profiles', 'guest-deliveries'],
    blocks: [
      { type: 'paragraph', text: '存在三个不同的“通知”入口。顶栏的铃铛是员工通知中心——您的提醒、系统通知和发送分层。“客人”下的“客服”是接收客人门户消息的收件箱——那些需要员工回复。“工具”下的“通知”是发往外部的客人邮件发送记录。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“客服”', body: '会话列表显示未关闭的客人会话，包括未认领队列。' },
          { title: '先认领再回复', body: '未认领的会话必须先被认领才有人能回复——由您自己（持有 support:assign 或 support:manage 时）或由持有该权限的人认领。只有写权限是不够的。' },
          { title: '阅读并回复', body: '打开会话查看客人消息并内联回复。会话一旦被指派，由其负责人（或 support:manage 持有者）回复——而不是大家一起上。' },
          { title: '更新状态', body: '关闭或更新会话状态，让队列保持真实。' },
        ],
      },
      { type: 'callout', tone: 'info', title: '不是员工 IT 支持', body: '这个收件箱面向向酒店求助的客人。关于管理门户本身的帮助，请使用帮助中心的“获取更多帮助”指引。' },
      { type: 'callout', tone: 'tip', body: '支持收件箱可以在“酒店设置”中全物业关闭——如果整个模块消失了，那个开关是第一嫌疑人。' },
    ],
  },
  {
    slug: 'email-not-sending',
    title: '邮件发不出去',
    summary: '排查营销与通知邮件的发送失败——多数原因都能在“最近错误”列或失败的测发中看到。',
    category: 'communications',
    keywords: ['邮件失败', 'smtp', '发不出', '邮件错误', '活动失败', '最近错误'],
    routePath: '/communications',
    requiredPermissions: ['communications:read'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['email-campaigns-templates', 'notifications-guest-support', 'escalation'],
    blocks: [
      { type: 'paragraph', text: '邮件由后台工作进程发送，需要在服务器上配置 SMTP 凭据。邮件停发时，证据几乎都在“通信”页面本身。' },
      {
        type: 'steps',
        steps: [
          { title: '发送测试邮件', body: '测发失败证明问题出在基础设施而非活动内容。' },
          { title: '看“最近错误”列', body: '活动发送会按收件人记录失败原因——认证、连接和地址错误各自对应不同的修法。' },
          { title: '查看“已发送/失败”计数', body: '部分失败指向收件人地址；全部失败指向 SMTP 配置。' },
          { title: '上报 SMTP 问题', body: '服务器邮件设置属于环境配置而非门户内的界面——交给管理部署的人。' },
        ],
      },
      { type: 'callout', tone: 'important', body: '如果根本没有 SMTP 设置，邮件工作进程就是关闭的——您的屏幕没有故障，是这项能力从未被配置。' },
    ],
  },
  {
    slug: 'guest-deliveries',
    title: '查看客人邮件发送记录',
    summary: '发往客人的邮件流——酒店发出或排队的每条消息，及其分层、状态和最近错误。',
    category: 'communications',
    keywords: ['发送记录', '宾客投递', '邮件流', '发件箱', '已发邮件', '发送状态', '排队中', '被屏蔽', '事务性', '营销'],
    routePath: '/notifications',
    requiredPermissions: ['communications:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'email-not-sending', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: '页面标题是“宾客投递”。侧栏项是“工具”下的“通知”，与顶栏铃铛分开，记录发往客人的邮件。酒店发出或排队的每条消息都带脱敏收件人、类型、分层、状态、尝试次数、最近错误和发送时间。' },
      {
        type: 'list',
        items: [
          '“事务性”与“营销”两个分层，把收据和预订邮件与活动群发分开。',
          '状态筛选可收窄到排队中、发送中、已发送、失败、被屏蔽或已取消——失败行带着最近错误。',
          '铃铛里的发送标签页展示同一数据流的缩略版；本页才是完整的可筛选列表。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '客人坚称收据没收到？先来这里找到那一行——已发送、失败还是被屏蔽，胜过瞎猜。' },
    ],
  },

  // -------------------------------------------------------------- 员工与权限
  {
    slug: 'add-manage-staff',
    title: '添加与管理员工账户',
    summary: '为同事创建登录、分配角色，并在“访问控制”中编辑或移除账户。',
    category: 'staff-access',
    keywords: ['添加用户', '新员工', '员工账户', '创建用户', '删除用户', '员工登录'],
    routePath: '/rbac',
    requiredPermissions: ['users:create', 'users:update'],
    lastReviewed: '2026-10-04',
    featured: true,
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: '打开“访问控制”', body: '在“系统管理”菜单下找到它，然后打开“用户”标签页。' },
          { title: '选择“添加用户”', body: '“创建新用户”对话框收集新员工的账户信息。' },
          { title: '分配角色', body: '角色决定这个人能看什么、能做什么——前台和经理看到的是不同的门户。可在同一流程中分配，也可事后在用户行上调整。' },
          { title: '之后编辑或移除', body: '“编辑用户”更新信息；员工离职时“删除用户”会移除整个账户。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '先配角色再首次登录', body: '没有角色的用户几乎什么都看不到——如果同事反馈门户是空的，先检查角色分配。' },
      { type: 'callout', tone: 'tip', body: '优先调整角色而不是创建一次性账户；无论哪种方式，审计日志都会记录每次变更。' },
    ],
  },
  {
    slug: 'roles-and-permissions',
    title: '角色与权限',
    summary: '角色打包权限；权限控制页面和操作。*:manage 权限隐含其领域内的其他权限。',
    category: 'staff-access',
    keywords: ['角色', '权限', 'rbac', '访问控制', 'manage 权限', '前台 经理'],
    routePath: '/rbac',
    requiredPermissions: ['roles:read', 'roles:manage'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['add-manage-staff', 'page-missing-or-access-denied', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: '“访问控制”有两个标签页：“角色与权限”——如前台、经理这样的命名权限包，每个角色内按领域分组管理单项权限——和“用户”，即持有这些角色的员工账户。' },
      {
        type: 'list',
        items: [
          '权限形如 资源:操作——例如 bookings:create 或 payments:refund。',
          '资源:manage 权限隐含该资源的所有操作。',
          '路由策略把页面映射到权限，这就是不同用户菜单不同的原因。',
          '系统角色自带合理的授权；特殊配置可以创建自定义角色。',
        ],
      },
      { type: 'callout', tone: 'warning', body: '修改系统角色会影响所有持有该角色的人——当只有一个人需要不同的权限时，请新建角色。' },
      { type: 'callout', tone: 'tip', body: '权限在“角色与权限”标签页的每个角色内按领域分组——展开一个类别即可看到角色究竟能做什么。' },
    ],
  },
  {
    slug: 'ekyc-reviews',
    title: '审核 eKYC 提交',
    summary: '身份核验工作在 eKYC 管理队列中进行——被指派的审核员按风险级别处理提交。',
    category: 'staff-access',
    keywords: ['ekyc', '身份', '核验', 'kyc', '审核员', '合规'],
    routePath: '/ekyc-admin',
    requiredPermissions: ['ekyc:review'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['roles-and-permissions', 'audit-log', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: '“eKYC 管理”是电子身份核验的审核队列。专门角色——eKYC 审核员、高级审核员和合规管理员——处理提交，高风险个案升级到高级审核。' },
      {
        type: 'list',
        items: [
          '审核员处理指派给自己的申请；高级审核员负责升级和高风险批准。',
          '敏感操作（查看证件、查看供应商数据）有独立权限并会被记录。',
          '如果看不到该模块，说明您没有任何 eKYC 角色——这是设计而非故障。',
        ],
      },
      { type: 'callout', tone: 'info', body: 'eKYC 权限被有意细分——只申请您的审核级别所需的操作。' },
    ],
  },

  // ------------------------------------------------------------- 设置与数据
  {
    slug: 'hotel-settings',
    title: '配置酒店设置',
    summary: '物业资料、入住/退房时间、时区、税费、押金、报表字体和功能开关——其他界面继承的默认值。',
    category: 'settings-data',
    keywords: ['设置', '酒店名称', '时区', '入住时间', '税', '押金', '旅游税', '服务税', '配置'],
    routePath: '/settings',
    requiredPermissions: ['settings:update'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['run-night-audit', 'room-types-and-rooms', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: '“酒店设置”保存其他界面继承的物业级默认值：名称与联系方式、入住/退房时间、时区、押金金额、服务税和旅游税率、付款期限、报表排版以及功能开关。' },
      {
        type: 'list',
        items: [
          '入住与退房时间驱动提前入住提示和客房服务目标。',
          '时区定义营业日期——报表、夜审和“今天”都跟随它。',
          '押金金额、服务税和旅游税计入预订总额；外籍客人需付旅游税。',
          '支持和客人取消开关可整体启停对应功能。',
          '报表字体设置决定打印输出的版式。',
        ],
      },
      { type: 'callout', tone: 'important', title: '未付款保留窗口也在这里', body: '“未付款保留释放小时数”控制 pending_payment 预订占用房间的时长（默认 24；0 为禁用）。' },
      { type: 'callout', tone: 'warning', body: '设置保存后立即生效——错误的税率或时区会影响每一笔新预订。' },
    ],
  },
  {
    slug: 'import-export-data',
    title: '导入与导出数据',
    summary: '“数据迁移”负责备份的进出——四个导出档位、先预览，以及在任何特权或破坏性操作前重新验证身份。',
    category: 'settings-data',
    keywords: ['导入', '导出', '备份', '恢复', '数据迁移', '数据转移', '迁移', '数据库', '系统备份', '口令短语'],
    routePath: '/data-transfer',
    requiredPermissions: ['data_transfer:view'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['hotel-settings', 'audit-log', 'escalation'],
    blocks: [
      { type: 'paragraph', text: '“数据转移”负责酒店数据的迁入迁出——用于备份、恢复和迁移。您能做什么取决于数据转移权限：查看页面、导出和导入各自需要独立授权，涉及机密或破坏性的操作还会要求您重新输入密码（如已启用，还需验证器验证码）。' },
      {
        type: 'steps',
        steps: [
          { title: '打开“数据迁移”', body: '需要 data_transfer:view。“导出”标签页有四个档位：标准（仅运营数据）、完整（全部可转移业务数据）、迁移备份（完整数据集加关系元数据）和完整系统备份（仅超级管理员）。' },
          { title: '导出', body: '标准档需要 data_transfer:export。完整和迁移备份携带机密的客人、支付和账目数据——需要 data_transfer:export_sensitive 并重新验证身份。完整系统备份更进一步：用户账户、密码哈希、会话、RBAC 授权、eKYC 记录和审计历史——仅限超级管理员，且文件始终用您提供的口令短语加密。' },
          { title: '检查导入预览', body: '上传备份文件（data_transfer:import）。预览显示文件内容、在包含敏感数据时警告，并指明您仍缺少的权限。' },
          { title: '确认导入', body: '“合并”只新增、不动现有行；“更新”式冲突处理需要 data_transfer:override。完整恢复会先删除现有数据，需要 data_transfer:restore 并重新验证身份。只在您信任的文件上继续。' },
          { title: '查看“转移历史”', body: '过去的导入、导出和提权尝试都连同操作者一起列出——与审计日志记录的是同一批行。' },
        ],
      },
      { type: 'callout', tone: 'important', title: '设计上即具破坏性', body: '“先删除所有现有数据”是字面意思——完整恢复会替换整个数据库。请与管理员确认文件和时机。' },
      { type: 'callout', tone: 'tip', title: '机密只留在最高档', body: '标准、完整和迁移备份绝不含凭据——密码、会话、令牌或身份核验证据。完整系统备份有意包含它们，以便在全新安装上重建登录；这正是它始终加密、凭口令短语解锁且仅限超级管理员的原因。请妥善保管口令短语——丢失后无法找回。' },
    ],
  },
  {
    slug: 'system-health-and-jobs',
    title: '系统健康与后台任务',
    summary: '“系统管理”下照看平台本身的两个面板——服务健康，以及让酒店正常运转的后台任务。',
    category: 'settings-data',
    keywords: ['系统健康', '后台任务', '计划任务', '调度', '服务状态', '夜审任务', '运行时间'],
    routePath: '/system-health',
    requiredPermissions: ['settings:manage'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['hotel-settings', 'audit-log', 'run-night-audit'],
    blocks: [
      { type: 'paragraph', text: '“系统管理”下有两个页面照看的是平台而非物业。“系统健康”报告部署的运行状况——服务状态、数据库和 worker 健康。“后台任务”列出服务器按计划执行的任务——夜审、未付款保留释放、支付收据、通信发送——以及最近一次运行状态。' },
      {
        type: 'list',
        items: [
          '多个页面同时出问题时先看“系统健康”——它能把应用问题和数据问题分开。',
          '“后台任务”显示计划工作是否在跑——停滞的夜审或邮件任务能解释“它自己停了”这类反馈。',
          '两者都属于 settings:manage 的领地——如果看不到，那是管理员的视图。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '一行失败的任务加上审计日志通常就能指名原因——上报时两个都带上。' },
    ],
  },

  // ------------------------------------------------------------- 故障排查
  {
    slug: 'cant-find-a-booking',
    title: '找不到预订？',
    summary: '按清单排查：搜索词、筛选器，以及让预订从日常视图消失的两种状态（已作废、已释放）。',
    category: 'troubleshooting',
    keywords: ['预订丢失', '预订缺失', '找不到', '无结果', '消失了'],
    routePath: '/bookings',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['find-a-reservation', 'void-reactivate-release', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          '在 ⌘K 中试预订编号——BK- 编号和客人姓名都能搜。',
          '清除“预订”列表上的筛选——遗留的搜索词、“抵店”或“逾期未结”等视图标签、日期或月份筛选是常见元凶。',
          '检查日期：住宿可能在您查看的范围之外。',
          '询问预订是否已被作废——已作废的住宿会从日常视图消失。',
          '检查是否为已释放的未付款保留——始终未付款的线上预订会自动释放回库存。',
          '确认您能看到“预订”模块本身——模块缺失是权限问题，不是搜索问题。',
        ],
      },
      { type: 'callout', tone: 'tip', body: '预订时间线和审计日志在作废后依然保留——只要预订存在过，它的记录就还在。' },
    ],
  },
  {
    slug: 'payment-problems',
    title: '支付问题',
    summary: '线上付款失败、审批卡住和退款报错——把症状对应到正确的队列。',
    category: 'troubleshooting',
    keywords: ['付款失败', '支付错误', '被拒', '挽回付款', '审批卡住', '退款错误'],
    routePath: '/payment-approvals',
    lastReviewed: '2026-10-04',
    relatedSlugs: ['refund-a-deposit', 'review-payment-approvals', 'email-not-sending'],
    blocks: [
      {
        type: 'list',
        items: [
          '客人线上付款失败 → 付款挽回邮件可以让客人通过安全链接重试——在断定钱丢了之前先查看预订状态。',
          '付款凭证在等待 → 它会留在“付款审批”中直到有人审核；客人看到的是“已提交”而非“已确认”。',
          '退款按钮缺失 → 您需要 payments:refund；撤销退款需要 payments:manage。',
          '预订卡在 pending_payment → 它是未付款保留；会自动释放或可手动释放。',
        ],
      },
      { type: 'callout', tone: 'warning', body: '绝不要通过编辑预订来“修好”卡住的付款——走审批队列或上报；账目和审计轨迹需要真实的理由。' },
    ],
  },
  {
    slug: 'session-and-stale-data',
    title: '会话与过期数据问题',
    summary: '当界面看起来过时或会话行为异常时——刷新顺序、空闲过期和营业日期陷阱。',
    category: 'troubleshooting',
    keywords: ['数据过期', '刷新', '会话过期', '被退出', '日期不对', '时区'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['sign-in-and-security', 'hotel-settings', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          '刷新页面——长时间空闲后会话令牌会自动续期；界面过时只需重新加载。',
          '会话状态不一致时退出并重新登录——“退出登录”图标在顶栏最右端（手机宽度的屏幕不显示）。',
          '日期看起来不对 → 营业日期遵循“酒店设置”中的酒店时区，而不是您笔记本的时钟。',
          '设置改了但没生效 → 有些变更只对新活动生效，不追溯。',
          '另一台设备上看起来不同 → 主题和语言按工作站记忆，权限按账户生效。',
        ],
      },
      { type: 'callout', tone: 'info', body: '反复被退出不是故障——访问令牌有意设计为短时效，并会在后台静默续期。' },
    ],
  },
  {
    slug: 'escalation',
    title: '获取更多帮助',
    summary: '当帮助中心解决不了时该怎么办——找谁问、带上什么。',
    category: 'troubleshooting',
    keywords: ['联系', '上报', '经理', '管理员', '更多帮助', '支持'],
    lastReviewed: '2026-10-04',
    relatedSlugs: ['page-missing-or-access-denied', 'payment-problems', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: '帮助中心覆盖门户的使用方法。账户访问、权限变更以及任何疑似缺陷的问题，请沿物业自身的链路逐级上报。' },
      {
        type: 'steps',
        steps: [
          { title: '询问您的管理员或经理', body: '权限、角色和设置变更归他们管——带上页面名称和您预期看到的内容。' },
          { title: '带上证据', body: '审计日志记录、预订编号、活动的“最近错误”文本——一条具体记录胜过对症状的描述。' },
          { title: '客人侧的问题', body: '如果是客人在反映问题，先到“支持”收件箱查找现有会话，而不是另起一条并行线索。' },
        ],
      },
      { type: 'callout', tone: 'tip', body: '截图有帮助，但准确的错误文本和发生时间更有用——两者都在应用自己的记录里。' },
    ],
  },
];
