import type { HelpArticle } from '../types';

/**
 * Malay help articles — mirrors articles.en.ts (same slugs, same block
 * shapes; content.test.ts enforces parity). Control names are the Bahasa
 * Melayu labels the admin portal renders.
 */
export const ARTICLES_MS: HelpArticle[] = [
  // ---------------------------------------------------------- getting started
  {
    slug: 'sign-in-and-security',
    title: 'Log masuk dan selamatkan akaun anda',
    summary: 'Log masuk, tambah passkey atau pengesahan dua faktor, dan log keluar dengan selamat di stesen kerja berkongsi.',
    category: 'getting-started',
    keywords: ['log masuk', 'kata laluan', 'passkey', '2fa', 'dua faktor', 'log keluar', 'komputer berkongsi'],
    routePath: '/profile',
    lastReviewed: '2026-10-05',
    relatedSlugs: ['getting-around-admin-portal', 'page-missing-or-access-denied'],
    blocks: [
      { type: 'paragraph', text: 'Akaun kakitangan dicipta oleh pentadbir. Setelah menerima kelayakan, log masuk dari halaman login — portal akan mengembalikan anda ke halaman yang asalnya anda cuba buka.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka halaman login', body: 'Masukkan nama pengguna dan kata laluan. Jika sesi anda tamat, anda akan dibawa ke sini dahulu kemudian dihantar semula ke halaman yang dikehendaki.' },
          { title: 'Tambah passkey apabila diminta', body: 'Semasa log masuk pertama, anda mungkin diminta mendaftar passkey (cap jari, wajah, atau PIN peranti). Passkey ialah cara paling pantas dan selamat untuk masuk semula — anda boleh menolak prompt dan menetapkannya kemudian dari profil anda.' },
          { title: 'Daftar pengesahan dua faktor', body: 'Jika peranan anda memerlukannya, anda akan dibimbing melalui pendaftaran 2FA. Sediakan aplikasi pengesah anda.' },
          { title: 'Log keluar pada akhir syif', body: 'Pilih ikon Log Keluar di hujung kanan bar atas, di sebelah avatar akaun anda. Di stesen kerja kaunter hadapan yang dikongsi, ini bukan pilihan — orang seterusnya mewarisi sesi yang ditinggalkan.' },
        ],
      },
      { type: 'callout', tone: 'warning', title: 'Stesen kerja berkongsi', body: 'Jangan biarkan sesi yang telah log masuk tanpa pengawasan di kaunter hadapan. Log keluar akan memadam token akses dalam ingatan. Ikon Log Keluar disembunyikan pada skrin selebar telefon — tamatkan sesi dari tablet atau desktop.' },
      { type: 'callout', tone: 'tip', body: 'Jika halaman memaparkan Akses ditolak, peranan anda sememangnya tidak merangkuminya — lihat “Kenapa saya tidak dapat melihat halaman?” sebelum menganggap ada kerosakan.' },
    ],
  },
  {
    slug: 'getting-around-admin-portal',
    title: 'Mengemudi portal admin',
    summary: 'Kumpulan navigasi, palet arahan, notifikasi, bahasa dan tema — lima kawalan yang akan anda gunakan setiap syif.',
    category: 'getting-started',
    keywords: ['navigasi', 'menu', 'palet arahan', 'carian', 'tema', 'bahasa', 'mod gelap', 'english'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['sign-in-and-security', 'cant-find-a-booking'],
    blocks: [
      { type: 'paragraph', text: 'Dua permukaan membawa portal. Bar sisi memegang nama hotel, butang Tempahan baharu dan navigasi modul, dikumpulkan sebagai Utama, Pejabat Hadapan, Tetamu, Hasil & Pemasaran, Kewangan, Wawasan, Pentadbiran dan Utiliti. Bar atas memegang carian, loceng notifikasi, bahasa, menu akaun anda dan ikon Log Keluar.' },
      {
        type: 'list',
        items: [
          'Pejabat Hadapan merangkumi kerja harian kaunter — Tempahan, Garis Masa, Bilik dan Pengemasan. Tetamu menghimpun Hubungan Tetamu, direktori Tetamu, Sokongan dan Kesetiaan.',
          'Hasil & Pemasaran memegang Hasil, Kadar, Kempen, Segmen, Saluran, Komunikasi dan Inventori Dalam Talian; Kewangan memegang Lejar Syarikat, Kelulusan Pembayaran, Audit Malam dan Malam Percuma.',
          'Pentadbiran memegang Kawalan Akses, Pentadbir eKYC, Tetapan Hotel, Konfigurasi Bilik, Log Audit, Pemindahan Data, Kesihatan Sistem dan Tugasan; Utiliti memegang Penghantaran dan Bantuan ini.',
          'Pada telefon, navigasi berpindah ke bar bawah — beberapa destinasi utama serta Lagi, helaian yang menyenaraikan setiap modul lain yang anda boleh lihat, dengan senarai bahasa di bawahnya. Tiada laci sisi atau butang menu pada pengepala.',
          'Hanya kumpulan yang peranan anda boleh lihat muncul — dua kakitangan boleh mempunyai bar sisi berbeza pada skrin yang sama.',
        ],
      },
      { type: 'heading', text: 'Cari apa-apa dengan ⌘K' },
      { type: 'paragraph', text: 'Tekan ⌘K (Ctrl+K pada Windows) atau klik bar carian — ikon carian pada telefon — untuk membuka palet arahan. Ia mencari tempahan, tetamu, entri lejar, bilik, halaman — dan artikel bantuan. Kekunci anak panah menggerakkan hasil, Enter membuka pilihan, Esc menutup. Taip / untuk tindakan pantas seperti Tempahan baharu.' },
      { type: 'heading', text: 'Bahasa dan tema' },
      { type: 'paragraph', text: 'Ikon glob menukar antara English, Bahasa Melayu, 简体中文 dan 繁體中文 serta-merta — tanpa muat semula; pada telefon ia berada di bahagian bawah helaian Lagi. Tetapan Hotel → Rupa hanya menawarkan Cerah dan Gelap. Pilihan tema malam yang tersimpan dibuka sebagai Gelap, dan pilihan diingati pada stesen kerja itu.' },
      { type: 'callout', tone: 'tip', body: 'Palet mengingati enam destinasi terkini anda, jadi perjalanan berulang hanya mengambil dua ketukan kekunci.' },
    ],
  },
  {
    slug: 'page-missing-or-access-denied',
    title: 'Kenapa saya tidak dapat melihat halaman?',
    summary: 'Halaman muncul berdasarkan peranan dan kebenaran anda — item menu yang hilang atau skrin Akses ditolak hampir selalu keputusan akses, bukan kerosakan.',
    category: 'getting-started',
    keywords: ['access denied', '403', 'kebenaran', 'menu tersembunyi', 'peranan', 'tidak nampak', 'halaman hilang'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security'],
    blocks: [
      { type: 'paragraph', text: 'Setiap modul dalam portal admin dilindungi oleh dasar akses laluan. Navigasi anda hanya menunjukkan destinasi yang dibenarkan oleh peranan dan kebenaran anda — dua kakitangan boleh melihat menu yang sangat berbeza pada skrin yang sama.' },
      {
        type: 'list',
        items: [
          'Item menu hilang → dasar laluan mengecualikan peranan anda atau anda tiada kebenarannya.',
          'Anda membuka pautan dan melihat Akses ditolak (403) → anda boleh melihat portal tetapi bukan modul itu.',
          'Sesuatu berfungsi semalam tetapi tidak hari ini → peranan anda atau dasar laluan telah berubah. Semak Log Audit atau tanya pentadbir.',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: 'Sahkan modul itu wujud', body: 'Tanya rakan sekerja sama ada mereka dapat melihat halaman itu. Jika tiada siapa dapat, ia mungkin isu konfigurasi dan bukan akses.' },
          { title: 'Tanya pentadbir anda', body: 'Akses diberikan dalam Pentadbiran → Kawalan Akses: tab Pengguna melantik peranan, tab Peranan & Kebenaran mengubah apa yang peranan benarkan. Hanya pentadbir boleh mengubahnya.' },
        ],
      },
      { type: 'callout', tone: 'info', body: 'Kebenaran *:manage merangkumi setiap tindakan lain pada sumber itu — contohnya, bookings:manage merangkumi create, read, update dan delete.' },
    ],
  },
  {
    slug: 'front-desk-overview',
    title: 'Mulakan syif pada Utama',
    summary: 'Utama ialah skrin utama — ketibaan, pelepasan dan keadaan bilik hari ini untuk kaunter, atau papan pemuka analitik untuk pengurus.',
    category: 'getting-started',
    keywords: ['overview', 'papan pemuka', 'laman utama', 'kaunter hadapan', 'ketibaan hari ini', 'pelepasan', 'status bilik'],
    routePath: '/',
    lastReviewed: '2026-10-05',
    relatedSlugs: ['getting-around-admin-portal', 'daily-room-operations', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: 'Utama ialah halaman yang dibuka oleh portal. Apa yang dipaparkannya bergantung pada peranan anda: kakitangan kaunter hadapan mendapat papan hari ini operasi — ketibaan, pelepasan dan gambaran status bilik langsung — manakala pengurus dan pentadbir mendapat papan pemuka analitik.' },
      {
        type: 'list',
        items: [
          'Papan kaunter hadapan memaparkan pergerakan hari ini — ketibaan untuk daftar masuk, pelepasan untuk daftar keluar, bilik yang memerlukan perhatian — serta jalur tempahan baharu apabila ia masuk.',
          'Papan pemuka pengurusan mengagregat analitik hasil, penghunian dan trend dan bukannya giliran kerja kaunter.',
          'Semua pada papan memaut seterusnya — satu baris membuka tempahan atau bilik, jadi Utama ialah titik mula, bukan destinasi.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Mulakan syif di sini, selesaikan ketibaan dan pelepasan dahulu, kemudian biarkan Tempahan atau papan Bilik mengambil alih untuk baki hari.' },
    ],
  },

  // ------------------------------------------------------------------ bookings
  {
    slug: 'create-a-booking',
    title: 'Cipta tempahan',
    summary: 'Buat tempahan dari butang Tempahan baharu — pilih tarikh, bilik, kadar dan bayaran dalam satu skrin.',
    category: 'bookings',
    keywords: ['tempahan', 'tempahan baharu', 'walk in', 'tempahan telefon', 'tempahan manual'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:create'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['check-in-a-guest', 'find-a-reservation', 'void-reactivate-release'],
    blocks: [
      { type: 'paragraph', text: 'Tempahan walk-in, telefon dan tetamu berulang semuanya dicipta melalui skrin Tempahan baharu yang sama. Ia menggabungkan tarikh penginapan, pemilihan bilik, butiran tetamu dan kadar/bayaran dalam satu aliran.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Tempahan baharu', body: 'Gunakan butang Tempahan baharu di bahagian atas bar sisi, atau butang Tempahan baharu pada halaman Tempahan sendiri. Pada telefon ia turut berada pada helaian tindakan pantas.' },
          { title: 'Pilih tarikh dan mod penginapan', body: 'Pilih tarikh daftar masuk dan daftar keluar. Pemilih mod tempahan menyesuaikan aliran mengikut jenis tempahan yang anda buat.' },
          { title: 'Pilih bilik', body: 'Pilih jenis bilik, kemudian bilik tertentu. Hanya bilik yang kosong untuk keseluruhan tempoh ditawarkan.' },
          { title: 'Masukkan butiran tetamu', body: 'Cari tetamu sedia ada atau masukkan yang baharu — nama, butiran hubungan dan warganegara menentukan cukai dan semakan identiti.' },
          { title: 'Tetapkan kadar dan bayaran', body: 'Semak harga semalam dan jumlah, pilih kaedah bayaran dan deposit, kemudian sahkan.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Warganegara Tempatan lawan Asing mengawal sama ada cukai pelancongan dikenakan — ia dipilih pada bahagian tetamu, bukan semasa bayaran.' },
      { type: 'callout', tone: 'important', title: 'Hold dalam talian tanpa bayaran', body: 'Tempahan yang kekal dalam Menunggu bayaran ialah hold. Ia dilepaskan secara automatik selepas tempoh yang ditetapkan dalam Tetapan Hotel (Pelepasan Hold Belum Dibayar) dan boleh dilepaskan secara manual lebih awal.' },
    ],
  },
  {
    slug: 'find-a-reservation',
    title: 'Cari tempahan',
    summary: 'Cari mana-mana tempahan mengikut kod, nama tetamu atau bilik — dari senarai Tempahan atau palet ⌘K.',
    category: 'bookings',
    keywords: ['cari tempahan', 'tempahan hilang', 'kod tempahan', 'bk-', 'carian'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['cant-find-a-booking', 'check-in-a-guest', 'create-a-booking'],
    blocks: [
      { type: 'paragraph', text: 'Terdapat dua laluan pantas bergantung pada apa yang anda tahu: senarai Tempahan apabila anda mahu menyemak dan menapis, atau palet ⌘K apabila anda tahu kod tempahan atau tetamu.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka palet ⌘K', body: 'Tekan ⌘K atau klik bar carian. Pilih cip skop Tempahan untuk mengehadkan hasil.' },
          { title: 'Cari mengikut kod atau tetamu', body: 'Taip kod tempahan (contohnya BK-…) atau nama tetamu. Memilih hasil membuka Tempahan yang sudah ditapis kepada tempahan itu.' },
          { title: 'Atau tapis senarai Tempahan', body: 'Pada halaman Tempahan, kotak carian memadankan tempahan, tetamu, invois dan nombor bilik, manakala cip paparan (Semua, Ketibaan, Dalam Penginapan, Akan Datang, Baki Tertunggak) serta penapis kaedah bayaran, saluran dalam talian, tarikh dan bulan mengecilkan senarai tanpa meninggalkan halaman.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Menampal kod tempahan ke dalam palet ialah carian paling pantas — hasilnya memaut terus ke senarai yang ditapis.' },
      { type: 'callout', tone: 'info', title: 'Jika masih tidak muncul', body: 'Tempahan void dan hold tanpa bayaran yang dilepaskan dikecualikan daripada paparan biasa. Lihat “Tidak jumpa tempahan?” untuk senarai semak penuh.' },
    ],
  },
  {
    slug: 'check-in-a-guest',
    title: 'Daftar masuk tetamu',
    summary: 'Tandakan ketibaan pada hari daftar masuk — tempahan Disahkan dan Menunggu layak; daftar masuk awal ditandakan, bukan disekat.',
    category: 'bookings',
    keywords: ['ketibaan', 'checkin', 'daftar masuk', 'kaunter hadapan', 'check in awal'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['check-out-a-guest', 'find-a-reservation', 'housekeeping-maintenance'],
    blocks: [
      { type: 'paragraph', text: 'Tempahan boleh didaftar masuk apabila statusnya Disahkan atau Menunggu dan tarikh ketibaan telah tiba. Tindakan Daftar masuk berada pada tempahan itu sendiri.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka tempahan', body: 'Cari melalui ⌘K atau senarai Tempahan dan buka butirannya.' },
          { title: 'Pilih Daftar masuk', body: 'Tindakan ini hanya muncul apabila tempahan layak — status Disahkan atau Menunggu dan hari ini pada atau selepas tarikh daftar masuk.' },
          { title: 'Semak makluman daftar masuk', body: 'Tetamu yang biasa dibilkan kepada syarikat boleh mencetuskan makluman sebelum anda meneruskan — bacanya, kemudian sahkan.' },
          { title: 'Sahkan', body: 'Tempahan berpindah ke Daftar masuk dan bilik menunjukkan diduduki pada Bilik dan Garis Masa.' },
        ],
      },
      { type: 'callout', tone: 'info', title: 'Daftar masuk awal', body: 'Tiba sebelum waktu daftar masuk yang dikonfigurasi (Tetapan Hotel → Masa Daftar Masuk, lalai 15:00) memaparkan gesaan daftar masuk awal dan bukannya sekatan keras.' },
      { type: 'callout', tone: 'warning', body: 'Butang Daftar masuk tidak akan muncul sebelum tarikh ketibaan — ini disengajakan. Jika tetamu tiba sehari awal, edit tarikh tempahan dahulu.' },
    ],
  },
  {
    slug: 'check-out-a-guest',
    title: 'Daftar keluar tetamu',
    summary: 'Tutup penginapan dari tempahan atau papan Bilik — hanya tempahan berstatus Daftar masuk boleh daftar keluar.',
    category: 'bookings',
    keywords: ['pelepasan', 'daftar keluar', 'berlepas', 'selesai', 'daftar keluar lewat'],
    routePath: '/room-management',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['check-in-a-guest', 'refund-a-deposit', 'housekeeping-maintenance'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: 'Buka tempahan atau papan Bilik', body: 'Daftar keluar tersedia dari tindakan tempahan, dan papan Bilik memaparkan Daftar Keluar Lewat supaya tiada yang terlepas.' },
          { title: 'Pilih Daftar keluar', body: 'Tindakan ini hanya muncul semasa status tempahan Daftar masuk.' },
          { title: 'Selesaikan penginapan', body: 'Tempahan yang melepasi tarikh daftar keluar dengan baki tertunggak — termasuk penginapan bil syarikat yang melepasi terma bayaran — diketengahkan supaya anda boleh mengutip atau mengatur bayaran sebelum atau semasa pelepasan.' },
          { title: 'Hantar bilik kembali untuk dikemas', body: 'Selepas daftar keluar, bilik kembali ke giliran pengemasan dan tugas pengemasan dicipta secara automatik — bilik tidak membuka tiket penyelenggaraan dengan sendirinya.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Jika deposit telah dikutip, bayar balik semasa daftar keluar — lihat “Bayar balik deposit”.' },
      { type: 'callout', tone: 'warning', body: 'Tempahan tidak boleh daftar keluar melainkan ia Daftar masuk. Jika status kelihatan salah, semak garis masa tempahan untuk melihat apa yang berlaku.' },
    ],
  },
  {
    slug: 'void-reactivate-release',
    title: 'Batal, aktifkan semula atau lepaskan tempahan',
    summary: 'Batal membatalkan tempahan, aktifkan semula memulihkan yang dibatalkan, dan Lepaskan bilik membebaskan hold dalam talian tanpa bayaran — tiga tindakan berbeza dengan peraturan berbeza.',
    category: 'bookings',
    keywords: ['batal', 'void', 'aktif semula', 'lepas', 'hold tanpa bayaran', 'tiada bayaran', 'noshow'],
    routePath: '/bookings',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['create-a-booking', 'refund-a-deposit', 'find-a-reservation'],
    blocks: [
      { type: 'paragraph', text: 'Setiap tindakan wujud untuk situasi berbeza, dan setiap satu hanya ditawarkan apabila tempahan layak — jika butang hilang, status tempahan ialah puncanya.' },
      {
        type: 'list',
        items: [
          'Batal — membatalkan tempahan. Tersedia pada mana-mana tempahan yang belum dibatalkan. Gunakan untuk pembatalan.',
          'Aktifkan semula — memulihkan tempahan yang dibatalkan. Hanya ditawarkan pada tempahan yang dibatalkan.',
          'Lepaskan bilik — membebaskan bilik yang dipegang oleh tempahan dalam talian tanpa bayaran. Hanya ditawarkan semasa status Menunggu bayaran dan tiada bayaran telah dikutip.',
        ],
      },
      { type: 'heading', text: 'Hold tanpa bayaran lepas sendiri' },
      { type: 'paragraph', text: 'Tugas latar belakang melepaskan hold tanpa bayaran secara automatik selepas tempoh yang dikonfigurasi dalam Tetapan Hotel (Pelepasan Hold Belum Dibayar — lalai 24, 0 menyahaktif). Pelepasan manual ialah untuk mengosongkan bilik lebih awal.' },
      { type: 'callout', tone: 'important', title: 'Wang sudah dikutip?', body: 'Lepaskan bilik sengaja tidak tersedia sebaik sahaja wujud sebarang bayaran — pelayan turut menguatkuasakannya. Batal tempahan dan bayar balik tetamu sebaliknya.' },
      { type: 'callout', tone: 'tip', body: 'Setiap peralihan ini direkodkan dalam garis masa tempahan dan Log Audit — anda sentiasa boleh melihat siapa melakukan apa.' },
    ],
  },
  {
    slug: 'read-the-timeline',
    title: 'Baca garis masa tempahan',
    summary: 'Pandangan bilik-mengikut-hari tentang siapa tiba, menginap atau berlepas — cara terpantas melihat penghunian sepintas lalu.',
    category: 'bookings',
    keywords: ['garis masa', 'kalendar', 'paparan penghunian', 'pergerakan bilik', 'ketibaan pelepasan'],
    routePath: '/timeline',
    requiredPermissions: ['bookings:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['daily-room-operations', 'check-in-a-guest', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: 'Garis Masa menyusun tempahan merentasi bilik dan hari supaya anda dapat melihat ketibaan, penginapan dalaman dan pelepasan sebagai peta dan bukan senarai. Ia ialah skrin yang sesuai untuk perancangan perpindahan bilik dan mengesan kekosongan.' },
      {
        type: 'list',
        items: [
          'Imbas seminggu penghunian dalam beberapa saat — berguna sebelum menerima walk-in.',
          'Rancang perpindahan bilik mengelilingi tempahan berturut-turut pada bilik yang sama.',
          'Kenal pasti bilik kosong untuk daftar masuk awal tanpa membuka setiap tempahan.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Padankan dengan papan Bilik: Garis Masa untuk “siapa di mana bila”, Bilik untuk “apa keadaan setiap bilik sekarang”.' },
    ],
  },

  // -------------------------------------------------------------------- guests
  {
    slug: 'manage-guest-profiles',
    title: 'Urus profil tetamu',
    summary: 'Cari, edit dan selenggara rekod tetamu — termasuk tanda Maklumat kurang dan pemindahan akaun portal.',
    category: 'guests',
    keywords: ['tetamu', 'profil', 'edit tetamu', 'sejarah tetamu', 'nombor ic', 'akaun portal', 'missing info'],
    routePath: '/guest-relations/guests',
    requiredPermissions: ['guests:read', 'guests:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['create-a-booking', 'notifications-guest-support', 'guest-relations-hub'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: 'Buka Tetamu', body: 'Halaman Tetamu menyenaraikan setiap profil tetamu. Carian mengecilkan mengikut nama atau butiran hubungan.' },
          { title: 'Buka profil', body: 'Lihat butiran hubungan, medan identiti, sejarah tempahan dan makluman seperti Maklumat kurang sepintas lalu.' },
          { title: 'Edit apa yang berubah', body: 'Pastikan telefon dan e-mel terkini — ia menggerakkan resit, kempen dan aliran pra-daftar masuk.' },
          { title: 'Kendalikan akaun portal dengan teliti', body: 'Pindahkan akaun portal memindahkan log masuk portal ke profil berbeza — gunakan hanya apabila anda pasti akaun itu milik orang yang sama.' },
        ],
      },
      { type: 'callout', tone: 'warning', title: 'Memadam tetamu', body: 'Padam tetamu memadam profil. Utamakan edit berbanding padam apabila tempahan wujud — sejarah penting untuk lejar dan laporan.' },
      { type: 'callout', tone: 'tip', body: 'Cip Maklumat kurang menandakan profil dengan kekosongan (seperti telefon) yang menyekat aliran seperti notifikasi — ia tempat pertama untuk disemak apabila tetamu “tidak dapat dihubungi”.' },
    ],
  },
  {
    slug: 'guest-relations-hub',
    title: 'Urus papan Hubungan Tetamu',
    summary: 'Satu papan untuk kerja berdepan tetamu — ketibaan, tetamu dalaman, pelepasan, ketibaan VIP, susulan, sokongan terbuka dan ulasan.',
    category: 'guests',
    keywords: ['guest relations', 'ketibaan', 'pelepasan', 'susulan', 'vip', 'ulasan', 'guest 360'],
    routePath: '/guest-relations',
    requiredPermissions: ['guests:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['manage-guest-profiles', 'check-in-a-guest', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: 'Hubungan Tetamu ialah giliran kerja berdepan tetamu: jalur statistik serta satu kad bagi setiap giliran — ketibaan, tetamu dalaman, pelepasan, ketibaan VIP dan susulan terbuka, dengan perbualan sokongan terbuka dan ulasan menunggu apabila peranan anda boleh bertindak padanya. Setiap kad mempratonton beberapa item seterusnya dan memaut ke senarai penuh.' },
      {
        type: 'list',
        items: [
          'Ketibaan hari ini, Tetamu dalam penginapan dan Perlepasan hari ini mempratonton pergerakan tetamu hari ini — kerja yang sama diliputi paparan Tempahan, dihimpun cara tetamu.',
          'Ketibaan VIP menandakan penginapan yang patut disediakan sebelum pintu dibuka.',
          'Susulan terbuka ialah janji tetamu dengan tarikh akhir — giliran penuh berada di bawah Hubungan Tetamu.',
          'Kad Permintaan sokongan terbuka dan Ulasan menunggu respons hanya muncul apabila peranan anda boleh bertindak padanya.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Kad membuka aliran kerja yang sepadan — baris ketibaan mendarat pada profil tetamu, baris sokongan pada perbualan. Gunakan papan untuk mencari perkara seterusnya, bukan untuk melakukannya.' },
    ],
  },

  // ----------------------------------------------------------- rooms & inventory
  {
    slug: 'room-types-and-rooms',
    title: 'Sediakan jenis bilik dan bilik',
    summary: 'Jenis bilik mentakrifkan apa sesuatu bilik dan harganya; bilik ialah unit fizikal tempat tetamu tidur — kedua-duanya diurus dalam Konfigurasi Bilik.',
    category: 'rooms-inventory',
    keywords: ['jenis bilik', 'tambah bilik', 'bilik baharu', 'susunan katil', 'kapasiti', 'harga', 'padam bilik'],
    routePath: '/room-config',
    requiredPermissions: ['rooms:create', 'rooms:update'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['daily-room-operations', 'online-inventory-grid', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: 'Konfigurasi Bilik ialah tempat model hartanah berada. Jenis bilik membawa takrifan dikongsi — nama, susunan katil, kapasiti, harga dan status — dan setiap bilik ialah unit bernombor bagi sesuatu jenis.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Konfigurasi Bilik', body: 'Cari ia di bawah menu Pentadbiran.' },
          { title: 'Cipta atau edit jenis bilik', body: 'Lalui bahagian-bahagian — Asas (nama, penerangan), Persediaan Katil, Kapasiti (penghuni maksimum), Harga (harga semalam) dan Status.' },
          { title: 'Tambah bilik kepada jenis itu', body: 'Setiap bilik mendapat nombor dan tergolong dalam sesuatu jenis. Bilik menggunakan harga dan kapasiti jenis secara lalai, tetapi sesuatu bilik boleh membawa harga tersuai sendiri setiap malam.' },
          { title: 'Semak sebelum memadam', body: 'Padam Bilik memadam unit; Padam Jenis Bilik memadam takrifan — hanya apabila tiada apa bergantung padanya.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Harga bermula di sini', body: 'Kadar yang tetamu lihat bermula pada bahagian Pricing jenis bilik; harga tersuai peringkat bilik mengatasinya untuk unit itu. Override dalam talian diurus secara berasingan dalam Inventori Dalam Talian.' },
      { type: 'callout', tone: 'tip', body: 'Penghunian Maksimum menggerakkan pengesahan tempahan dan perancangan pengemasan — pastikan ia tepat.' },
    ],
  },
  {
    slug: 'daily-room-operations',
    title: 'Jalankan operasi bilik harian',
    summary: 'Papan Bilik: status bilik langsung, daftar masuk dan daftar keluar, perpindahan bilik, sekatan penyelenggaraan dan pelepasan lewat.',
    category: 'rooms-inventory',
    keywords: ['status bilik', 'diduduki', 'penyelenggaraan', 'bilik disekat', 'pindah bilik', 'daftar keluar lewat', 'bilik kotor'],
    routePath: '/room-management',
    requiredPermissions: ['rooms:read', 'rooms:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['check-out-a-guest', 'housekeeping-maintenance', 'read-the-timeline'],
    blocks: [
      { type: 'paragraph', text: 'Bilik ialah papan operasi untuk hartanah fizikal — bilik mana diduduki, mana kosong, mana disekat, dan pelepasan mana yang lewat.' },
      {
        type: 'list',
        items: [
          'Lajur Daftar masuk / Daftar keluar menunjukkan pergerakan hari ini sepintas lalu.',
          'Daftar Keluar Lewat memaparkan tetamu yang sepatutnya sudah berlepas — selesaikan dahulu setiap syif.',
          'Penyelenggaraan mengeluarkan bilik daripada perkhidmatan sehingga statusnya dikosongkan.',
          'Pilih Bilik Baharu memindahkan tetamu antara bilik tanpa membatalkan tempahan.',
        ],
      },
      {
        type: 'steps',
        steps: [
          { title: 'Mulakan dari papan Bilik', body: 'Buka Bilik untuk gambaran keseluruhan hartanah.' },
          { title: 'Selesaikan daftar keluar lewat dahulu', body: 'Susul atau daftar keluar setiap penginapan lewat supaya bilik boleh dikemas dan dijual semula.' },
          { title: 'Tandakan baik pulih dengan jujur', body: 'Tetapkan bilik dalam baik pulih kepada Penyelenggaraan supaya kaunter tahu ia di luar perkhidmatan. Untuk menghentikan jualan dalam talian bagi jenis bilik dan tarikh, override sel dalam Inventori Dalam Talian — suis dalam talian berasingan daripada status bilik.' },
          { title: 'Pindahkan tetamu dengan Pilih Bilik Baharu', body: 'Untuk pertukaran bilik, pilih bilik baharu — tempahan mengikut tetamu.' },
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Bilik dalam Penyelenggaraan masih memerlukan tiket penyelenggaraan untuk penjejakan — lihat “Tiket pengemasan dan penyelenggaraan”.' },
    ],
  },
  {
    slug: 'online-inventory-grid',
    title: 'Kawal inventori dalam talian',
    summary: 'Override ketersediaan dan harga mengikut jenis bilik dan tarikh pada grid Inventori Dalam Talian — termasuk edit pukal.',
    category: 'rooms-inventory',
    keywords: ['inventori dalam talian', 'ketersediaan', 'jual online', 'override kadar', 'tutup tarikh', 'henti jual'],
    routePath: '/online-inventory',
    requiredPermissions: ['rooms:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['room-types-and-rooms', 'daily-room-operations', 'reports-and-metrics'],
    blocks: [
      { type: 'paragraph', text: 'Inventori Dalam Talian ialah grid tarikh-mengikut-jenis-bilik yang mengawal apa yang tetamu boleh tempah dalam talian. Setiap sel boleh memegang override — nilai asas datang dari jenis bilik.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Inventori Dalam Talian', body: 'Grid menunjukkan jenis bilik sebagai baris dan tarikh akan datang sebagai lajur.' },
          { title: 'Edit satu sel', body: 'Klik sel untuk membuka popover editor dan tetapkan nilai tarikh itu.' },
          { title: 'Atau edit pukal satu julat', body: 'Pilih berbilang sel, kemudian gunakan panel edit pukal untuk mengenakan satu perubahan merentasi pilihan.' },
          { title: 'Semak sebelum menyimpan', body: 'Perubahan terkumpul dalam Semak perubahan — sahkan di sana, dan gunakan penapis “Tetapan khas sahaja” untuk mengaudit apa yang berbeza dari tetapan asas.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Sel yang diubah dan di-override ditandakan, jadi anda sentiasa boleh membezakan konfigurasi asas dari keputusan sekali sahaja.' },
      { type: 'callout', tone: 'important', body: 'Untuk menghentikan jualan dalam talian bagi sesuatu tarikh, override sel itu — jangan sekat bilik secara fizikal melainkan ia benar-benar tidak boleh digunakan.' },
    ],
  },
  {
    slug: 'housekeeping-maintenance',
    title: 'Tiket pengemasan dan penyelenggaraan',
    summary: 'Jejaki keadaan bilik dan kerja penyelenggaraan — cipta tiket, lantik pemegang, dan kembalikan bilik ke dalam perkhidmatan.',
    category: 'rooms-inventory',
    keywords: ['housekeeping', 'pengemasan', 'tiket penyelenggaraan', 'baiki', 'kotor', 'dilantik kepada'],
    routePath: '/housekeeping',
    requiredPermissions: ['housekeeping:read', 'housekeeping:create'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['daily-room-operations', 'check-out-a-guest', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: 'Pengemasan menyelaraskan keadaan bilik: papan bilik dengan status langsung, giliran Tugas untuk kerja pengemasan, dan tab Penyelenggaraan untuk tiket baik pulih. Bilik daftar keluar mendapat tugas pengemasan secara automatik; selebihnya manual.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Pengemasan', body: 'Tapis papan mengikut tingkat, keutamaan atau status untuk memfokuskan syif.' },
          { title: 'Cipta tugas untuk kerja rutin', body: 'Tugas baharu mencipta tugas pengemasan — kerja pengemasan dan bilik yang dilantik kepada seseorang dengan tarikh berjadual.' },
          { title: 'Laporkan baik pulih sebagai tiket', body: 'Laporkan penyelenggaraan pada bilik, atau Tiket baharu pada tab Penyelenggaraan, membuka tiket penyelenggaraan dengan bilik, kategori, keutamaan dan pemegang. Tab itu memerlukan maintenance:read dan tiket memerlukan maintenance:write — kakitangan tanpanya tidak pernah melihat laluan ini.' },
          { title: 'Selesaikan giliran', body: 'Kemas kini status tugas dan tiket mengikut perkembangan kerja; bilik dalam Penyelenggaraan kekal di luar kumpulan boleh dijual sehingga statusnya dikosongkan.' },
          { title: 'Kembalikan bilik ke perkhidmatan', body: 'Setelah kerja diselesaikan dan bilik dikemas, kosongkan status Penyelenggaraan pada papan Bilik.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Tapis mengikut keutamaan dahulu — penghawa dingin bocor lebih mendesak daripada dinding tercalar apabila bilik sedang dijual.' },
    ],
  },

  // ----------------------------------------------------------- payments & ledgers
  {
    slug: 'refund-a-deposit',
    title: 'Bayar balik deposit',
    summary: 'Pulangkan deposit tetamu dari tempahan — bayaran balik ialah tugas daftar keluar biasa; membatalkannya sengaja dihadkan.',
    category: 'payments-ledgers',
    keywords: ['bayaran balik', 'deposit', 'pulangan wang', 'refund', 'batal refund', 'rampas'],
    routePath: '/bookings',
    requiredPermissions: ['payments:refund'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['check-out-a-guest', 'review-payment-approvals', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: 'Bayaran balik deposit ialah kerja kaunter hadapan rutin semasa daftar keluar. Tindakan itu berada di dalam Invois tempahan, pada bahagian deposit, dan memerlukan kebenaran payments:refund, yang dipegang oleh penyambut tetamu dan pengurus.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Invois tempahan', body: 'Cari penginapan dan buka Invoisnya — bahagian deposit menunjukkan apa yang dikutip dan apa yang masih dipegang.' },
          { title: 'Pilih Bayar balik deposit', body: 'Bayaran balik sentiasa baki pegangan penuh — kakitangan tidak memilih jumlah. Pilih kaedah bayaran balik dan tambah nota pilihan.' },
          { title: 'Atau forfeit sebaliknya', body: 'Rampas deposit ialah pilihan berasingan. Simpan sebahagian atau keseluruhan baki pegangan dan pilih sebab — kerosakan bilik, barang hilang, caj tertunggak, atau lain-lain. Apa yang tidak disimpan kekal boleh dibayar balik.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Membatalkan bayaran balik adalah terhad', body: 'Mengembalikan semula bayaran balik deposit membuka semula deposit untuk dibayar balik dan memerlukan payments:manage — penyambut tetamu tidak boleh kitar refund/revert sendiri. Semak dua kali sebelum mengesahkan.' },
      { type: 'callout', tone: 'tip', body: 'Jika butang bayaran balik hilang, anda tiada payments:refund — minta pengurus dan bukannya mengatasi dengan pelarasan manual.' },
    ],
  },
  {
    slug: 'review-payment-approvals',
    title: 'Semak kelulusan bayaran',
    summary: 'Bukti bayaran menunggu dalam giliran semakan — periksa resit berbanding tempahan, kemudian lulus atau tolak.',
    category: 'payments-ledgers',
    keywords: ['kelulusan bayaran', 'resit', 'bukti bayaran', 'lulus bayaran', 'tolak bayaran', 'pindahan bank'],
    routePath: '/payment-approvals',
    requiredPermissions: ['payments:approve'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['refund-a-deposit', 'company-ledgers', 'payment-problems'],
    blocks: [
      { type: 'paragraph', text: 'Kelulusan Pembayaran menyenaraikan bukti bayaran yang diserahkan bersama tempahan, tetamu, jumlah, kaedah dan resit. Setiap item berpindah dari Dihantar ke Disemak sebaik sahaja anda bertindak.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Kelulusan Pembayaran', body: 'Cari ia di bawah menu Kewangan.' },
          { title: 'Periksa bukti', body: 'Buka item dan muat turun resit — semak jumlah dan rujukan berbanding tempahan.' },
          { title: 'Lulus atau tolak', body: 'Lulus apabila bukti sepadan; tolak dengan sebab apabila tidak. Keputusan direkodkan atas akaun anda.' },
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Bayaran dalam talian yang ditolak mencetuskan aliran e-mel pemulihan bayaran kepada tetamu — tolak hanya apabila bukti benar-benar salah.' },
      { type: 'callout', tone: 'tip', body: 'Selesaikan giliran yang paling lama dahulu: daftar masuk tetamu mungkin menunggu semakan anda.' },
    ],
  },
  {
    slug: 'company-ledgers',
    title: 'Bekerja dengan lejar syarikat',
    summary: 'Akaun korporat mengumpul penginapan yang dibilkan dalam lejar — semak baki, terma bayaran dan akaun lewat.',
    category: 'payments-ledgers',
    keywords: ['lejar', 'syarikat', 'korporat', 'invois', 'dibilkan', 'terma bayaran', 'city ledger'],
    routePath: '/company-ledger',
    requiredPermissions: ['ledgers:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['review-payment-approvals', 'reports-and-metrics', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: 'Lejar Syarikat menjejaki penginapan yang dibilkan kepada akaun korporat dan bukannya dibayar semasa daftar keluar. Setiap lejar menunjukkan syarikat, tempahannya dan baki berjalan.' },
      {
        type: 'list',
        items: [
          'Tetamu pada tempahan bil syarikat boleh mencetuskan makluman semasa daftar masuk — bil pergi ke syarikat, bukan tetamu.',
          'Terma bayaran mentakrifkan berapa lama syarikat ada untuk melangsaikan; akaun yang melepasi terma dengan baki diketengahkan secara automatik.',
          'Pada senarai Tempahan, paparan Baki Tertunggak berpecah kepada Biasa dan Syarikat — cip Syarikat menunjukkan penginapan bil syarikat yang melepasi terma bayaran, bukan setiap penginapan syarikat.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Syarikat yang melepasi termanya ialah perbualan untuk pengurus — sistem menandakannya, manusia menyelesaikannya.' },
    ],
  },
  {
    slug: 'complimentary-nights-credits',
    title: 'Malam percuma dan kredit tetamu',
    summary: 'Tandakan penginapan sebagai percuma, tukarkannya kepada kredit, dan urus baki malam percuma setiap tetamu dan jenis bilik.',
    category: 'payments-ledgers',
    keywords: ['percuma', 'malam percuma', 'kredit', 'kredit bilik percuma', 'kredit hadiah', 'penginapan comp'],
    routePath: '/complimentary',
    requiredPermissions: ['bookings:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['create-a-booking', 'company-ledgers', 'loyalty-program'],
    blocks: [
      { type: 'paragraph', text: 'Pengurusan complimentary merangkumi penginapan percuma: menandakan tempahan sebagai complimentary, menukar penginapan complimentary kepada kredit tetamu, dan menempah dengan kredit itu — semuanya dijejaki setiap tetamu dan jenis bilik.' },
      {
        type: 'list',
        items: [
          'Tandakan tempahan complimentary dari tindakan tempahan.',
          'Tukar penginapan complimentary kepada kredit — baki berada dengan tetamu, mengikut skop jenis bilik.',
          'Tempah dengan kredit untuk menggunakan baki malam percuma tetamu pada penginapan baharu.',
          'Paparan ringkasan menunjukkan jumlah complimentary dan kredit tertunggak.',
        ],
      },
      { type: 'callout', tone: 'important', body: 'Membuang status complimentary atau memadam kredit mengubah apa yang tetamu berhak terima — anggap kedua-duanya sebagai keputusan peringkat pengurus walaupun kebenaran membenarkannya.' },
    ],
  },

  // ---------------------------------------------------------- rates & promotions
  {
    slug: 'promotions-vouchers',
    title: 'Urus promosi dan baucar',
    summary: 'Cipta tawaran yang tetamu lihat pada halaman Offers awam dan baucar yang mendiskaunkan tempahan.',
    category: 'rates-promotions',
    keywords: ['promosi', 'baucar', 'diskaun', 'kod promo', 'tawaran', 'deal', 'kempen', 'dijeda'],
    routePath: '/campaigns',
    requiredPermissions: ['promotions:manage', 'vouchers:manage'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'online-inventory-grid', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: 'Halaman kakitangan bertajuk Kempen dan berada di bawah Hasil & Pemasaran. Ia mengurus bahagian tawaran hartanah merentasi dua tab — Kempen (tawaran awam yang tetamu lihat pada halaman Offers, dengan prestasi) dan Vouchers (kod tebus yang terikat pada tawaran itu).' },
      {
        type: 'list',
        items: [
          'Kempen mentakrifkan tawaran — namanya, bila ia berjalan dan apa yang diberikannya. Penapis status ialah Draf, Dijadualkan, Berlangsung, Dijeda, Tamat tempoh, Dibatalkan dan Diarkibkan.',
          'Baucar ialah kod tebus yang terikat pada tawaran itu — keluarkannya kepada tetamu atau biarkan ahli menebusnya dengan mata kesetiaan.',
          'E-mel kempen boleh merujuk promosi secara langsung dari Komunikasi.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Promosi menjual apa yang Inventori Dalam Talian hargakan — pastikan tawaran awam, terma baucar dan kadar sebenar menceritakan kisah yang sama.' },
    ],
  },
  {
    slug: 'loyalty-program',
    title: 'Fahami program kesetiaan',
    summary: 'Kesetiaan menjejaki tetamu berulang dan ganjaran mereka — lihat dari item Kesetiaan di bawah Tetamu.',
    category: 'guests',
    keywords: ['kesetiaan', 'ganjaran', 'mata', 'tetamu berulang', 'ahli'],
    routePath: '/loyalty',
    requiredPermissions: ['loyalty:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['complimentary-nights-credits', 'manage-guest-profiles', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: 'Kesetiaan, di bawah Tetamu, menunjukkan sisi program bagi tetamu berulang: ahli, mata, ganjaran dan permintaan tebusan menunggu. Kakitangan dengan loyalty:manage mentadbir ganjaran dan meluluskan tebusan; loyalty:read (atau analytics:read) memadai untuk melihat.' },
      { type: 'callout', tone: 'tip', body: 'Kesetiaan, malam percuma dan kredit tetamu ialah tiga tuas berbeza — semak profil tetamu sebelum menggunakan mana-mana satunya supaya anda tidak memberi ganti dua kali.' },
    ],
  },
  {
    slug: 'revenue-overview',
    title: 'Baca gambaran Hasil',
    summary: 'Prestasi hasil tarikh penginapan berbanding tempoh sebelumnya — KPI, trend harian dan saluran asal wang.',
    category: 'rates-promotions',
    keywords: ['revenue', 'adr', 'revpar', 'campuran saluran', 'hasil bersih', 'prestasi', 'trend'],
    routePath: '/revenue',
    requiredPermissions: ['revenue:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['reports-and-metrics', 'booking-channels', 'rates-and-rate-plans'],
    blocks: [
      { type: 'paragraph', text: 'Hasil menjawab “bagaimana keadaan wang?” merentasi julat tarikh penginapan yang anda pilih. Jalur KPI membandingkan julat dengan tempoh sebelumnya — hasil, ADR, RevPAR, purata penginapan, tempahan (dengan kadar void dan no-show) serta bahagian langsung hasil bersih.' },
      {
        type: 'list',
        items: [
          'Carta trend menunjukkan penghunian dan malam bilik mengikut tarikh penginapan — kenal pasti malam lemah, bukan hanya jumlah lemah.',
          'Jadual campuran saluran memecahkan hasil bersih mengikut saluran tempahan, jadi komisen OTA kelihatan pada apa yang anda simpan, bukan hanya apa yang anda bilkan.',
          'Menukar julat mengasaskan semula setiap angka berbanding tempoh sebelumnya yang sepadan.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Untuk potongan setiap laporan — setiap jenis bilik, setiap syarikat, setiap saluran — perpustakaan Wawasan pergi lebih dalam. Hasil ialah papan pemuka; Wawasan ialah perincian.' },
    ],
  },
  {
    slug: 'rates-and-rate-plans',
    title: 'Urus kadar dan pelan kadar',
    summary: 'Kalendar Kadar menunjukkan harga semalaman terselesai setiap jenis bilik; Pelan Kadar memegang set harga bernama dengan band, pelarasan dan kemas kini pukal.',
    category: 'rates-promotions',
    keywords: ['kadar', 'pelan kadar', 'kalendar harga', 'hari bekerja hujung minggu', 'kadar pukal', 'harga', 'band kadar'],
    routePath: '/rates',
    requiredPermissions: ['revenue:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['revenue-overview', 'online-inventory-grid', 'room-types-and-rooms'],
    blocks: [
      { type: 'paragraph', text: 'Kadar mempunyai dua tab. Kalendar Kadar menunjukkan harga semalaman terselesai setiap jenis bilik setiap tarikh — termasuk override dalam talian dan tahap jualan setiap sel. Pelan Kadar mengurus pelan bernama (standard, seasonal, promotional, corporate…) yang band kadarnya menghargakan jenis bilik merentasi julat tarikh; pelan keutamaan lebih tinggi menang apabila bertindih.' },
      {
        type: 'steps',
        steps: [
          { title: 'Baca kalendar dahulu', body: 'Lalui tarikh dan semak apa yang tetamu akan bayar setiap jenis bilik — sel menunjukkan kadar efektif, dari mana ia datang dan penghunian hari itu.' },
          { title: 'Edit dalam pelan kadar', body: 'Pelan baharu atau band pelan sedia ada menetapkan harga (atau pelarasan peratusan/tetap) setiap jenis bilik antara Sah dari dan Sah hingga, secara pilihan terhad mengikut tempoh penginapan dan pendahuluan tempahan.' },
          { title: 'Kemas kini pukal satu julat', body: 'Kadar pukal mengharga semula pelan merentasi julat tarikh dalam satu tindakan — band bertindih diselesaikan kepada tulisan terbaharu.' },
        ],
      },
      { type: 'callout', tone: 'important', body: 'Pelan kadar ialah alat harga sisi kakitangan — harga dalam talian awam masih datang daripada jenis bilik serta sebarang override Inventori Dalam Talian, yang menang atas setiap peraturan kadar.' },
    ],
  },
  {
    slug: 'guest-segments',
    title: 'Bina segmen tetamu',
    summary: 'Audiens tetamu berasaskan peraturan yang dinilai langsung — lampirkan satu pada kempen e-mel untuk menyempitkan penerimanya.',
    category: 'rates-promotions',
    keywords: ['segmen', 'audiens', 'sasaran tetamu', 'senarai pemasaran', 'peraturan', 'audiens kempen'],
    routePath: '/segments',
    requiredPermissions: ['segments:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'manage-guest-profiles', 'promotions-vouchers'],
    blocks: [
      { type: 'paragraph', text: 'Segmen ialah audiens dinamik berasaskan peraturan: satu set syarat atas data tetamu (negara, kiraan penginapan, tag, tier…) yang dinilai langsung semasa hantaran — bukan senarai tersimpan yang menjadi lapuk.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Segmen', body: 'segments:read menunjukkan perpustakaan; membina dan mengeditnya memerlukan segments:manage.' },
          { title: 'Cipta segmen', body: 'New segment menggabungkan baris medan, operator dan nilai — “country is one of…”, “stays at least…” — menjadi takrifan audiens.' },
          { title: 'Lampirkannya pada kempen', body: 'Pada Komunikasi → Kempen, pilih segmen untuk menyempitkan audiens hantaran — kiraan audiens dikemas kini langsung semasa anda memilih.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Oleh kerana segmen dinilai langsung, takrifan kempen yang sama sentiasa menghantar kepada tetamu yang sepadan hari ini — bukan sesiapa yang sepadan apabila senarai disimpan.' },
    ],
  },
  {
    slug: 'booking-channels',
    title: 'Urus saluran tempahan',
    summary: 'Saluran tempahan anda tiba — harga jualan, komisen dan matriks saluran.',
    category: 'rates-promotions',
    keywords: ['saluran', 'ota', 'booking.com', 'agoda', 'expedia', 'komisen', 'walk in', 'langsung', 'matriks saluran'],
    routePath: '/channels',
    requiredPermissions: ['channels:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['revenue-overview', 'online-inventory-grid', 'rates-and-rate-plans'],
    blocks: [
      { type: 'paragraph', text: 'Saluran menyenaraikan saluran pengedaran tempat tempahan boleh tiba — Langsung, Walk-in, Telefon dan OTA — setiap satu dengan persediaan harga jualan dan komisennya sendiri. Tab Matriks harga membariskan saluran berbanding jenis bilik supaya anda boleh melihat dan menyelaraskan keseluruhan grid sekaligus.' },
      {
        type: 'list',
        items: [
          'Rekod saluran membawa komisen yang diambil saluran — itulah yang menjadikan hasil bersih pada Hasil dan Wawasan berbeza daripada kasar.',
          'Mencipta dan mengedit saluran memerlukan channels:write; mengaktifkan dan memadamnya memerlukan channels:manage.',
          'Saluran sesuatu tempahan menentukan angka mana ia masuk pada laporan Hasil Bersih Saluran dan OTA dalam Wawasan.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Audit matriks selepas menambah jenis bilik — jenis tanpa baris saluran mengharga dari lalai, yang jarang menjadi apa yang anda maksudkan.' },
    ],
  },

  // ------------------------------------------------------ reports & night audit
  {
    slug: 'reports-and-metrics',
    title: 'Baca laporan dalam Wawasan',
    summary: 'Perpustakaan laporan Wawasan: laporan operasi, kewangan, analitik dan perakaunan — penghunian, hasil, jurnal, penyata dan banyak lagi.',
    category: 'reports-night-audit',
    keywords: ['laporan', 'insights', 'penghunian', 'adr', 'revpar', 'hasil', 'ketibaan', 'pelepasan', 'analitik', 'metrik', 'jurnal', 'kunci kira-kira', 'laporan syif', 'ota'],
    routePath: '/insights',
    requiredPermissions: ['analytics:read'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['run-night-audit', 'audit-log', 'revenue-overview'],
    blocks: [
      { type: 'paragraph', text: 'Wawasan ialah perpustakaan laporan — setiap laporan dipaparkan melalui satu paparan dengan penapisnya sendiri, dihimpun dalam empat keluarga. (Alamat /reports lama mengalih ke sini.)' },
      {
        type: 'list',
        items: [
          'Operasi — Operasi Harian (ketibaan, pelepasan, tetamu dalaman, kadar penghunian), Kadar Penghunian (dengan ADR dan RevPAR), Bilik Dijual, Prestasi Bilik, Laporan Syif dan Malam Percuma.',
          'Kewangan — Hasil, Hasil Bersih Saluran, Komisen OTA, Penyata Bulanan OTA dan Status Bayaran.',
          'Analitik — Statistik Tetamu: tetamu unik, baharu dan berulang, campuran warganegara dan tetamu teratas.',
          'Perakaunan — Jurnal Am, Jurnal mengikut Jenis, Kunci Kira-kira dan Penyata Lejar Syarikat (penyata setiap syarikat dengan penuaan).',
        ],
      },
      { type: 'heading', text: 'Dua metrik yang orang tanya' },
      {
        type: 'list',
        items: [
          'ADR — harga purata dibayar setiap bilik dijual: hasil bilik ÷ bilik dijual. Ia menjawab “adakah kita menjual tinggi?”',
          'RevPAR — hasil diagihkan atas setiap bilik yang anda miliki, dijual atau tidak: hasil bilik ÷ jumlah bilik. Ia menjawab “adakah kita memenuhkan pada kadar baik?”',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Kadar penghunian tanpa ADR menyorokkan diskaun; ADR tanpa penghunian menyorokkan bilik kosong. Baca kedua-duanya bersama.' },
    ],
  },
  {
    slug: 'run-night-audit',
    title: 'Jalankan audit malam',
    summary: 'Tutup hari perniagaan: sahkan audit, yang mengunci tempahan daripada editan dan merakamkan status bilik.',
    category: 'reports-night-audit',
    keywords: ['night audit', 'akhir hari', 'tutup hari', 'kunci tempahan', 'tarikh perniagaan'],
    routePath: '/night-audit',
    requiredPermissions: ['night_audit:execute'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['reports-and-metrics', 'audit-log', 'hotel-settings'],
    blocks: [
      { type: 'paragraph', text: 'Audit malam menutup hari perniagaan hotel. Mengesahkannya merekodkan siapa menjalankannya dan bila, mengunci tempahan hari itu daripada editan lanjut, dan boleh merakamkan status bilik untuk pelaporan.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Audit Malam', body: 'Cari ia di bawah menu Kewangan dan semak tarikh audit.' },
          { title: 'Semak apa yang larian itu akan lakukan', body: 'Pengesahan menyenaraikan pilihan — termasuk mengunci tempahan dan merekodkan gambaran status bilik.' },
          { title: 'Sahkan Audit Malam', body: 'Larian direkodkan dengan akaun dan cap masa anda; Log Audit mencerminkannya.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Penguncian adalah nyata', body: 'Selepas audit, tempahan hari itu menahan editan lanjut — jalankan apabila hari benar-benar selesai, atau gunakan tetapan auto-run dalam Tetapan Hotel.' },
      { type: 'callout', tone: 'tip', body: 'Tarikh perniagaan mengikut zon masa hotel dalam Tetapan Hotel — audit menutup hari itu, bukan tengah malam UTC.' },
    ],
  },
  {
    slug: 'audit-log',
    title: 'Guna audit log',
    summary: 'Rekod baca-sahaja tentang siapa mengubah apa — persinggahan pertama apabila sesuatu kelihatan berbeza daripada semalam.',
    category: 'reports-night-audit',
    keywords: ['audit log', 'sejarah', 'siapa mengubah', 'aktiviti', 'jejak'],
    routePath: '/audit-log',
    requiredPermissions: ['audit:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['page-missing-or-access-denied', 'run-night-audit', 'roles-and-permissions'],
    blocks: [
      { type: 'paragraph', text: 'Log Audit merekodkan tindakan mengubah merentasi sistem — perubahan tempahan, editan tetapan, kemas kini peranan, larian audit malam. Ia baca-sahaja mengikut reka bentuk.' },
      {
        type: 'list',
        items: [
          'Menyiasat tempahan atau tetapan yang berubah → mulakan di sini sebelum bertanya keliling.',
          'Semakan akses → log menunjukkan siapa memberi apa dan bila.',
          'Setiap entri menamakan pelaku dan cap masa, jadi susulan pergi kepada orang, bukan misteri.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Padankan dengan garis masa tempahan: log merekodkan tindakan, garis masa menceritakan kisah penginapan.' },
    ],
  },

  // ------------------------------------------------------------- communications
  {
    slug: 'email-campaigns-templates',
    title: 'Hantar kempen e-mel dan urus templat',
    summary: 'Bina templat e-mel boleh guna semula, kemudian hantar kempen kepada tetamu terpilih — dengan e-mel ujian sebelum apa-apa sebenar keluar.',
    category: 'communications',
    keywords: ['e-mel', 'kempen', 'templat', 'pengumuman', 'pemasaran', 'hantar ujian', 'pemboleh ubah'],
    routePath: '/communications',
    requiredPermissions: ['communications:compose', 'communications:send'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-not-sending', 'promotions-vouchers', 'guest-deliveries'],
    blocks: [
      { type: 'paragraph', text: 'Komunikasi mempunyai tiga tab: Kempen E-mel (hantaran sebenar), Templat (kandungan boleh guna semula dengan pemboleh ubah) dan Sekatan (alamat yang tidak boleh dihantar).' },
      {
        type: 'steps',
        steps: [
          { title: 'Cipta atau pilih templat', body: 'Templat membawa subjek dan isi dengan pemboleh ubah untuk nilai khusus tetamu.' },
          { title: 'Hantar e-mel ujian', body: 'Send test email membuktikan format dan penghantaran ke alamat anda sendiri sebelum mana-mana tetamu melihatnya.' },
          { title: 'Cipta kempen', body: 'Pilih jenis (contohnya Announcement), penerima — secara pilihan disempitkan kepada segmen tetamu — subjek dan isi, secara pilihan memautkan promosi.' },
          { title: 'Pantau hantaran', body: 'Cip status membaca Draf, Dijadualkan, Sedang berjalan, Selesai, Dibatalkan atau Gagal. Aktif, Dijeda dan Berakhir bukan status hantaran e-mel — Dijeda ada pada halaman tawaran Kempen, bersama Berlangsung, Tamat tempoh, Dibatalkan dan Diarkibkan. Kiraan Dihantar / Gagal dan lajur Ralat terakhir mendedahkan masalah.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Sentiasa hantar ujian dahulu — pemboleh ubah yang rosak memalukan pada skala besar.' },
    ],
  },
  {
    slug: 'notifications-guest-support',
    title: 'Notifikasi dan peti masuk sokongan tetamu',
    summary: 'Suapan notifikasi anda ialah untuk anda; peti masuk Sokongan ialah untuk tetamu — jawab mesej mereka di sana.',
    category: 'communications',
    keywords: ['notifikasi', 'loceng', 'peti masuk sokongan', 'mesej tetamu', 'perbualan', 'balas', 'lantik'],
    routePath: '/support',
    requiredPermissions: ['support:read', 'support:write'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-not-sending', 'manage-guest-profiles', 'guest-deliveries'],
    blocks: [
      { type: 'paragraph', text: 'Terdapat tiga permukaan “notifikasi” berbeza. Loceng di bar atas ialah pusat notifikasi kakitangan — makluman anda, notis sistem dan tier penghantaran. Sokongan di bawah Tetamu ialah peti masuk tempat mesej portal tetamu tiba — itu memerlukan balasan kakitangan. Penghantaran di bawah Utiliti ialah suapan e-mel tetamu keluar.' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Sokongan', body: 'Senarai perbualan menunjukkan perbualan tetamu terbuka, termasuk giliran belum dilantik.' },
          { title: 'Tuntut sebelum membalas', body: 'Perbualan belum dilantik mesti dituntut sebelum sesiapa membalas — oleh anda jika anda memegang support:assign atau support:manage, jika tidak oleh seseorang yang memegangnya. Akses tulis sahaja tidak mencukupi.' },
          { title: 'Baca dan balas', body: 'Buka perbualan untuk melihat mesej tetamu dan balas dalam talian. Setelah dilantik, pemegang lantikannya (atau pemegang support:manage) menjawabnya — bukan semua orang serentak.' },
          { title: 'Kemas kini status', body: 'Tutup atau kemas kini keadaan perbualan supaya giliran kekal tepat.' },
        ],
      },
      { type: 'callout', tone: 'info', title: 'Bukan sokongan IT kakitangan', body: 'Peti masuk ini ialah untuk tetamu yang meminta bantuan hotel. Untuk bantuan dengan portal admin sendiri, gunakan panduan “Dapatkan lebih bantuan” dalam Bantuan.' },
      { type: 'callout', tone: 'tip', body: 'Peti masuk sokongan boleh dimatikan untuk seluruh hartanah dalam Tetapan Hotel — jika keseluruhan modul hilang, togel itu ialah suspek pertama.' },
    ],
  },
  {
    slug: 'email-not-sending',
    title: 'E-mel tidak dihantar',
    summary: 'Kenal pasti kegagalan e-mel kempen dan notifikasi — kebanyakan punca kelihatan dalam lajur Ralat terakhir atau hantaran ujian yang gagal.',
    category: 'communications',
    keywords: ['e-mel gagal', 'smtp', 'tidak dihantar', 'ralat e-mel', 'kempen gagal', 'last error'],
    routePath: '/communications',
    requiredPermissions: ['communications:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'notifications-guest-support', 'escalation'],
    blocks: [
      { type: 'paragraph', text: 'E-mel berjalan melalui pekerja latar belakang yang memerlukan kelayakan SMTP dikonfigurasi pada pelayan. Apabila mel berhenti, buktinya hampir selalu pada halaman Komunikasi sendiri.' },
      {
        type: 'steps',
        steps: [
          { title: 'Hantar e-mel ujian', body: 'Ujian yang gagal membuktikan masalahnya ialah infrastruktur, bukan kandungan kempen anda.' },
          { title: 'Baca lajur Ralat terakhir', body: 'Hantaran kempen merekodkan sebab kegagalan setiap penerima — ralat pengesahan, sambungan dan alamat masing-masing bermaksud pembetulan berbeza.' },
          { title: 'Semak Kiraan Dihantar / Gagal', body: 'Kegagalan separa menunjuk kepada alamat penerima; kegagalan penuh menunjuk kepada konfigurasi SMTP.' },
          { title: 'Eskalasi masalah SMTP', body: 'Tetapan mel pelayan ialah konfigurasi persekitaran, bukan skrin dalam portal — serahkan kepada sesiapa yang mengurus penggunaan.' },
        ],
      },
      { type: 'callout', tone: 'important', body: 'Jika tiada tetapan SMTP wujud, pekerja e-mel sememangnya dimatikan — tiada apa rosak pada skrin anda, keupayaan itu tidak pernah dikonfigurasi.' },
    ],
  },
  {
    slug: 'guest-deliveries',
    title: 'Semak Penghantaran Tetamu',
    summary: 'Suapan e-mel tetamu keluar — setiap mesej yang hotel hantar atau antri, tier, status dan ralat terakhirnya.',
    category: 'communications',
    keywords: ['deliveries', 'penghantaran tetamu', 'suapan e-mel', 'peti keluar', 'e-mel dihantar', 'status penghantaran', 'queued', 'suppressed', 'transactional', 'marketing'],
    routePath: '/notifications',
    requiredPermissions: ['communications:read'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['email-campaigns-templates', 'email-not-sending', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: 'Halaman bertajuk Penghantaran Tetamu. Item bar sisi ialah Penghantaran, di bawah Utiliti — suapan e-mel tetamu keluar, berasingan daripada loceng. Setiap mesej yang hotel hantar atau antri muncul dengan penerima terlindung, jenisnya, tier, status, kiraan cubaan, ralat terakhir dan masa hantaran.' },
      {
        type: 'list',
        items: [
          'Tier Transaksi berbanding Pemasaran memisahkan resit dan mel tempahan daripada hantaran kempen.',
          'Penapis status menyempitkan kepada Dalam giliran, Menghantar, Dihantar, Gagal, Disekat atau Dibatalkan — baris gagal membawa ralat terakhir.',
          'Tab penghantaran loceng menunjukkan suapan yang sama dalam bentuk kecil; halaman ini ialah senarai penuh yang boleh ditapis.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Tetamu mendakwa resit tidak pernah tiba? Cari barisnya di sini dahulu — Dihantar, Gagal atau Disekat mengatasi meneka.' },
    ],
  },

  // -------------------------------------------------------------- staff & access
  {
    slug: 'add-manage-staff',
    title: 'Tambah dan urus akaun kakitangan',
    summary: 'Cipta log masuk untuk rakan sekerja, lantik peranan mereka, dan edit atau buang akaun dari Kawalan Akses.',
    category: 'staff-access',
    keywords: ['tambah pengguna', 'kakitangan baharu', 'akaun pekerja', 'cipta pengguna', 'padam pengguna', 'log masuk kakitangan'],
    routePath: '/rbac',
    requiredPermissions: ['users:create', 'users:update'],
    lastReviewed: '2026-10-05',
    featured: true,
    relatedSlugs: ['roles-and-permissions', 'sign-in-and-security', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'steps',
        steps: [
          { title: 'Buka Kawalan Akses', body: 'Cari ia di bawah menu Pentadbiran, kemudian buka tab Pengguna.' },
          { title: 'Pilih Tambah Pengguna', body: 'Dialog Cipta Pengguna Baharu mengumpul butiran akaun untuk ahli kakitangan baharu.' },
          { title: 'Lantik peranan', body: 'Peranan menentukan apa yang orang itu boleh lihat dan lakukan — penyambut tetamu dan pengurus mendapat portal berbeza. Lantik dalam aliran yang sama atau kemudian dari baris pengguna.' },
          { title: 'Edit atau buang kemudian', body: 'Edit Pengguna mengemas kini butiran; Padam Pengguna membuang akaun sepenuhnya apabila seseorang berhenti.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Peranan sebelum log masuk pertama', body: 'Pengguna tanpa peranan melihat hampir tiada apa — jika rakan sekerja melaporkan portal kosong, semak lantikan peranan mereka dahulu.' },
      { type: 'callout', tone: 'tip', body: 'Utamakan mengedit peranan berbanding mencipta akaun sekali sahaja; Log Audit menjejaki setiap perubahan walau apa pun.' },
    ],
  },
  {
    slug: 'roles-and-permissions',
    title: 'Peranan dan kebenaran',
    summary: 'Peranan menghimpun kebenaran; kebenaran mengawal halaman dan tindakan. Kebenaran *:manage merangkumi selebihnya dalam domainnya.',
    category: 'staff-access',
    keywords: ['peranan', 'kebenaran', 'rbac', 'kawalan akses', 'kebenaran manage', 'penyambut tetamu pengurus'],
    routePath: '/rbac',
    requiredPermissions: ['roles:read', 'roles:manage'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['add-manage-staff', 'page-missing-or-access-denied', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: 'Kawalan Akses mempunyai dua tab: Peranan & Kebenaran — himpunan bernama seperti Penyambut Tetamu atau Pengurus, dengan kebenaran individu dihimpun mengikut domain dalam setiap peranan — dan Pengguna, akaun kakitangan yang memegang peranan itu.' },
      {
        type: 'list',
        items: [
          'Kebenaran kelihatan seperti sumber:tindakan — contohnya bookings:create atau payments:refund.',
          'Kebenaran sumber:manage merangkumi setiap tindakan pada sumber itu.',
          'Dasar laluan memetakan halaman kepada kebenaran, sebab itulah menu berbeza setiap pengguna.',
          'Peranan sistem datang dengan pemberian munasabah; peranan tersuai boleh dicipta untuk persediaan luar biasa.',
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Mengubah peranan sistem mengubahnya untuk semua yang memegangnya — utamakan peranan baharu apabila seorang sahaja memerlukan sesuatu yang berbeza.' },
      { type: 'callout', tone: 'tip', body: 'Kebenaran dihimpun mengikut domain dalam setiap peranan pada Peranan & Kebenaran — kembangkan kategori untuk melihat dengan tepat apa yang peranan boleh lakukan.' },
    ],
  },
  {
    slug: 'ekyc-reviews',
    title: 'Semak penyerahan eKYC',
    summary: 'Kerja pengesahan identiti berlaku dalam giliran Pentadbir eKYC — penyemak yang dilantik bertindak pada penyerahan mengikut tahap risiko.',
    category: 'staff-access',
    keywords: ['ekyc', 'identiti', 'pengesahan', 'kyc', 'penyemak', 'pematuhan'],
    routePath: '/ekyc-admin',
    requiredPermissions: ['ekyc:review'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['roles-and-permissions', 'audit-log', 'manage-guest-profiles'],
    blocks: [
      { type: 'paragraph', text: 'Pentadbir eKYC ialah giliran semakan untuk pengesahan identiti elektronik. Peranan khusus — eKYC Reviewer, Senior Reviewer dan Compliance Administrator — mengendalikan penyerahan, dengan kes berisiko tinggi dieskalasi kepada semakan kanan.' },
      {
        type: 'list',
        items: [
          'Penyemak bertindak pada permohonan yang dilantik; penyemak kanan mengendalikan eskalasi dan kelulusan berisiko tinggi.',
          'Tindakan sensitif (mendedahkan dokumen, melihat data pembekal) mempunyai kebenaran tersendiri dan direkodkan.',
          'Jika anda tidak dapat melihat modul itu, anda tidak memegang peranan eKYC — itu mengikut reka bentuk, bukan pepijat.',
        ],
      },
      { type: 'callout', tone: 'info', body: 'Kebenaran eKYC sengaja terperinci — minta hanya tindakan yang diperlukan oleh tahap semakan anda.' },
    ],
  },

  // ------------------------------------------------------------- settings & data
  {
    slug: 'hotel-settings',
    title: 'Konfigurasi tetapan hotel',
    summary: 'Profil hartanah, waktu daftar masuk/out, zon masa, cukai, deposit, fon laporan dan togel ciri — lalai yang diwarisi oleh setiap skrin lain.',
    category: 'settings-data',
    keywords: ['tetapan', 'nama hotel', 'zon masa', 'waktu check in', 'cukai', 'deposit', 'cukai pelancongan', 'cukai perkhidmatan', 'konfigurasi'],
    routePath: '/settings',
    requiredPermissions: ['settings:update'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['run-night-audit', 'room-types-and-rooms', 'notifications-guest-support'],
    blocks: [
      { type: 'paragraph', text: 'Tetapan Hotel memegang lalai seluruh hartanah yang diwarisi skrin lain: nama dan butiran hubungan, waktu daftar masuk/daftar keluar, zon masa, jumlah deposit, kadar cukai perkhidmatan dan pelancongan, terma bayaran, tipografi laporan dan togel ciri.' },
      {
        type: 'list',
        items: [
          'Waktu daftar masuk dan daftar keluar menggerakkan gesaan daftar masuk awal dan sasaran pengemasan.',
          'Zon masa mentakrifkan tarikh perniagaan — laporan, audit malam dan “hari ini” semuanya mengikutnya.',
          'Jumlah deposit, cukai perkhidmatan dan cukai pelancongan memberi makan kepada jumlah tempahan; tetamu asing membawa cukai pelancongan.',
          'Togel sokongan dan pembatalan tetamu menghidupkan atau mematikan keseluruhan ciri.',
          'Tetapan fon laporan membentuk output cetakan.',
        ],
      },
      { type: 'callout', tone: 'important', title: 'Tingkap hold tanpa bayaran juga di sini', body: 'Unpaid hold release hours mengawal berapa lama tempahan Menunggu bayaran memegang bilik sebelum auto-release (lalai 24; 0 menyahaktif).' },
      { type: 'callout', tone: 'warning', body: 'Simpan tetapan terpakai serta-merta — kadar cukai atau zon masa yang salah menyentuh setiap tempahan baharu.' },
    ],
  },
  {
    slug: 'import-export-data',
    title: 'Import dan eksport data',
    summary: 'Pemindahan Data menggerakkan sandaran masuk dan keluar — empat tahap eksport, pratonton dahulu, dan pengesahan semula sebelum apa-apa yang istimewa atau memusnahkan.',
    category: 'settings-data',
    keywords: ['import', 'eksport', 'sandaran', 'pulih', 'pemindahan data', 'migrasi', 'pangkalan data', 'sandaran sistem', 'frasa laluan'],
    routePath: '/data-transfer',
    requiredPermissions: ['data_transfer:view'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['hotel-settings', 'audit-log', 'escalation'],
    blocks: [
      { type: 'paragraph', text: 'Pemindahan Data mengendalikan pemindahan data hotel masuk dan keluar — untuk sandaran, pemulihan dan migrasi. Apa yang anda boleh lakukan bergantung pada kebenaran data-transfer anda: melihat halaman, mengeksport dan mengimport masing-masing memerlukan kebenaran tersendiri, dan tindakan sulit atau memusnahkan turut meminta anda memasukkan semula kata laluan (dan kod pengesah, jika diaktifkan).' },
      {
        type: 'steps',
        steps: [
          { title: 'Buka Pemindahan Data', body: 'Memerlukan data_transfer:view. Tab Eksport menunjukkan empat tahap: Eksport standard (data operasi sahaja), Eksport penuh (semua data perniagaan boleh pindah), Sandaran migrasi (set data penuh serta metadata perhubungan) dan Sandaran sistem penuh (Pentadbir Super sahaja).' },
          { title: 'Eksport', body: 'Eksport standard memerlukan data_transfer:export. Eksport penuh dan Sandaran migrasi membawa data sulit tetamu, pembayaran dan lejar — ia memerlukan data_transfer:export_sensitive dan pengesahan semula baharu. Sandaran sistem penuh pergi lebih jauh: akaun pengguna, hash kata laluan, sesi, pemberian RBAC, rekod eKYC dan sejarah audit — ia Pentadbir Super sahaja dan failnya sentiasa disulitkan dengan frasa laluan yang anda bekalkan.' },
          { title: 'Semak pratonton import', body: 'Muat naik fail sandaran (data_transfer:import). Pratonton menunjukkan apa yang fail mengandungi, memberi amaran apabila ia membawa data sulit, dan menyebut kebenaran tambahan yang masih diperlukan.' },
          { title: 'Sahkan import', body: 'Merge menambah tanpa menyentuh baris sedia ada; pengendalian konflik “update” memerlukan data_transfer:override. Pemulihan penuh memadam data sedia ada dahulu dan memerlukan data_transfer:restore serta pengesahan semula. Teruskan hanya pada fail yang anda percayai.' },
          { title: 'Semak Sejarah', body: 'Import, eksport dan percubaan pengesahan semula lalu disenaraikan dengan siapa menjalankannya — baris yang sama direkodkan dalam Log Audit.' },
        ],
      },
      { type: 'callout', tone: 'important', title: 'Memusnahkan mengikut reka bentuk', body: '“This deletes all existing data first” adalah literal — pemulihan penuh menggantikan pangkalan data. Sahkan fail dan pemasaan dengan pentadbir anda.' },
      { type: 'callout', tone: 'tip', title: 'Rahsia kekal dalam tahap teratas', body: 'Eksport standard, Eksport penuh dan Sandaran migrasi tidak pernah mengandungi kelayakan — kata laluan, sesi, token atau bukti pengesahan identiti. Sandaran sistem penuh sengaja merangkuminya supaya ia boleh membina semula log masuk pada pemasangan baharu; sebab itulah ia kekal disulitkan, dikawal frasa laluan dan Pentadbir Super sahaja. Simpan frasa laluan di tempat selamat — ia tidak boleh dipulihkan.' },
    ],
  },
  {
    slug: 'system-health-and-jobs',
    title: 'Kesihatan Sistem dan Tugasan',
    summary: 'Papan pemuka Pentadbiran untuk platform itu sendiri — kesihatan perkhidmatan dan tugas latar belakang yang mengekalkan hotel berjalan.',
    category: 'settings-data',
    keywords: ['kesihatan sistem', 'tugas', 'tugas latar belakang', 'penjadual', 'status perkhidmatan', 'tugas audit malam', 'uptime'],
    routePath: '/system-health',
    requiredPermissions: ['settings:manage'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['hotel-settings', 'audit-log', 'run-night-audit'],
    blocks: [
      { type: 'paragraph', text: 'Dua skrin Pentadbiran menjaga platform dan bukan hartanah. Kesihatan Sistem melaporkan keadaan penggunaan — status perkhidmatan, pangkalan data dan kesihatan pekerja. Tugasan menyenaraikan tugas latar belakang yang pelayan jalankan mengikut jadual — audit malam, pelepasan hold tanpa bayaran, resit bayaran, hantaran komunikasi — dengan keadaan larian terakhirnya.' },
      {
        type: 'list',
        items: [
          'Semak Kesihatan Sistem dahulu apabila beberapa skrin tidak bertingkah serentak — ia memisahkan masalah aplikasi daripada masalah data.',
          'Tugasan menunjukkan sama ada kerja berjadual berjalan — tugas night-audit atau e-mel yang lapuk menjelaskan laporan “ia berhenti sendiri”.',
          'Kedua-duanya wilayah settings:manage — jika anda tidak dapat melihatnya, itu paparan pentadbir.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Baris tugas gagal serta Log Audit biasanya menamakan puncanya — bawa kedua-duanya apabila anda eskalasi.' },
    ],
  },

  // ------------------------------------------------------------- troubleshooting
  {
    slug: 'cant-find-a-booking',
    title: 'Tidak jumpa tempahan?',
    summary: 'Lalui senarai semak: istilah carian, penapis, dan dua keadaan (void, released) yang menyembunyikan tempahan daripada paparan biasa.',
    category: 'troubleshooting',
    keywords: ['tempahan hilang', 'tempahan tidak jumpa', 'tiada hasil', 'lesap'],
    routePath: '/bookings',
    lastReviewed: '2026-10-05',
    relatedSlugs: ['find-a-reservation', 'void-reactivate-release', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          'Cuba kod tempahan dalam ⌘K — kod BK- dan nama tetamu kedua-duanya mencari.',
          'Buang penapis pada senarai Tempahan — istilah carian tertinggal, cip paparan seperti Ketibaan atau Baki Tertunggak, atau penapis tarikh/bulan ialah punca biasa.',
          'Semak tarikh: penginapan mungkin berada di luar julat yang anda lihat.',
          'Tanya sama ada tempahan telah void — penginapan void meninggalkan paparan biasa.',
          'Semak hold tanpa bayaran yang dilepaskan — tempahan dalam talian yang tidak pernah dibayar dilepaskan semula ke inventori secara automatik.',
          'Sahkan anda dapat melihat Tempahan langsung — modul yang hilang ialah soalan kebenaran, bukan masalah carian.',
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Garis masa tempahan dan Log Audit kedua-duanya tahan terhadap pembatalan — jika tempahan itu pernah wujud, kisahnya masih ada.' },
    ],
  },
  {
    slug: 'payment-problems',
    title: 'Masalah bayaran',
    summary: 'Bayaran dalam talian gagal, kelulusan tersangkut dan ralat bayaran balik — padankan simptom dengan giliran yang betul.',
    category: 'troubleshooting',
    keywords: ['bayaran gagal', 'ralat bayaran', 'ditolak', 'pulih bayaran', 'kelulusan tersangkut', 'ralat refund'],
    routePath: '/payment-approvals',
    lastReviewed: '2026-10-05',
    relatedSlugs: ['refund-a-deposit', 'review-payment-approvals', 'email-not-sending'],
    blocks: [
      {
        type: 'list',
        items: [
          'Bayaran tetamu gagal dalam talian → e-mel pemulihan bayaran boleh membiarkan mereka cuba semula melalui pautan selamat — semak keadaan tempahan sebelum menganggap wang itu hilang.',
          'Bukti bayaran menunggu → ia berada dalam Kelulusan Pembayaran sehingga seseorang menyemaknya; tetamu melihat “submitted”, bukan “confirmed”.',
          'Butang bayaran balik hilang → anda memerlukan payments:refund; mengembalikan semula bayaran balik memerlukan payments:manage.',
          'Tempahan tersangkut dalam Menunggu bayaran → ia ialah hold tanpa bayaran; ia auto-release atau boleh dilepaskan secara manual.',
        ],
      },
      { type: 'callout', tone: 'warning', body: 'Jangan “perbaiki” bayaran tersangkut dengan mengedit tempahan — selesaikan giliran kelulusan atau eskalasi; lejar dan jejak audit memerlukan sebab yang sebenar.' },
    ],
  },
  {
    slug: 'session-and-stale-data',
    title: 'Isu sesi dan data lapuk',
    summary: 'Apabila skrin kelihatan lapuk atau sesi tidak bertingkah — susunan refresh, tamat masa terbiar dan perangkap tarikh perniagaan.',
    category: 'troubleshooting',
    keywords: ['data lapuk', 'refresh', 'sesi tamat', 'keluar log', 'tarikh salah', 'zon masa'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['sign-in-and-security', 'hotel-settings', 'page-missing-or-access-denied'],
    blocks: [
      {
        type: 'checklist',
        items: [
          'Refresh halaman — selepas tempoh terbiar yang lama token sesi diperbaharui secara automatik; skrin lapuk hanya memerlukan muat semula.',
          'Log keluar dan masuk semula jika keadaan sesi tidak konsisten — ikon Log Keluar berada di hujung kanan bar atas (ia disembunyikan pada skrin selebar telefon).',
          'Tarikh kelihatan salah → tarikh perniagaan mengikut zon masa hotel dalam Tetapan Hotel, bukan jam komputer riba anda.',
          'Tetapan berubah tetapi tiada apa bergerak → sesetengah perubahan terpakai pada aktiviti baharu sahaja, bukan secara retroaktif.',
          'Peranti lain kelihatan berbeza → tema dan bahasa mengikut stesen kerja, kebenaran mengikut akaun.',
        ],
      },
      { type: 'callout', tone: 'info', body: 'Log keluar berulang bukan kerosakan — token akses jangka pendek mengikut reka bentuk dan diperbaharui secara senyap di latar belakang.' },
    ],
  },
  {
    slug: 'escalation',
    title: 'Dapatkan lebih bantuan',
    summary: 'Apa yang perlu dilakukan apabila Bantuan tidak menyelesaikannya — siapa untuk ditanya dan apa yang perlu dibawa kepada mereka.',
    category: 'troubleshooting',
    keywords: ['hubungi', 'eskalasi', 'pengurus', 'pentadbir', 'lebih bantuan', 'sokongan'],
    lastReviewed: '2026-10-05',
    relatedSlugs: ['page-missing-or-access-denied', 'payment-problems', 'audit-log'],
    blocks: [
      { type: 'paragraph', text: 'Bantuan merangkumi cara portal berfungsi. Untuk akses akaun, perubahan kebenaran dan apa-apa yang kelihatan seperti kecacatan, eskalasi dalam rantaian hartanah anda sendiri.' },
      {
        type: 'steps',
        steps: [
          { title: 'Tanya pentadbir atau pengurus anda', body: 'Perubahan akses, peranan dan tetapan adalah milik mereka — bawa nama halaman dan apa yang anda jangkakan untuk dilihat.' },
          { title: 'Bawa bukti', body: 'Entri Log Audit, kod tempahan, teks Ralat terakhir kempen — rekod tertentu mengalahkan penerangan simptom.' },
          { title: 'Untuk isu berdepan tetamu', body: 'Jika tetamu melaporkan masalah, semak peti masuk Sokongan untuk perbualan sedia ada mereka dan bukannya memulakan urutan selari.' },
        ],
      },
      { type: 'callout', tone: 'tip', body: 'Tangkapan skrin membantu, tetapi teks ralat tepat dan masa ia berlaku membantu lebih — kedua-duanya berada dalam rekod aplikasi sendiri.' },
    ],
  },
];
