#!/usr/bin/env node
/**
 * i18n-scan.mjs — hardcoded user-visible string sweep for the i18n rollout.
 *
 * Walks a source directory (default `src`) and prints candidate literals that
 * should route through `t()`/`tOr()` but do not. Pure Node, no dependencies —
 * run it from the hotel-web-fe root:
 *
 *   bun scripts/i18n-scan.mjs                 # scan src/
 *   bun scripts/i18n-scan.mjs src/features/admin
 *
 * Output, one finding per line:
 *
 *   src/path/File.tsx:LINE  KIND  literal
 *
 * Kinds:
 *   jsx-text    literal JSX text node            >Save changes<
 *   jsx-expr    literal inside a {} expression   {'Save'}  cond && 'Save'  c ? 'A' : 'B'
 *   attr:<name> literal JSX attribute            placeholder="Search"
 *   prop:<name> literal object property          { label: 'Name' }
 *
 * The attr/jsx-text heuristics mirror what the Task-16 audit test enforces
 * (literal JSX text + literal placeholder|title|aria-label|alt|label|
 * helperText|headerName attributes); prop and jsx-expr additionally surface
 * enum label maps, DataGrid headerName columns, menu items, and `cond &&
 * 'text'` idioms so domain sweeps see them too.
 *
 * A finding is a *candidate*, not a verdict: exempt values are filtered by the
 * allowlist below; anything borderline is printed for a human to judge.
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, resolve, sep } from 'node:path';

// ---------------------------------------------------------------------------
// Exempt paths — tested against the path relative to src/ when the file lives
// under src/, else relative to cwd. Mirrors the plan's do-not-translate list:
//   * i18n/        — the engine + JSON bundles themselves (machinery)
//   * test/, *.test.*, *.spec.* — test code
//   * routeTree.gen.ts — generated by TanStack Router
//   * ds-bundle/   — design preview package, not shipped app UI
//   * features/legal/content/ — PDPA notice corpus, en/ms only by design
//   * features/help/content/  — help article corpus (own en/ms parity test,
//                               maintained outside the JSON bundle system)
// ---------------------------------------------------------------------------
const EXEMPT_PATH_PATTERNS = [
  /(^|\/)i18n\//,
  /(^|\/)test\//,
  /(^|\/)ds-bundle\//,
  /(^|\/)features\/legal\/content\//,
  /(^|\/)features\/help\/content\//,
  /(^|\/)routeTree\.gen\.ts$/,
  /\.(test|spec)\.[tj]sx?$/,
  /\.d\.ts$/,
];

// ---------------------------------------------------------------------------
// Exempt literals — values that are never translated: currency codes, brand
// names/app title, N/A, ellipsis/keyboard glyphs, developer error codes.
// ---------------------------------------------------------------------------
const ALLOWED_LITERALS = new Set([
  'RM',
  'MYR',
  'N/A',
  '…',
  '×',
  'ERROR',
  'Hotel ERP System', // brand fallback title (GuestRootLayout FALLBACK_APP_TITLE)
  'Hotel ERP',
]);

// Patterns applied to the trimmed literal — a match means "do not report".
const ALLOWED_PATTERNS = [
  /[{}]/,                                          // '{'-expression fragment, not text
  /^\p{Lu}*[\d&+\/._-][\p{Lu}\d&+\/._ -]*$/u,      // codes w/ digit or symbol: 2FA, V1
  /^[dMyLhHmsS]{1,5}([\/\-.,:\s][dMyLhHmsS]{1,5})+$/, // date-format tokens: dd/MM/yyyy, HH:mm
  /^[a-zA-Z][\w-]*([.:][\w-]+)+$/,                 // translation-key shaped: ns:key, a.b.c
  /^\/[\w-]*(\/[\w-]*)*$/,                         // route/path shaped: /bookings
  /^#/,                                            // CSS colour: '#fff'
  /^var\(/,                                        // CSS variable: 'var(--hotel-…)'
  /^[a-z][a-zA-Z-]*\([^)]*\)$/,                    // CSS function: 'rotate(180deg)'
  /^(?:color-mix|light-dark|env|image-set)\(/,     // nested-paren CSS functions
  /^-?[\d.]+(px|em|rem|deg|vh|vw|s|ms|fr|ch|ex|%)$/, // CSS measure: '-0.015em'
];

// jsx-text heuristic: a "text node" that starts with a closing bracket, comma,
// colon or `=`, ends with an opening bracket, looks like a TS signature
// (`(cmd: string, args?: Record`), or carries a JS operator is really a code
// fragment caught between JSX siblings (`) : cond ? (`, `= TanStackColumnDef`,
// `(KEY) ?? store.get`).
const JSX_CODE_FRAGMENT_RE =
  /^[)\],;:}=\[]|^[(\[][^<]*:|[([{&|]$|==|!=|&&|\|\||\?\?|\?\.|=>|\.\w+\s*\(/;

// Attribute / property names whose literal values are user-visible.
const TEXT_PROP_NAMES = [
  'placeholder',
  'title',
  'aria-label',
  'ariaLabel',
  'alt',
  'label',
  'helperText',
  'headerName',
];

const NAME_RE = TEXT_PROP_NAMES.map((n) => n.replace(/-/g, '\\-')).join('|');

// Literal JSX attributes:  name="…" | name='…' | name={"…"} | name={'…'}
const JSX_ATTR_RE = new RegExp(
  `(?<=[\\s{(])(${NAME_RE})\\s*=\\s*(?:"([^"\\\\]*)"|'([^'\\\\]*)'|\\{\\s*"([^"\\\\]*)"\\s*\\}|\\{\\s*'([^'\\\\]*)'\\s*\\})`,
  'g'
);

// Literal object properties:  name: '…' | name: "…" (unquoted keys) and
// 'name': '…' (quoted keys, e.g. inputProps={{ 'aria-label': '…' }}).
const OBJ_PROP_RE = new RegExp(
  `(?<=[{,\\s])(${NAME_RE})\\s*:\\s*(?:"([^"\\\\]*)"|'([^'\\\\]*)')`,
  'g'
);
const QUOTED_PROP_RE = new RegExp(
  `['"](${NAME_RE})['"]\\s*:\\s*(?:'([^'\\\\]*)'|"([^"\\\\]*)")`,
  'g'
);

// Literal JSX text nodes: `>` …letters… `<`. The lookbehind restricts `>` to
// positions that can close a tag (tag name, quote, /, fragment <>, or a
// preceding `{…}`/`>`), so `a > b`, `(x) > (y)` and `=>` arrows do not produce
// text nodes; `(?!=)` additionally rejects `>=`. `;` is excluded from the text
// body — real JSX prose almost never carries one, and excluding it stops
// generic-call spans like `createContext<T>(…); … React.FC<` matching as text.
const JSX_TEXT_RE = /(?<=[A-Za-z0-9"'`\/><}])>(?!=)([^<>{};]*\p{L}[^<>{};]*)</gu;

// Any string literal — filtered afterwards by surrounding context so that
// {'…'}, {cond && '…'} and {cond ? '…' : '…'} surface while call arguments
// (t('key'), new Error(…)) and object keys do not.
const ANY_STRING_RE = /'([^'\\\n]*)'|"([^"\\\n]*)"/g;

// Lines whose findings are developer-only, never user-visible.
const DEV_ONLY_LINE_RE = /\bconsole\.|new Error\s*\(|throw\s+new\b/;

const SOURCE_EXTENSIONS = new Set(['.ts', '.tsx', '.js', '.jsx']);

// ---------------------------------------------------------------------------

/**
 * Blank out // and /* *‍/ comment bodies (preserving offsets and newlines) so
 * doc examples like `title="x"` inside comments are not reported. String and
 * template literals are tracked so `//` inside 'https://…' is not a comment.
 */
function blankComments(src) {
  const out = src.split('');
  const n = src.length;
  let i = 0;
  let mode = 'code'; // code | line | block | sq | dq | tpl
  while (i < n) {
    const c = src[i];
    const next = src[i + 1];
    if (mode === 'code') {
      if (c === '/' && next === '/') mode = 'line';
      else if (c === '/' && next === '*') mode = 'block';
      else if (c === "'") mode = 'sq';
      else if (c === '"') mode = 'dq';
      else if (c === '`') mode = 'tpl';
    } else if (mode === 'line') {
      if (c === '\n') mode = 'code';
      else out[i] = ' ';
    } else if (mode === 'block') {
      if (c === '*' && next === '/') {
        out[i] = ' ';
        out[i + 1] = ' ';
        i += 1;
        mode = 'code';
      } else if (c !== '\n') {
        out[i] = ' ';
      }
    } else {
      // inside a string/template literal
      if (c === '\\') i += 1; // skip the escaped char
      else if (
        (mode === 'sq' && c === "'") ||
        (mode === 'dq' && c === '"') ||
        (mode === 'tpl' && c === '`')
      ) {
        mode = 'code';
      } else if (mode !== 'tpl' && c === '\n') {
        mode = 'code'; // unterminated string — recover at EOL
      }
    }
    i += 1;
  }
  return out.join('');
}

function lineNumberAt(lineStarts, index) {
  let lo = 0;
  let hi = lineStarts.length - 1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (lineStarts[mid] <= index) lo = mid;
    else hi = mid - 1;
  }
  return lo + 1;
}

function isAllowedLiteral(text, kind) {
  if (text.length <= 1) return true; // empty, single chars, keyboard glyphs
  if (ALLOWED_LITERALS.has(text)) return true;
  if (!/\p{L}/u.test(text)) return true; // digits/punctuation/glyphs: … × ⌘ 100%
  for (const pattern of ALLOWED_PATTERNS) {
    if (pattern.test(text)) return true;
  }
  if (kind === 'jsx-text' && JSX_CODE_FRAGMENT_RE.test(text)) return true;
  // {cond && 'primary'}, {x ? 'en' : 'ms'}, {ch === 'ONL'} — in expression
  // positions a lowercase/camelCase/short-CAPS token is an enum, style,
  // locale, or channel code, not prose.
  if (
    kind === 'jsx-expr' &&
    (/^[a-z0-9]+([ ._\/-][a-z0-9]+)*$/.test(text) ||
      /^[a-z]+([A-Z][a-zA-Z0-9]*)+$/.test(text) ||
      /^\p{Lu}{2,6}$/u.test(text))
  ) {
    return true;
  }
  return false;
}

function isExemptPath(relPath) {
  return EXEMPT_PATH_PATTERNS.some((p) => p.test(relPath));
}

function collectFiles(dir, srcRoot, cwd, files) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === 'node_modules' || entry.name.startsWith('.')) continue;
    const full = join(dir, entry.name);
    const relSrc = relative(srcRoot, full).split(sep).join('/');
    const rel = relSrc.startsWith('..')
      ? relative(cwd, full).split(sep).join('/')
      : relSrc;
    if (entry.isDirectory()) {
      if (!isExemptPath(rel + '/')) collectFiles(full, srcRoot, cwd, files);
      continue;
    }
    const dot = entry.name.lastIndexOf('.');
    if (!SOURCE_EXTENSIONS.has(entry.name.slice(dot))) continue;
    if (isExemptPath(rel)) continue;
    files.push(full);
  }
}

function scanFile(path) {
  const source = readFileSync(path, 'utf8');
  const code = blankComments(source);

  const lineStarts = [0];
  for (let i = 0; i < source.length; i += 1) {
    if (source[i] === '\n') lineStarts.push(i + 1);
  }
  const lineAt = (index) => lineNumberAt(lineStarts, index);
  const lineTextAt = (index) => {
    const start = lineStarts[lineAt(index) - 1];
    const end = source.indexOf('\n', start);
    return source.slice(start, end === -1 ? undefined : end);
  };

  const findings = [];
  const reported = new Set(); // index dedupe across kinds

  const consider = (index, kind, raw) => {
    const text = raw.trim().replace(/\s+/g, ' ');
    if (isAllowedLiteral(text, kind)) return;
    if (DEV_ONLY_LINE_RE.test(lineTextAt(index))) return;
    if (reported.has(index)) return;
    reported.add(index);
    findings.push({ index, line: lineAt(index), kind, text });
  };

  for (const m of code.matchAll(JSX_TEXT_RE)) {
    // report the line the text starts on (m.index is the closing `>` of the tag)
    const leadWs = m[1].length - m[1].trimStart().length;
    consider(m.index + 1 + leadWs, 'jsx-text', m[1]);
  }

  for (const m of code.matchAll(JSX_ATTR_RE)) {
    consider(m.index, `attr:${m[1]}`, m[2] ?? m[3] ?? m[4] ?? m[5] ?? '');
  }

  for (const m of code.matchAll(OBJ_PROP_RE)) {
    consider(m.index, `prop:${m[1]}`, m[2] ?? m[3] ?? '');
  }
  for (const m of code.matchAll(QUOTED_PROP_RE)) {
    consider(m.index, `prop:${m[1]}`, m[2] ?? m[3] ?? '');
  }

  // String literals in expression positions: {'x'}, cond && 'x', a ?? 'x',
  // cond ? 'x' : 'y'. Call arguments (preceded by `(` or `,`) and object keys
  // are skipped, so t('key')/tOr('k','fb') never surface. A trailing `:` is an
  // object key only when no `?` opened a ternary earlier on the same line —
  // `cond ? 'a' : 'b'` flags both arms, `{ 'key': v }` flags neither.
  for (const m of code.matchAll(ANY_STRING_RE)) {
    const value = m[1] ?? m[2] ?? '';
    const start = m.index;
    const end = start + m[0].length;

    const lineStart = lineStarts[lineAt(start) - 1];
    const before = code.slice(lineStart, start);
    const ternaryQ = before.lastIndexOf('?');
    const boundary = Math.max(
      before.lastIndexOf('{'),
      before.lastIndexOf('}'),
      before.lastIndexOf(','),
      before.lastIndexOf(';')
    );
    const inTernary = ternaryQ > boundary;

    let j = end;
    while (j < code.length && /\s/.test(code[j])) j += 1;
    if (code[j] === ':' && !inTernary) continue; // object key, not a value

    let k = start - 1;
    while (k >= 0 && /\s/.test(code[k])) k -= 1;
    const prev = code[k];

    if (prev === '{') {
      // {'x'} — unless the {} is an attribute value (name={'x'}), which the
      // attr pass already reported.
      let q = k - 1;
      while (q >= 0 && /\s/.test(code[q])) q -= 1;
      if (code[q] === '=') continue;
      consider(start, 'jsx-expr', value);
    } else if (prev === '?' || prev === '&' || prev === '|') {
      consider(start, 'jsx-expr', value); // cond && 'x', a ?? 'x', c ? 'x'
    } else if (prev === ':' && inTernary) {
      consider(start, 'jsx-expr', value); // second arm of cond ? 'a' : 'b'
    }
  }

  return findings.sort((a, b) => a.index - b.index);
}

function main() {
  const arg = process.argv[2] ?? 'src';
  const root = resolve(process.cwd(), arg);
  const cwd = process.cwd();
  const srcRoot = resolve(cwd, 'src');

  let stats;
  try {
    stats = statSync(root);
  } catch {
    console.error(`i18n-scan: no such path: ${arg}`);
    console.error('usage: bun scripts/i18n-scan.mjs [dir]   (default: src)');
    process.exit(2);
  }

  const files = [];
  if (stats.isDirectory()) {
    collectFiles(root, srcRoot, cwd, files);
  } else {
    const relSrc = relative(srcRoot, root).split(sep).join('/');
    const rel = relSrc.startsWith('..') ? relative(cwd, root).split(sep).join('/') : relSrc;
    if (isExemptPath(rel)) {
      console.error(`note: ${rel} is on the exempt list (scanning anyway)`);
    }
    files.push(root);
  }
  files.sort();

  let count = 0;
  const filesWithFindings = new Set();
  for (const file of files) {
    const rel = relative(cwd, file).split(sep).join('/');
    for (const f of scanFile(file)) {
      count += 1;
      filesWithFindings.add(file);
      console.log(`${rel}:${f.line}  ${f.kind}  ${f.text}`);
    }
  }
  console.error(
    `\n${count} candidate(s) in ${filesWithFindings.size} file(s); ${files.length} file(s) scanned under ${arg}`
  );
}

main();
